penumbra-zone/web

apps/extension/package.json, apps/extension/src/state/password.test.ts, apps/extension/src/storage/base.ts, apps/extension/src/storage/local.ts, apps/extension/src/storage/migration.test.ts, apps/extension/src/storage/mock.ts, apps/extension/src/storage/session.ts, apps/extension/src/types/utility.ts, apps/extension/src/utils/assertions.ts, apps/webapp/package.json, package.json, packages/eslint-config-custom/index.js, packages/eslint-config-custom/package.json, packages/ui/package.json, pnpm-lock.yaml
Will _hopefully_ reduce the cases of needing users to re-install the extension. This persists versioned storage that we can define migration functions for.
=> Add ability to migrate storage

apps/extension/src/controllers/services.ts, apps/extension/src/service-worker.ts
When re-building and deploying new code, the new service worker "waits" to take over the old one. This appears to cause the messaging connection to break. The error reads:
```
could not establish connection. receiving end does not exist
```
This PR mitigates this by forcing the new service worker to replace the old one as soon as it's installed.
=> Service worker forced handover

packages/query/src/block-processor.ts, packages/wasm/src/sct.test.ts, packages/wasm/src/sct.ts
- Enables marking notes as spent via nullifiers
- Validates SCT tree (need to add debug flag)
- Adds generated metadata to storage if no metadata in remote
=> Nullifiers + SCT validation

packages/wasm/package.json, packages/wasm/src/view-server.test.ts, pnpm-lock.yaml
Turns out the new `ViewServer` has a requirement to open up a IndexedDb connection. On web, that's fine. But for our nodejs tests, we have to import a faux indexed db or it will throw.
=> Re-enable wasm test

apps/extension/src/hooks/last-block-synced.ts, apps/extension/src/routes/popup/home/block-sync.tsx, apps/extension/src/services/index.ts, packages/query/src/block-processor.ts
Closes https://github.com/penumbra-zone/web/issues/62
- Allows for retries of `getWalletServices()` on subsequent calls instead of settling on a reject promise
- Makes `syncBlocks()` not spin up more instances if called twice
- Popup on init sends "SYNC-BLOCKS" request on startup to wake the service worker up
=> Re-initialization of wallet services [bug fix]

apps/extension/src/services/index.ts, apps/extension/webpack/webpack.dev.js
closes #67
Realized we probably should not be overriding the default service worker lifecycle for installing and taking over. In production, the old service worker should be able to transition to the new when it's ready to. However, in dev mode, we want to rapidly transition and not wait.
Had to add this code as a banner given our webpack config prevents top level listeners.
=> Skip waiting in dev

.github/workflows/deploy-firebase-dapp.yml
Follow up to [0]. Post merge of the new Firebase deploy config, the GHA failed [1], not able to find `turbo`. Makes sense: we didn't install it! Let's run the `pnpm install` command, same as used in the other workflows.
[0] https://github.com/penumbra-zone/web/pull/48
[1] https://github.com/penumbra-zone/web/actions/runs/6404599868/job/17385485760#step:5:14
=> ci: install deps prior to running turbo

apps/extension/src/routes/popup/home/index.tsx, apps/extension/src/state/accounts.ts, packages/ui/components/ui/identicon/index.tsx
Closes #76
I'm not entirely the biggest fan (design wise) of the double bar/identicon. But we need a way to communicate the wallet id as this will be the address/identicon that shows when you are connected to the web app.
=> Add wallet id to popup

apps/extension/package.json, apps/extension/src/content-scripts.ts, apps/extension/src/hooks/chain-id.ts, apps/extension/src/popup.tsx, apps/extension/src/routes/popup/home/index-header.tsx, apps/extension/src/routes/popup/home/index.tsx, apps/extension/src/routes/service-worker/root-router.ts, apps/extension/src/routes/service-worker/view-protocol-server/router.ts, apps/extension/src/services/clients.ts, apps/webapp/app/balances/display-balances.tsx, apps/webapp/app/chain-params/index.tsx, apps/webapp/app/header/header.tsx, apps/webapp/app/header/network.tsx, apps/webapp/app/page.tsx, apps/webapp/app/transactions/all-transactions.tsx, apps/webapp/hooks/balances.ts, apps/webapp/hooks/chain-id.ts, packages/transport/package.json, packages/transport/src/internal.ts, packages/ui/components/ui/networks-popover.tsx, pnpm-lock.yaml
Dapp+Popup can now display current chain id:
New routing types + grpc client exposed to internal messages
=> Extending grpc to internal messages

apps/extension/src/state/seed-phrase/import.test.ts, apps/extension/src/state/seed-phrase/import.ts
If pasting a seed phrase longer than twelve, the import box will now grow to twenty four to accommodate
=> Extend length importing seedphrase

packages/ui/components/ui/tx/view/address-view.tsx
Per discussion on discord and twitter, this seems clearer for users to understand than "ephemeral address".
=> Use 'One-time Address' terminology

packages/ui/components/ui/tx/view/viewbox.tsx
The structure is actually publicly visible, so we should render it as such.
=> Show labels for encrypted data

packages/tsconfig/vite.json
Removes the necessity for declaration files to be emit with the vite app. It's not necessary and causing IDE warnings.
=> Do not emit declaration map

packages/storage/src/chrome/syncer.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts
We'll get a display bug if we don't execute 
```typescript
void localExtStorage.set('lastBlockSynced', 0); 
``` 
The synс progress bar will display the old value of `lastBlockSynced`, while in fact sync started from 0 block
=> 252 need to clear indexed db during version migration

apps/extension/src/injected-penumbra-global.ts
[Bug] Other wallet extensions block transport between the webapp and extension
Fixes #297
obviously intended to be inside the conditional, but i guess there is not really any reason to deactivate it
=> don't remove init listener after activation

packages/router/src/grpc/custody/authorize.ts
After the user approves the popup, if they are not logged in, an error is thrown. This PR moves that check up so that the user doesn't get an approval popup without being logged in first.
=> Require login before tx popup

apps/extension/src/service-worker.ts, packages/transport/src/chrome-runtime/adapter.ts
this is a temp workaround. we could also 
1) do nothing. it's not the end of the world to default to concealed errors
2) manually try/catch in impls
3) [PR connectrpc](https://github.com/connectrpc/connect-es/compare/main...turbocrime:connect-es:internal-errors)
=> wrap impls to rethrow

packages/ui/components/ui/tx/view/address-view.test.tsx, packages/ui/components/ui/tx/view/address-view.tsx, packages/ui/package.json, packages/ui/tests-setup.js, packages/ui/vitest.config.ts, pnpm-lock.yaml
🚨 Note that hundreds of the line changes are just from `pnpm-lock.yaml`
Per #173, we should hide the copy button for one-time addresses, since they should never be reused and thus don't need to be copied.
- Hide the copy button for one-time addresses
- Set up test infrastructure with Vitest + JSDom + React Testing Library for the `ui` package. This adds a bit of scope to the PR, but I figured it'd be worth it so that we can start writing tests for all of our UI components. Let me know what y'all think of the setup.
Closes #173
=> Hide the copy button for one-time addresses

apps/webapp/src/components/header/header.tsx, apps/webapp/src/components/header/navbar.tsx, apps/webapp/src/icons/index.tsx, apps/webapp/src/icons/message-warning.tsx, packages/ui/components/ui/networks-popover.tsx
- Add a feedback button to the web app, which links to an invite the `#web-ext-feedback` Discord channel.
- Tweak the layout of the header so that, instead of having a fixed gap between header links, it is responsive to the width of the window.
Closes #221
=> Add a feedback button to the header of the web app

packages/query/src/block-processor/index.ts, packages/query/src/block-processor/transactions.ts, packages/router/src/grpc/view-protocol-server/broadcast-transaction.ts, packages/wasm/src/transaction.ts
wasm just uses `pbt::Transaction::encode_to_vec`, which is byte-for-byte identical to bufbuild's `Transaction.toBinary`
https://github.com/penumbra-zone/penumbra/blob/4d4ae0197a1315fdb02bda6d40b044e35c838fe8/crates/wasm/src/tx.rs#L44-L52
https://github.com/penumbra-zone/penumbra//blob/1c957b5e1fc68cb2d26a63135b5392cd9357d2a9/transaction/src/transaction.rs#L306-L318
=> use Transaction.toBinary instead of wasm encodeTx

packages/router/src/grpc/view-protocol-server/index.ts, packages/router/src/grpc/view-protocol-server/witness-and-build.ts, packages/router/src/grpc/view-protocol-server/witness.ts, packages/wasm/src/build.ts
- `note_commitments` will be removed from `WitnessRequest`, so I just ignored this field 
ref: https://discord.com/channels/824484045370818580/979785365437165658/1193954469201838101
- just renamed the wasm wrapper `witness()` to `getWitness()` so as not to conflict with the rpc method
=> view service:  impl witness

apps/extension/src/state/wallets.ts, apps/webapp/src/components/dashboard/assets-table.tsx, apps/webapp/src/fetchers/address.ts, packages/types/src/account.ts, packages/ui/components/ui/address-icon.tsx, packages/ui/components/ui/address.test.tsx, packages/ui/components/ui/address.tsx, packages/ui/components/ui/copy-address-button.tsx, packages/ui/components/ui/copy-to-clipboard-icon-button.tsx, packages/ui/components/ui/copy-to-clipboard.tsx, packages/ui/components/ui/select-account.tsx, packages/ui/components/ui/tx/view/address-view.test.tsx, packages/ui/components/ui/tx/view/address-view.tsx, packages/ui/components/ui/tx/view/output.tsx, packages/ui/components/ui/tx/view/spend.tsx, packages/ui/package.json, packages/ui/tests-setup.ts, packages/ui/tsconfig.json, packages/ui/vitest.config.ts, pnpm-lock.yaml
Well, this turned out to be surprisingly annoying.
In short: the idea was to consolidate the display of addresses throughout the UIs and use the `AddressViewComponent`.
However, that didn't work in practice, since that component is designed to render [an `AddressView` object](https://github.com/penumbra-zone/penumbra/blob/main/crates/core/keys/src/address/view.rs) which, once translated into JavaScript, contains properties that need to be [corralled into human-readable values](https://github.com/penumbra-zone/web/blob/jessepinho/web-217-standardize-address-component/packages/ui/components/ui/tx/view/address-view.tsx#L16-L17). The problem is, we render addresses in places where we don't have an `AddressView` object, but rather just an address string. Further complicating matters is the …
=> Extract several shared components related to rendering addresses

apps/webapp/src/components/root-router.tsx
This allows us to ship the web app as a static site that can be hosted by anyone anywhere, without any special server config required to support URL rewriting.
- Do we want to also remove Firebase config from the `apps/webapp`, since that's specific to Penumbra Labs' own setup and consumers of this repo shouldn't have to worry about Firebase? (This would require reconfiguring our CI to apply its own config to Firebase, since `firebase.json` would be gone.) Or, are we OK with leaving it, since consumers of this repo can simply run `pnpm build` and get a statically-hostable version of the web app, which they can host wherever they want?
=> Use a hash router

apps/webapp/index.html, apps/webapp/src/components/dashboard/constants.ts, apps/webapp/src/components/dashboard/transaction-table.tsx, apps/webapp/src/components/header/block-sync.tsx, apps/webapp/src/components/header/header.tsx, apps/webapp/src/components/header/notifications.tsx, apps/webapp/src/components/send/constants.ts, apps/webapp/src/components/shared/input-token.tsx, apps/webapp/src/components/tx-details/index.tsx, apps/webapp/vite.config.ts, packages/constants/assets.ts
Pairing with @turbocrime on fixing references to various assets. This allows us to serve the Penumbra web app from a subdirectory.
To test:
1. `cd apps/webapp`
2. `pnpm build`
3. `python3 -m http.server`
4. Navigate to http://127.0.0.1:8000/dist
5. Verify that all CSS, images, etc. load as expected, even though we're serving under a `/dist` subdirectory
6. Quit the python server
7. `cd dist`
8. `python3 -m http.server`
9. Navigate to http://127.0.0.1:8000/
10. Verify that all CSS, images, etc. load as expected, now that we're serving from the root directory
=> Fix asset paths

packages/crypto/browser.config.ts
In #379, I've documented that we're getting flaky build failures due to something about the `packages/crypto/src/encryption.test.ts` test suite. 
I've tried fixing it to no avail (so far); per @hdevalence, we should just temporarily disable that test suite so that other development efforts aren't blocked. So this PR disables that test suite for now.
=> Disable flaky tests

apps/extension/src/offscreen.ts, apps/extension/src/routes/popup/approval/transaction.tsx, apps/extension/src/routes/popup/approval/tx-msg-handler.ts, apps/extension/src/state/tx-approval.ts, apps/extension/src/wasm-build-action.ts, apps/webapp/src/components/tx-details/hash-parser.tsx, packages/router/src/grpc/custody/view-transaction-plan/index.ts, packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.test.ts, packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/types/src/internal-msg/offscreen.ts, packages/types/src/jsonified.ts, packages/ui/components/ui/json-viewer/index.tsx, packages/ui/package.json, pnpm-lock.yaml
`Jsonified<AnyMessage>` becomes a black-box `JsonObject` to avoid any kind of structural inaccuracy, because protojson has rules that were not satisfied.
other types are converted more informatively.
jsonified is used in idb schema to identify contents and key types, which resolve to either `JsonObject` or primitives.
also, added type guards (and fixed some bugs) in offscreen.ts because it was a major internal user of jsonified.
use `Jsonified<T>` in your schemas/parameter/return types to convey the presence of unparsed json, and suggest what the json should deserialize to.
=> don't attempt to type message json with Jsonified

apps/webapp/src/components/dashboard/assets-table.tsx, apps/webapp/src/components/shared/input-token.tsx, apps/webapp/src/components/shared/select-token-modal.tsx, apps/webapp/src/components/swap/asset-out-box.tsx, apps/webapp/src/fetchers/balances.ts, apps/webapp/src/state/ibc.test.ts, apps/webapp/src/state/ibc.ts, apps/webapp/src/state/send.test.ts, apps/webapp/src/state/send.ts, apps/webapp/src/state/swap.test.ts, apps/webapp/src/state/swap.ts, packages/types/src/amount.test.ts, packages/types/src/amount.ts, packages/types/src/denom-metadata.test.ts, packages/types/src/denom-metadata.ts, packages/types/src/lo-hi.ts, packages/ui/components/ui/tx/view/value.test.tsx, packages/ui/components/ui/tx/view/value.tsx
This started as a change to how we render a user's balance on the Send form. @grod220 [pointed out](https://github.com/penumbra-zone/web/pull/362#discussion_r1472411058) that we should be using a `ValueViewComponent`, as that is the standard for how we render `ValueView`s throughout the app.
As I worked on this, though, I realized this change wasn't possible without also changing the form of data that we pass around in `apps/webapp/src/fetchers/balances.ts`. So I refactored the helpers in that file so that we could work with full `DenomMetadata` objects, rather than just a few properties pulled off of those objects. 
When I did this, I also realized there were a few places where we were making incorrect assumptions and calculations about how to render financial values! I'll comment on …
=> Refactor selections/balances to use `DenomMetadata`, and to render a ValueViewComponent when possible

packages/ui/components/ui/address.tsx, packages/ui/components/ui/select-account.tsx, packages/ui/components/ui/tx/view/address-view.tsx, packages/ui/components/ui/tx/view/output.tsx
Previously, the addresses in tx views were an inconsistent size with the surrounding text. This makes the address component not specify a text size, so it can fit with its surroundings.
Before:
After
Note however that there's a bug where the "to" and "from" labels are offset 2px upwards, it's quite unfortunate.
=> minor tweaks to tx views

.github/workflows/deploy-firebase-dapp.yml
Follow up from web weekly. Given the _unstable_ times we are in, moving the web app deployment to manual (syncing with extension publishes) in order to not break user experiences between testnet launches.
After this, will manually run this action on an old commit that works with our current extension. This should revive the current experience for users.
=> Move web app deploy from continuous to manual

apps/extension/src/routes/popup/approval/transaction/index.tsx
We want to put a little speed bump in place so that users don't approve transactions without reviewing them. This PR adds a countdown so that the Approve button is disabled for a few seconds.
Fixes #457
=> Use a countdown before enabling the Approve button

apps/webapp/src/state/swap.ts
Per @hdevalence 's comment in Discord, we'll just set the fee for swap claims to 0 for now, since gas prices are 0 in testnet anyway. Once we have nonzero gas prices in testnet, we'll revisit this.
=> Hardcode an estimated fee of 0 for swap claims

packages/router/src/grpc/view-protocol-server/status.test.ts
Looks like a couple imports were missing in the recent upgrade to v1
=> Fix imports from tests to use core v1

apps/extension/src/wasm-build-action.ts, apps/webapp/src/components/swap/asset-out-box.tsx, apps/webapp/src/state/helpers.ts, apps/webapp/src/state/ibc.ts, apps/webapp/src/state/send.ts, apps/webapp/src/state/swap.ts, packages/router/src/grpc/custody/view-transaction-plan/index.test.ts, packages/router/src/grpc/custody/view-transaction-plan/index.ts, packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.test.ts, packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.ts, packages/router/src/grpc/view-protocol-server/witness-and-build.ts, packages/types/src/transaction/classification.ts, packages/types/src/transaction/classify.test.ts, packages/types/src/transaction/classify.ts, packages/types/src/utility.test.ts, packages/types/src/utility.ts, packages/ui/components/ui/tx/view/action-view.tsx, packages/ui/components/ui/tx/view/output.tsx, packages/ui/components/ui/tx/view/swap-claim.tsx, packages/ui/components/ui/tx/view/swap.tsx, packages/wasm/src/utils.ts
🚨 471 line additions are just test files
🚨 Note that the "Swap into" field is not yet used. This PR is just for adding the swap claim step after a swap.
https://github.com/penumbra-zone/web/assets/1121544/22da28c4-328d-4a03-927b-e5d3d2c63d5d
- Build and submit a swap claim transaction automatically after building and submitting the swap transaction.
- Fix bug where we were trying to load proving keys in `camelCase` when we should have been loading them in `snake_case`
- Update `planWitnessBuildBroadcast` to now return the entire built transaction; extract a `getTransactionHash` helper so we can use that where needed.
- Update `classifyTransaction` to also handle `swap`/`swapClaim` transactions.
If reviewers want to manually test, here's how I tested:
1. Check out penumbra core on the …
=> Support swap claims when doing a swap

apps/webapp/package.json, apps/webapp/vite.config.ts, pnpm-lock.yaml
vite plugin provides a simple self-signed cert for localhost ssl. this is nice because
- some browser api are only available on ssl pages
- simplifies dev when restricting transport connections to ssl pages
i don't think this interferes with any CI or tests
fixes #284
=> webapp dev server ssl

packages/router/src/grpc/offscreen-client.ts, packages/types/src/internal-msg/popup.ts
Refuse to open multiple popups of the same path.
This is important for any externally-triggerable popup, such as connection request, or transaction request.
If we later do want to provide multiple simultaneous popups, we might want to add some kind of id hash.
=> Prevent popup spam

apps/extension/src/service-worker.ts, apps/extension/src/utils/rethrow-impl-errors.test.ts, apps/extension/src/utils/rethrow-impl-errors.ts
Previously, `rethrowImplErrors` was only catching errors thrown by view service methods with a `kind` of `MethodKind.Unary`. This meant that, for `MethodKind.ServerStreaming` methods, any errors thrown would get swallowed by the ConnectRPC method, and turned into a generic, unhelpful "internal error". (See [this ticket](https://github.com/penumbra-zone/web/issues/437).)
This PR fixes that by extending `rethrowImplErrors` to handle server streaming methods.
1. Update the `balances` impl to throw on its first line:
2. Reload the extension.
3. Visit the web app.
Closes #437.
=> Don't swallow errors thrown in streaming RPC methods

packages/router/src/grpc/view-protocol-server/assets.ts, packages/router/src/grpc/view-protocol-server/transaction-info.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/stream.ts, packages/transport/src/chrome-runtime/adapter.ts, packages/transport/src/create.ts, packages/transport/src/stream.ts, packages/types/src/indexed-db.ts, packages/types/src/stream.ts
~~This didn't actually solve the problem, because it turns out ConnectRPC will use await internally, and break the IDB transaction.~~
~~But, it involves more robust rethrow logic to bypass ConnectRPC's obscuring rethrow.~~
~~Removed the rethrow wrapper in service-worker.ts and just wrapped every impl with a try/catch.~~
~~May be able to address the IDB issue more fundamentally by rewriting IDB queries as streams.~~
This is is now a complete solution
rebased onto #500 which provides a better rethrow wrapper
now using a ReadableStream to iterate idb, which provides buffering and async iteration while allowing IDB to perceive its caller as remaining active, while still allowing free async behavior outside the stream
https://github.com/penumbra-zone/web/assets/134443988/2955a70a-5db6-4c84-8bf1 …
=> Keep IDB queries awake

.gitignore, apps/extension/package.json, apps/webapp/package.json, packages/wasm/.gitignore, packages/wasm/crate/.gitignore, packages/wasm/package.json, turbo.json
uses `cargo watch` for wasm dev (users must install with `cargo install cargo-watch`)
sets up turbo dependency tree to use cacheing properly
=> more turbo suggestions

packages/ui/components/ui/tx/view/output.tsx
Closes: https://github.com/penumbra-zone/web/issues/477
Before:
After:
=> Align to/from css class

packages/storage/src/indexed-db/index.ts
Discord context: https://discord.com/channels/824484045370818580/1044457038886998137/1208072520784420864
At the moment, we are saving new additions to the local assets registry to the database when the view server starts up. We'll want to overwrite even existing entries though. There are cases where a local asset is edited (say the image icon) and we want our database to pick this up.
=> Overwrite metadata on init

apps/extension/src/routes/page/onboarding/success.tsx, apps/webapp/src/components/dashboard/assets-table.tsx, apps/webapp/src/components/dashboard/constants.ts, apps/webapp/src/components/dashboard/transaction-table.tsx, apps/webapp/src/components/extension-not-installed.tsx, apps/webapp/src/components/layout.tsx, apps/webapp/src/components/metadata/content.ts, apps/webapp/src/components/send/constants.ts, apps/webapp/src/components/send/send-form/index.tsx, apps/webapp/src/components/shared/edu-panels/content.tsx, apps/webapp/src/components/shared/edu-panels/edu-info-card.tsx, apps/webapp/src/components/shared/error-boundary.tsx, apps/webapp/src/components/swap/swap-loader.tsx, apps/webapp/src/components/tx-details/index.tsx, apps/webapp/src/fetchers/is-connected.ts, apps/webapp/src/utils/extension-not-installed-error.ts, apps/webapp/src/utils/is-connected.ts, packages/ui/components/ui/logo/compressed-video.tsx, packages/ui/components/ui/splash-page.tsx, packages/ui/index.ts
Tests seem to be failing due to an issue in `main`.
Closes #520
=> Create UI for when extension is not installed

apps/webapp/src/components/send/layout.tsx, packages/tailwind-config/index.js, packages/ui/components/ui/card.tsx
I noticed that the dropdown menu on tablets was hiding behind the form on the Send page. This was due to some weird use of absolute positioning just to create a gradient background on our `Card` component. To fix this, I removed all the absolute positioning, and modified the gradient to include the semi-transparency and background color that was previously being achieved via markup.
=> Simplify the Card component to no longer need z-indexes

apps/extension/src/routes/page/index.tsx, apps/extension/src/routes/popup/home/index.tsx, apps/extension/src/routes/popup/popup-layout.tsx, packages/tailwind-config/index.js, packages/ui/components/ui/splash-page.tsx
As @turbocrime and I were pairing on a separate issue, we realized that the extension was using some messy markup with absolute-positioned elements just to show a semitransparent background image. @turbocrime figured out a way to show a semitransparent background image by layering a solid color over it at 80% opacity, so this PR implements that to simplify the markup.
This PR also refactors the "successful login" extension page to use the `<SplashPage />` component, and fixes a z-index issue there too.
Note that the Penumbra rays are shifted down a bit from before, but I assume that's OK.
=> Fix the extension background

apps/extension/src/routes/page/onboarding/import.tsx, apps/extension/src/routes/page/onboarding/set-password.tsx, apps/extension/src/routes/page/restore-password/set-password.tsx, apps/extension/src/routes/popup/login.tsx, apps/extension/src/shared/components/password-input.tsx, apps/extension/src/state/wallets.ts
🚨 When reviewing this PR, you'll prob want to use "Hide whitespace" for the indentation changes:
Per #442:
> The extension forces users to use a "strong enough" password, but it's not clear this improves security, because the key material ends up in the extension memory anyways, and something that's compromised the user's machine can probably get access to that. It also makes operating on the testnet less convenient. If there were no strength requirements, users who were comfortable with lower security could set an empty password.
This PR takes the naive approach and allows users to set an empty password, but doesn't actually change any of the underlying wiring that uses the (now-possibly-empty) password to encrypt the seed phrase. It also doesn't advertise that an empty password is …
=> Remove password strength requirements

packages/router/src/grpc/view-protocol-server/notes-for-voting.test.ts, packages/router/src/grpc/view-protocol-server/test-utils.ts
This test does not really test anything, because all the filtering logic takes place in the storage package and is covered by the tests there. 
Should we refactor to move the filtering logic to the rpc layer?
=> add tests for notes-for-voting

apps/webapp/src/components/dashboard/assets-table.tsx, apps/webapp/src/components/root-router.tsx, apps/webapp/src/components/staking/accounts/account.tsx, apps/webapp/src/components/staking/accounts/index.tsx, apps/webapp/src/components/staking/layout.tsx, apps/webapp/src/components/staking/validators-table.tsx, apps/webapp/src/fetchers/balances/by-account.ts
This is the first step of reorganizing the Validators page to focus on tokens. See the tracking issue #463 for what's coming next.
This PR just displays the user's penumbra balances for any account that holds penumbra. In the upcoming PRs, I'll add delegation and unbonding tokens to each account, but I wanted to keep these PRs bite-sized.
Closes #586
=> Show a user's unstaked tokens on the validators page

packages/constants/assets/index.ts, packages/constants/assets/local-asset-registry.json, packages/query/package.json, packages/query/src/block-processor.ts, packages/query/src/customize-symbol.test.ts, packages/query/src/customize-symbol.ts, packages/router/src/grpc/view-protocol-server/assets.ts, packages/storage/src/indexed-db/index.ts, pnpm-lock.yaml
This PR experiments with symbols for delegation tokens. Two possible approaches are illustrated:
1. The extension's asset registry can be augmented with the validator-specific token info, as I did for the two main testnet validators.
2. The extension could auto-create a symbol for the delegation token, but we must be very very careful about this, because the `symbol` field is shown to users and it is potentially attacker-controlled. For instance, if we just read the label off the chain, someone could spoof another validator's identity without consequence.
However, this seems like a good place to start.
=> Experiment with symbols for delegation tokens

apps/extension/package.json, apps/webapp/package.json, packages/crypto/package.json, packages/router/package.json, packages/types/package.json, packages/ui/package.json, packages/wasm/package.json
`vitest` defaults to watch mode when in development, but non-watch mode in CI. `vitest run` always exits after a run.
This PR switches from using `vitest run` to `vitest`, so that we automatically use watch mode in local development when running `pnpm test` inside any package directory.
=> Use 'vitest' instead of 'vitest run' to allow watching

apps/webapp/src/components/dashboard/layout.tsx, apps/webapp/src/components/send/layout.tsx, apps/webapp/src/components/swap/layout.tsx, apps/webapp/src/components/swap/swap-loader.tsx, apps/webapp/src/components/swap/unclaimed-swaps.tsx, apps/webapp/src/state/swap.ts, packages/ui/components/ui/select-account.tsx
=> Show tooltip icon no matter the toggle state

apps/extension/package.json, apps/webapp/package.json, packages/crypto/package.json, packages/router/package.json, packages/types/package.json, packages/ui/package.json, packages/wasm/package.json
Reverts penumbra-zone/web#599
`turbo.json` expects the `test` script of every package to be non-persistent and cacheable
either revert this change, or use a different name for the test-watch command, or configure `turbo.json` to work with the new test command
=> Revert "Use 'vitest' instead of 'vitest run' to allow watching"

apps/extension/src/utils/download-proving-keys.ts, package.json, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/tx.rs, pnpm-lock.yaml, turbo.json
wasm build broke when changing core dependency to 0.68
https://github.com/penumbra-zone/penumbra/issues/3894
https://github.com/penumbra-zone/penumbra/pull/3895
=> testnet v0.68

.github/workflows/compile-wasm.yml, .github/workflows/extension-publish.yml, .github/workflows/turbo-ci.yml, pnpm-lock.yaml
don't attempt any conditional CI, move all CI to buildjet. this reduces init and cache load/save times
=> simplify workflows

apps/extension/package.json, apps/extension/src/hooks/chain-id.ts, apps/extension/src/routes/popup/home/index-header.tsx, apps/extension/src/routes/popup/settings/settings-rpc.tsx, packages/polyfills/Promise.withResolvers.ts, packages/router/src/grpc/view-protocol-server/util/build-tx.ts, pnpm-lock.yaml
this now avoids clearing cache if the chainid at the new rpc endpoint remains the same
i refactored this when i expected to need to request permissions on a new endpoint after config change. that turned out to be unnecessary but i think this is better, provides some visual feedback, and prevents a long reset in some cases
=> refactor settings rpc page

packages/ui/components/ui/tx/view/value.tsx
https://github.com/penumbra-zone/web/assets/1121544/28d9d4be-84c7-4746-b40c-878c96d82f04
This isn't related to a specific ticket, but I've been wanting to redesign the Value View for a while as a pill/[chip](https://m3.material.io/components/chips/overview). Soon, we'll want to show equivalent values and other metadata on hover, and I think a pill better reflects the fact that this is a dynamic component, not just a static value. Thoughts?
=> Redesign ValueViewComponent

apps/webapp/src/components/shared/select-token-modal.tsx, apps/webapp/src/components/swap/asset-out-selector.tsx, packages/ui/components/ui/dialog.tsx
This cleans up a few issues I discovered while working on https://github.com/penumbra-zone/web/pull/620. Figured I'd make a separate PR for it for scoping reasons.
`<Dialog />`, `<DialogContent />`, and `<DialogHeader />` are now easier to use. I've added comments inline to explain the various changes.
=> Fix various issues with Dialogs

apps/webapp/src/components/staking/account/index.tsx, apps/webapp/src/components/staking/layout.tsx, apps/webapp/src/state/staking.test.ts, apps/webapp/src/state/staking.ts, packages/ui/components/ui/account-switcher.tsx, packages/ui/components/ui/select-account.tsx
Previously, you could only delegate, view validators, etc. from account #0. Now you can switch accounts.
Note that at the moment, it makes a request to the RPC node every time you switch accounts. This will no longer be the case once #601 and #612 are done.
https://github.com/penumbra-zone/web/assets/1121544/eeac65ab-2727-4f96-b584-1102b4088d4b
- Extract a new `<AccountSwitcher />` component from the `<SelectAccount />` component.
- Use it at the top of the account view.
- Put `account` state in the query string? But that could require a bit of refactoring, so I'll leave that for a future improvement.
=> Show an account switcher on the Staking page

apps/webapp/src/fetchers/staking.ts, apps/webapp/src/state/staking.test.ts, packages/query/src/block-processor.ts, packages/types/package.json, packages/types/src/customize-symbol.test.ts, packages/types/src/customize-symbol.ts, packages/types/src/index.ts, packages/ui/components/ui/tx/view/value.tsx, pnpm-lock.yaml
Previously we weren't rendering any balance for delegation tokens that the user doesn't hold any of. That's because there wasn't any metadata for those tokens, so `ValueViewComponent` rendered nothing for them.
- Fetch asset metadata based on the validator's delegation token name, and use it to render the zero balances.
- Remove `customizeSymbol` from the block processor
- Would especially like @grod220's thoughts on this. I made two changes to `customizeSymbol`: 1) I made it a pure function, returning a new copy of the `Metadata` with the symbol customized, rather than mutating the existing one; and 2) I moved it to `ValueViewComponent`, so that the customizing happens at the render stage rather than the block processing stage. This means that:
- The webapp, rather than the extension, is …
=> Include token metadata for zero-balance ValueViews of delegation tokens

packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.test.ts, packages/router/src/grpc/custody/view-transaction-plan/view-action-plan.ts, packages/types/src/transaction/perspective.ts, packages/types/src/translators/action-view.test.ts, packages/types/src/translators/action-view.ts
As part of my work on the staking page, this makes sure that the public/private views of a transaction account for delegate and undelegate actions. Without this change, those actions would be displayed in correctly when, e.g., clicking the "Public" view in the approval popup.
=> Account for delegate/undelegate actions in the public/private views of a transaction

packages/polyfills/Map.groupBy.ts
another standard api already shipped to our target platform with no ts definition
once again can't just declare, but must declare and re-export, because typescript does not support declaration merging for vars
=> declare Map.groupBy type

apps/extension/src/popup.ts, packages/client/prax.ts
apparently official chrome release does not include the ability to programmatically open the popup, despite documentation indicating that this functionality is present
https://developer.chrome.com/docs/extensions/reference/api/action#method-openPopup
=> fix connection

apps/extension/src/utils/download-proving-keys.ts, apps/extension/src/wasm-build-action.ts, packages/types/src/proving-keys.ts, packages/types/src/utility.ts, packages/wasm/crate/src/keys.rs, packages/wasm/crate/tests/build.rs, packages/wasm/src/utils.ts
While working on another branch, I recalled @hdevalence 's comment that we could store proving keys as a map of each action type to the proving key required for that action. Accessing them from an array was a bit cumbersome, so I converted them to an object to make it explicit which key is needed for which action.
This PR also removes the nullifier derivation proving key, which [Henry said](https://discord.com/channels/824484045370818580/883455571003576320/1214670615622066206) is not actually needed on web.
=> Small refactor to how proving keys are stored and accesssed

apps/webapp/src/components/staking/account/delegation-value-view/staking-actions/form-dialog.tsx, apps/webapp/src/components/staking/account/delegation-value-view/staking-actions/index.tsx
Previously, _all_ form dialogs were opening when _any_ validator was clicked on, so the incorrect validator info would show up in the dialog. This fixes that by making sure that the validator in state (i.e., the one the user clicked on ) matches the validator for the given `<FormDialog />`.
=> Hotfix: only open the form dialog for the selected validator info

packages/router/src/grpc/view-protocol-server/transaction-planner.test.ts
The simplification of wasm transaction planner https://github.com/penumbra-zone/web/issues/609 is already finished, so it no longer makes sense for us to hold off on these tests
=> add tests for transaction-planner

apps/minifront/src/components/staking/account/header/index.tsx, apps/minifront/src/state/staking.test.ts, apps/minifront/src/state/staking.ts, packages/ui/components/ui/account-switcher.test.tsx, packages/ui/components/ui/account-switcher.tsx
https://github.com/penumbra-zone/web/assets/1121544/bbf8799d-eee7-432e-98a6-29121309775c
Currently, the account switcher allows users to switch between any of their accounts, between 0 and 2^32. 
In some contexts, though, we want to restrict which accounts the user should be able to switch between. For example, on the staking page, we only want to allow the user to switch between accounts that have unstaked UM tokens, delegation tokens, and/or unbonding tokens. (Otherwise, there's no staking-related action the user could take on that account.)
This PR adds a `filter` prop to `<AccountSwitcher />` to make that functionality possible, then uses that prop in the staking page.
=> Filter the `<AccountSwitcher />` on the staking page to only allow switching between relevant accounts

apps/extension/.env, packages/types/src/customize-symbol.test.ts, packages/types/src/customize-symbol.ts
Previous symbols were a bit large and cumbersome in the UI. Per @hdevalence , we're OK to just use the first 8 characters of a validator identity key.
Closes #653
=> Shorten symbols for delegation/unbonding tokens

apps/extension/.env, apps/extension/src/impls.ts, packages/query/src/block-processor.ts, packages/router/src/grpc/sct/epoch-by-height.test.ts, packages/router/src/grpc/sct/epoch-by-height.ts, packages/router/src/grpc/sct/index.ts, packages/router/src/grpc/test-utils.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test-data.ts, packages/storage/src/indexed-db/indexed-db.test.ts, packages/types/src/indexed-db.ts
This started as a PR to address #601 (serving validator info from the extension), but I quickly realized I'd need to store epochs in IndexedDB first. So this PR takes care of that.
- Create a new `EPOCHS` table in IndexedDB.
- Since we're storing epochs locally anyway, I also created an `SctService` impl in the extension. (It only has one method, `GetEpochByHeight`.)
=> Store `Epoch`s in IndexedDB and serve from extension

packages/router/src/grpc/view-protocol-server/status.test.ts, packages/router/src/grpc/view-protocol-server/status.ts
=> Fix logic for whether we're currently catching up

scripts/create-validators.sh, scripts/delegate-to-validators.sh
I create these to make it easier for myself to test staking-related functionality on my local devnet, by spinning up hundreds of validators and delegating to them in bulk.
Not sure these should actually exist in the web repo, or anywhere at all other than for my personal use. The delegation script specifically doesn't even work super well. But I didn't want to lose track of these. Thoughts? Should these be in core?
=> Create scripts for creating and delegating to validators

apps/extension/src/routes/popup/approval/origin.tsx, package.json, pnpm-lock.yaml
looks like this was accidentally removed - not sure why there were so many changes in that deps upgrade PR
this style is useful because it visually indicates a line-break in the URL display field, which is necessary in order for the user to verify the origin
with the url `https://thisurlistryingtotrickyou-oooooooooooooooooooooooooooooooooooooooooooooooooooo-app.testnet.penumbra.zone-oooooooooooooooooooooooooooooooooooooooooooooooooooo-bymakingtheboxdisplaystrangely.verylongurl.ml:1234/`
without the style:
with the style:
edit: and a 'legit' dialog for comparison
=> restore overflow attention style

apps/extension/package.json, apps/extension/public/manifest.json, apps/extension/src/hooks/onboarding.ts, apps/extension/src/routes/popup/home/index.tsx, apps/extension/src/routes/popup/login.tsx, apps/extension/src/routes/popup/popup-needs.ts, apps/extension/src/routes/popup/router.tsx, apps/extension/src/service-worker.ts, packages/router/src/grpc/view-protocol-server/app-parameters.test.ts, packages/router/src/grpc/view-protocol-server/app-parameters.ts, packages/services/package.json, packages/services/src/index.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/services.ts, pnpm-lock.yaml
=> attempt to start, redirect to onboarding

apps/extension/src/popup.ts, apps/extension/src/state/tx-approval.ts, apps/minifront/src/state/helpers.ts, packages/router/src/grpc/custody/authorize.ts, packages/ui/lib/toast/transaction-toast.test.tsx, packages/ui/lib/toast/transaction-toast.tsx
https://github.com/penumbra-zone/web/assets/1121544/de6001fa-0d69-43bc-9619-f3d3566efe12
There were a number of issues with how we were handling errors coming from the extension. This PR fixes the following:
1. Show a nicer message when the user is not logged into the extension (closes #349).
2. Show a nicer message when the user closes the approval popup without approving or denying (closes #519).
3. Show a nicer message when the user denies authorization (re-fixes #517, which recently had a regression)
=> Fix how we handle various errors from the extension

apps/extension/src/popup.ts, apps/extension/src/state/tx-approval.ts, apps/minifront/src/state/helpers.ts, apps/minifront/src/state/ibc.ts, apps/minifront/src/state/send.ts, apps/minifront/src/state/staking/index.ts, apps/minifront/src/state/swap.ts, packages/router/src/grpc/custody/authorize.ts, packages/ui/lib/toast/transaction-toast.test.tsx, packages/ui/lib/toast/transaction-toast.tsx
`planBuildBroadcast` is back! 😆  
We've refactored our Zustand actions a number of times and we're back to the point where there's a ton of shared code between them. I extracted the bits that are general to pretty much any transaction: managing toasts, planning then building then broadcasting, etc. The rest gets passed in.
I manually tested:
And they all worked :)
Closes #717
=> Extract common transaction tasks to a planBuildBroadcast helper

apps/minifront/src/components/extension-unavailable.tsx, apps/minifront/src/components/not-found.tsx, apps/minifront/src/components/shared/error-boundary.tsx, apps/minifront/src/fetchers/chain-id.ts, apps/node-status/src/components/error-boundary.tsx
Previously, when the RPC node was unavailable, the `<ErrorBoundary />` component would catch the error, stringify it, and render it to the screen.
Now, we detect whether the given error is specific to the RPC being unavailable, and we show a message for that case.
I also prettified the `<ErrorBoundary />` in both the minifront and node-status apps to show other types of errors inside a `<SplashPage />` — e.g.:
And lastly, I created a 404 page:
Closes #571 
Closes #339
=> Show a nicer UI when minifront can't connect to the extension, and for other errors

apps/extension/src/utils/rethrow-impl-errors.ts, packages/types/src/base64.test.ts
instead of weirdly reaching into the cjs build of connectrpc we can just declare an equivalent type.
this change has zero behavioral effect but helps with packaging
=> better type in rethrow wrapper

apps/minifront/src/components/dashboard/assets-table.tsx, packages/ui/components/ui/address-component.test.tsx, packages/ui/components/ui/address-component.tsx, packages/ui/components/ui/card.tsx, packages/ui/components/ui/select-account.tsx, packages/ui/components/ui/tx/view/action-details.tsx, packages/ui/components/ui/tx/view/address-view.tsx, packages/ui/components/ui/tx/view/delegate.tsx, packages/ui/components/ui/tx/view/swap.tsx, packages/ui/components/ui/tx/view/undelegate.tsx, packages/ui/components/ui/tx/view/viewbox.tsx
A lot of our action details look a bit ugly. I created `<ActionDetails />` in a previous PR to address this, but I'd only used it for a single action type. This PR uses it in more places.
This doesn't resolve all our issues with how we display swaps + swap claims (more detail in #424), but it's a start.
Comments to explain my choices are inline.
Relates to #424
=> Prettify action details in several action views

apps/minifront/package.json, apps/minifront/src/components/staking/account/delegations.tsx, pnpm-lock.yaml
Well, that was easy.
https://github.com/penumbra-zone/web/assets/1121544/fb21c0b5-5edc-4192-9f99-7736c669a845
(Note that I had to install `framer-motion` inside `minifront`. This shouldn't actually add to the bundle size, though, since it's also installed in `packages/ui`, which is used by `minifront`. That said, we could probably save a bit of bundle size by not using framer-motion at all and rolling our own animations, or using the [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API).)
=> Animate validators as they render

apps/minifront/src/components/swap/swap-loader.tsx, apps/minifront/src/state/ibc.ts, apps/minifront/src/state/staking/index.ts, packages/constants/src/assets.test.ts, packages/constants/src/assets.ts, packages/getters/src/metadata.ts, packages/router/src/grpc/view-protocol-server/assets.ts, packages/router/src/grpc/view-protocol-server/delegations-by-address-index.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/customize-symbol.ts, packages/types/src/staking.ts
A proposal for new class that assists in typing so we don't have to do the `groups as unknown as GroupType` pattern.
=> New asset pattern helper

packages/types/src/validation.test.ts, packages/types/src/validation.ts
Given we do this on each block save and block sync is performance critical, we should only validate in dev mode. I don't notice a difference (at least on my machine), but still best to do. 
See discord for context: https://discord.com/channels/824484045370818580/1044457038886998137/1220036483612807298
=> Validate zod only in dev

apps/extension/src/approve-transaction.ts, apps/extension/src/message/popup.ts, apps/extension/src/state/tx-approval.ts, packages/perspective/plan/index.test.ts, packages/perspective/plan/index.ts, packages/perspective/plan/view-action-plan.test.ts, packages/perspective/plan/view-action-plan.ts, packages/router/src/ctx/approver.ts, packages/router/src/grpc/custody/authorize.test.ts, packages/router/src/grpc/custody/authorize.ts
pulled out of work refactoring custody/authorize.
tx view generation tools are now in their own package. we use these tools in the tx approval slice now, and query the view rpc for metadata when necessary, instead of serializing all metadata and posting it with the request message. the slice accesses the fvk directly, meaning the custody rpc no longer requires fvk at all.
=> generate tx view in slice

apps/extension/src/entry/popup-root.tsx, apps/extension/src/message/popup.ts, apps/extension/src/state/tx-approval.ts
Since https://github.com/penumbra-zone/web/pull/804 'transactionView' no longer in req.request
=> Update tx popup route guard

apps/minifront/src/components/header/navbar.tsx
Closes https://github.com/penumbra-zone/web/issues/810
Making the padding not conditional prevents them from resizing if active
=> Prevent jumping headers

apps/minifront/src/components/swap/asset-out-box.tsx, apps/minifront/src/components/swap/asset-out-selector.tsx, apps/minifront/src/components/swap/swap-form.tsx, apps/minifront/src/state/ibc.ts, apps/minifront/src/state/send.ts, apps/minifront/src/state/swap.test.ts, apps/minifront/src/state/swap.ts, packages/getters/src/value.ts, packages/getters/vite.config.ts, packages/types/src/amount.test.ts, packages/types/src/amount.ts
Closes https://github.com/penumbra-zone/web/issues/735 <--- turns out this isn't a slippage thing, but a price impact one
Closes https://github.com/penumbra-zone/web/issues/829
When a user makes a swap, the size of their trade could impact the price of the asset in the market. This `price impact` percentage is something we want to display to the user when they are estimating the swap they are about to take. This is especially important in low-liquidity pools where users may not want to take that kind of hit.
Zero price impact:
Price impact present:
Price impact worse than 10%
=> Add price impact to swap estimate

packages/ui/components/ui/account-switcher.tsx
1. Makes the hover color more visible (especially helpful in the extension, the web app has a higher contrast background anyway)
2. Increase width when right/left arrow are clicked so the number doesn't get cut off
Think this perhaps relates to some changes to this earlier in the month @jessepinho
Before:
https://github.com/penumbra-zone/web/assets/16624263/fbeb23dd-802e-47b8-b7b6-8f0e7f09ded8
After:
https://github.com/penumbra-zone/web/assets/16624263/3d54a982-ea9d-4f54-a307-71cdce5ffe76
=> Fix account switcher bug

packages/wasm/crate/src/keys.rs, packages/wasm/src/address.ts
Follow up from: https://github.com/penumbra-zone/web/pull/821/files#r1538165300
A small PR to improve the naming of the wasm function getting index from an address.
=> Clarify wasm func naming

packages/query/src/queriers/tendermint.ts
This should almost never happen. Basically, this should only happen when the user opens the web app in one epoch, then the epoch changes, then the user tries to delegate to a validator. In that case, we should at least show the error to the user rather than hanging indefinitely on "waiting for confirmation."
=> Account for error where delegation was prepared for different epoch

.changeset/red-geese-care.md, apps/extension/.env, apps/extension/src/state/tx-approval.ts, apps/extension/src/utils/download-proving-keys.ts, apps/minifront/src/state/staking/assemble-undelegate-claim-request.ts, package.json, packages/constants/src/assets.test.ts, packages/constants/src/assets.ts, packages/getters/src/metadata.test.ts, packages/getters/src/metadata.ts, packages/getters/src/undelegate-claim.ts, packages/getters/src/value-view.ts, packages/query/src/block-processor.ts, packages/router/src/grpc/view-protocol-server/asset-metadata-by-id.test.ts, packages/router/src/grpc/view-protocol-server/helpers.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/customize-symbol.test.ts, packages/types/src/customize-symbol.ts, packages/types/src/indexed-db.ts, packages/ui/components/ui/tx/view/undelegate-claim.tsx, packages/ui/components/ui/tx/view/undelegate.tsx, packages/ui/components/ui/tx/view/value/index.tsx, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/planner.rs, packages/wasm/crate/src/storage.rs, packages/wasm/crate/tests/build.rs, pnpm-lock.yaml
- Update Cargo and NPM dependencies on core packages.
- Fix various places where we were previously using epochs, but are now using block heights.
- This includes unbonding tokens. Unbonding tokens used to be named like `uunbonding_epoch_N_penumbravalid1abc123`. Now, unbonding tokens refer to a start _block height_, rather than a start _epoch_, so they're of the form `unbonding_start_at_N_penumbravalidabc123`. Also, they now have multiple denom units, so the display denom just starts with `unbonding_` rather than `uunbonding`.
- Fix a bug with how we stored epochs.
- Previously, we stored new epochs only at epoch transitions. However, this meant that the first epoch (index 0) was missing! So, I updated the block processor to create an initial epoch if we're starting sync at block height …
=> Update core dependencies to v0.70.3

apps/extension/.env, packages/query/src/block-processor.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test-data.ts, packages/storage/src/indexed-db/indexed-db.test.ts
This fixes a bug we had before where, for some reason (probably related to exponential back-off), the start epoch with index 0 was being saved multiple times. This threw off the count for epochs, making delegate actions fail (since they use epoch indexes). To fix this, we create epoch 0 outside of the syncAndStore method, at DB initialization.
Closes #865
=> Check for an existing start epoch before creating one

apps/minifront/src/components/staking/account/header/constants.ts, apps/minifront/src/components/staking/account/header/index.tsx, apps/minifront/src/components/staking/account/header/unbonding-tokens.tsx, apps/minifront/src/components/staking/layout.tsx, apps/minifront/src/state/staking/index.test.ts, apps/minifront/src/state/staking/index.ts, packages/getters/src/unbonding-tokens-by-address-index-response.ts
We've been showing a user's unbonding tokens in a single group. When they click the `Claim` button, we create a single transaction with undelegate claims for every unbonding token that user holds. This means that the entire transaction (and all its undelegate claims) will fail if _any_ undelegate claim fails, since they're all batched into the same transaction.
With this PR, we use the new `ViewService#unbondingTokensByAddressIndex` endpoint to determine which unbonding tokens are claimable and which are not yet claimable. We only show the `Claim` button for claimable tokens, and we show the claimable and not-yet-claimable tokens separately.
- Use the new `ViewService#unbondingTokensByAddressIndex` to load unbonding tokens into state.
- Fix a bug where some accounts were incorrectly …
=> Split out claimable vs. not-yet-claimable unbonding tokens in the UI

packages/perspective/translators/action-view.test.ts, packages/perspective/translators/action-view.ts, packages/ui/components/ui/tx/view/action-view.tsx, packages/ui/components/ui/tx/view/swap-claim.tsx, packages/ui/components/ui/tx/view/swap/index.tsx, packages/ui/components/ui/tx/view/unimplemented-view.tsx
Closes https://github.com/penumbra-zone/web/issues/642
At the moment, unimplemented views are seen as incognito. This is a mistaken default. This creates a view that communicates to the user that we haven't got to creating a view for it.
Up next, will create an issue to audit our action views (especially the opaque ones).
=> Make unimplemented views clear

packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts
The indexed-db version increase test was not correct. 
In fact, instead of increasing the version of the existing db, we created a new db with a different random name
=> Fix id increasing version test

packages/query/src/block-processor.ts
Closes https://github.com/penumbra-zone/web/issues/878
https://github.com/penumbra-zone/web/assets/16624263/c0596976-bc1f-45f9-8bc6-a84e7aaec7fa
=> Add console checks for sct divergence

apps/extension/src/hooks/full-sync-height.ts, apps/extension/src/routes/popup/home/index.tsx, apps/extension/src/routes/popup/settings/settings-clear-cache.tsx, apps/extension/src/state/network.test.ts, apps/extension/src/state/network.ts, packages/storage/src/chrome/local.ts, packages/storage/src/chrome/types.ts, packages/ui/components/ui/block-sync-status/large.tsx, packages/ui/components/ui/progress.tsx
Closes https://github.com/penumbra-zone/web/issues/824
Does two main things:
- On cache clearing, waits for db to clear before transitioning back to index. Sometimes takes a bit, so added a loading state for the button.
- Added genesis and normal loading states for block sync bar. Gives users an indication something is happening. At the moment, it simply doesn't render when its in the loading state.
https://github.com/penumbra-zone/web/assets/16624263/ef6dbfb7-bf07-4a80-a147-c83e7a77eed0
=> Clear cache fix & added sync states

apps/extension/src/routes/popup/padding-wrapper.tsx, apps/extension/src/routes/popup/settings/settings-advanced.tsx, apps/extension/src/routes/popup/settings/settings-auto-lock.tsx, apps/extension/src/routes/popup/settings/settings-clear-cache.tsx, apps/extension/src/routes/popup/settings/settings-connected-sites.tsx, apps/extension/src/routes/popup/settings/settings-full-viewing-key.tsx, apps/extension/src/routes/popup/settings/settings-passphrase.tsx, apps/extension/src/routes/popup/settings/settings-rpc.tsx, apps/extension/src/routes/popup/settings/settings-screen/index.tsx, apps/extension/src/routes/popup/settings/settings-screen/settings-header.tsx, apps/extension/src/routes/popup/settings/settings-security.tsx, apps/extension/src/routes/popup/settings/settings-spend-key.tsx, apps/extension/src/routes/popup/settings/settings.tsx
🚨 I'd recommend viewing this PR with the "Hide whitespace" setting turned on.
In #877, I created a `<PaddingWrapper />` component for use throughout the various settings screens. But then I realized that all the settings screens had a lot more in common than just the padding, so in this PR I deleted `<PaddingWrapper />` and extracted a `<SettingsScreen />` component to take care of the common elements of settings screens (header, back button, padding, icon, etc.).
The only visual difference in this PR is that "Lock wallet" is now listed along with other menu options, rather than being pushed all the way to the bottom:
=> DRY up extension settings code; extract a `<SettingsScreen />` component for all settings screens in the extension

apps/minifront/src/components/dashboard/assets-table/equivalent-values.tsx, apps/minifront/src/components/dashboard/assets-table/index.tsx, packages/ui/components/ui/tx/view/value/index.tsx
Pretty straightforward. I also added a tooltip for equivalent values to make it clear what they represent:
=> Show equivalent values in the assets table

.github/ISSUE_TEMPLATE/deployment.md, docs/deployment.md
Previously, the deployment docs pointed to a link that had the issue template embedded in the query string, which made it hard to update. This PR extracts that template to an issue template markdown file, and updates the link. Note that this can only really be tested once it's merged, since the link in the deployment docs points to a template that won't exist until this is merged.
=> Create issue template for deployments

apps/minifront/src/components/dashboard/assets-table/equivalent-values.tsx, apps/minifront/src/components/dashboard/assets-table/index.tsx, packages/ui/components/ui/table.tsx, packages/ui/components/ui/tx/view/value/index.tsx
🚨 I'd recommend reviewing this [with the "hide whitespace" feature turned on](https://github.com/penumbra-zone/web/pull/897/files?diff=split&w=1).
In response to @grod220 's [comment](https://github.com/penumbra-zone/web/pull/886#pullrequestreview-1981798384), I did a quick spike on rendering the assets table using an actual `<table>`:
Here's how it'd look with multiple equivalent values:
=> Render the assets table as an actual table

docs/deployment.md
Annoyingly, GitHub doesn't automatically pull the title from the template, so we have to include the title in the query string.
Also,the `template` query param should contain the entire template filename, apparently — including the extension.
=> Fix deployment issue link

apps/extension/.env, apps/extension/src/state/tx-approval.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/error.rs, packages/wasm/crate/src/lib.rs, packages/wasm/crate/src/metadata.rs, packages/wasm/crate/src/planner.rs, packages/wasm/crate/src/storage.rs, packages/wasm/crate/tests/build.rs
When a user undelegates from a validator — meaning, they want to unbond their delegation tokens so that they can reclaim those tokens as UM — Penumbra issues "unbonding" tokens. These unbonding tokens are tied to the specific validator that the user is undelegating from, as well as to the block height at which the user made the undelegate transaction. (It just so happens that Penumbra's current implementation clamps the block height to the start of the current epoch; but this could change in the future, so we treat it as though it's tied to a block height, rather than tied to an epoch.)
Because unbonding tokens are so specific, there often is no metadata for them in the database when a user wishes to undelegate from a validator. (The only way there _would_ be metadata for them in the …
=> Generate unbonding token metadata on the fly for the approval dialog

apps/minifront/src/components/dashboard/assets-table/index.tsx, apps/minifront/src/components/layout.tsx
See inline code comments.
Note the horizontal scrollbar at the bottom.
Closes #899
=> Get rid of horizontal scrollbar on dashboard page

apps/extension/.env, packages/query/src/block-processor.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts
=> fix epoch saving

apps/extension/src/service-worker.ts, packages/constants/src/assets.ts, packages/query/src/block-processor.ts, packages/query/src/price-indexer.test.ts, packages/query/src/price-indexer.ts, packages/router/src/grpc/view-protocol-server/balances.test.ts, packages/router/src/grpc/view-protocol-server/balances.ts, packages/services/src/index.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts, packages/types/src/indexed-db.ts
This PR contains some improvements on asset pricing 
- added support for multiple NUMERAIRES, allowing customers to determine for themselves which price estimate to use for display 
- added price relevance threshold depending on asset type. Crypto assets are very volatile and we can't use too old prices to display estimated values 
Close #794
=> 794 improve pricing method

packages/ui/components/ui/tx/view/action-details.tsx, packages/ui/components/ui/tx/view/memo-view.tsx, packages/ui/components/ui/tx/view/viewbox.tsx
Uses the rows component to render the entire memo as one object (since it is one object). Also fixes formatting for empty memos.
As a side effect to doing this, I added configuration to mark individual rows as visible or not. I originally used this to make a version of the "opaque" memo that showed that individual fields were opaque, and then concluded that it wasn't a good design.
However, I left them in the code since they'll be useful for making rendered views of actions that can show that some fields are present while others are opaque.
=> Improve memo rendering with rows

apps/minifront/src/components/dashboard/assets-table/index.tsx, packages/ui/components/ui/tx/view/value/index.tsx
At the moment, amounts in the value view are not really lined up with the token symbol. The amount is too "high" comparatively. 
This PR drops it by a few pixels so they share the same baseline
=> Align symbol with amount

apps/extension/.env, apps/extension/src/utils/tests-setup.js, packages/router/tests-setup.js, packages/storage/src/chrome/test-utils/tests-setup.js
We are currently defaulting to approving `app.testnet.penumbra.zone` as a connected site when the user first installs Prax.
However, the extension wasn't recognizing it as a pre-approved site because of the trailing slash in `MINIFRONT_URL`. Thus, you'd still have to click the "Connect" button when visiting minifront at that origin.
This PR fixes that. Lotttts of digging for a 4-line change 😆 
Closes #866
=> Remove trailing slash from MINIFRONT_URL

apps/minifront/src/components/header/top-row.tsx, apps/minifront/src/components/layout.tsx
Per #921, the entire minifront layout is blank while syncing genesis state. Since genesis state is large and may take a long time to sync, the user experience while syncing genesis state is pretty poor.
Fortunately, the fix was easy. It turns out that the root layout loader was querying for the chain ID. Since the chain ID query wouldn't respond until the extension was done syncing genesis state, the query was blocking the layout component from rendering. So I moved the chain ID query to the header (which is where it's used), so that the chain ID no longer blocks the layout.
(I wonder if we should stop putting queries into our loaders, as the loaders block their routes from rendering until loading is complete — which creates UX problems like this.)
I added a 1,000-second timeout to the …
=> Fix: Syncing genesis state causes unresponsive minifront

apps/minifront/src/components/dashboard/transaction-table.tsx, apps/minifront/src/components/root-router.tsx, apps/minifront/src/state/index.ts, apps/minifront/src/state/transactions.ts
https://github.com/penumbra-zone/web/assets/1121544/3b7d8252-a23d-4418-a931-6458b578fc0c
Reviewers, what do you think of this?
@Valentine1898 pointed out in #911 that there's a delay when switching to the transactions table if you have a lot of transactions. So in this PR, I switched it to stream results, so that it's more responsive.
This results in a similar issue to what we were dealing with on the staking page, though: the page might actually take longer to load all the data, even though it _feels_ faster, because of rendering costs.
That said, I generated nearly 200 transactions and then loaded the page, and it finished loading in under a second. So I think we're OK.
Closes #911
=> Stream transactions in transactions table to avoid blocking loading

apps/extension/src/routes/popup/approval/approve-deny.tsx, apps/extension/src/routes/popup/approval/origin.tsx, packages/ui/.storybook/main.js, packages/ui/components/ui/button.stories.tsx, packages/ui/components/ui/button.tsx
- Add a `destructiveSecondary` variant to the `<Button />` component.
- Create a Storybook story for the `<Button />` component.
- Use the new variant in `<ApproveDeny />`, and simplify that component to always use the same design.
Closes #711
=> Use accessible design for approve/deny buttons

.github/ISSUE_TEMPLATE/deployment.md, scripts/build-for-deployment.sh, scripts/zip-frontends.sh
This PR creates a script to build and ZIP the dist directories of minifront and node-status, so as to prevent human error and ease the deployment process.
Closes #857
=> Create a script to zip minifront/node-status dist directories for deploying to core

apps/extension/src/routes/popup/approval/approve-deny.tsx, apps/extension/src/routes/popup/approval/origin.tsx, apps/extension/src/routes/popup/approval/transaction/index.tsx, apps/extension/src/routes/popup/popup-layout.tsx, packages/ui/styles/globals.css
Explanation for changes are inline. In short:
- I made the popup root div have a _min_ width/height instead of a hard-coded width/height, thus allowing it to scale with the popup window size.
- I fixed the issue where the scrollbars were hidden behind the fixed-position approve/deny buttons, by removing the fixed positioning and using flexbox instead.
- You may notice in the screencap that there is still some strange scrolling behavior when you shrink the window _below_ 400px wide or 600px tall. That's due to the min widths that we apparently need for the attached window height. I believe that, to work around this, we'd need to make a separate root for detached vs. attached popup windows. We could do that, but I'd suggest we make that a separate PR (if reviewers even think it's …
=> Fix layout and resizing issues in the extension popup

packages/ui/components/ui/toaster.tsx
Instead of using Sonner's default UI, which hides old toasts behind new ones, this PR expands all toasts by default. That way, when doing a swap + swap claim, you can clearly see both notifications:
I actually think this is a better UI choice anyway. There isn't really a compelling need to hide old toasts behind new ones.
Closes #830
=> Expand toasts by default

apps/extension/src/entry/offscreen-handler.ts, packages/services/src/offscreen-client.ts
offscreen is rejecting a promise somewhere, but there is no mechanism to capture the failure
=> capture unhandled promise rejections in offscreen

apps/extension/src/service-worker.ts, packages/services/src/ctx/full-viewing-key.ts, packages/services/src/custody-service/authorize/index.test.ts, packages/services/src/custody-service/authorize/index.ts, packages/services/src/view-service/address-by-index.test.ts, packages/services/src/view-service/address-by-index.ts, packages/services/src/view-service/authorize-and-build.ts, packages/services/src/view-service/balances.test.ts, packages/services/src/view-service/ephemeral-address.test.ts, packages/services/src/view-service/ephemeral-address.ts, packages/services/src/view-service/index-by-address.test.ts, packages/services/src/view-service/index-by-address.ts, packages/services/src/view-service/transaction-info-by-hash.test.ts, packages/services/src/view-service/transaction-info-by-hash.ts, packages/services/src/view-service/transaction-info.test.ts, packages/services/src/view-service/transaction-info.ts, packages/services/src/view-service/transaction-planner/index.test.ts, packages/services/src/view-service/transaction-planner/index.ts, packages/services/src/view-service/witness-and-build.ts, packages/types/src/servers.ts
> currently, method impls that need fvk do something like this
> 
> ```
>   const { fullViewingKey } = (await services.getWalletServices()).viewServer;
> ```
> 
> we should just have a context key that provides fvk to impls, and fvk should not be available from another location.
> 
> relevant to #341
Close #826
=> context key for full viewing key

apps/extension/package.json, apps/minifront/package.json, apps/node-status/package.json, package.json, packages/bech32/package.json, packages/client/package.json, packages/constants/package.json, packages/crypto/package.json, packages/eslint-config-custom/package.json, packages/getters/package.json, packages/keys/package.json, packages/perspective/package.json, packages/polyfills/package.json, packages/query/package.json, packages/services-context/package.json, packages/services/package.json, packages/storage/package.json, packages/tailwind-config/package.json, packages/transport-chrome/package.json, packages/transport-dom/package.json, packages/tsconfig/package.json, packages/types/package.json, packages/ui/package.json, packages/wasm/package.json
i expected publishing to integrate the workspace root license key and license files due to documentation at https://pnpm.io/cli/publish however this seems to not be the case
=> add license key to every `package.json`

package.json, packages/wasm/package.json
correcting the clean script in wasm pkg to maintain the `.npmignore` file which should not be deleted
moved the existing `cargo clean` part to its own script `clean:rust` which must be called more deliberately. i think this is better because `cargo clean` is a bit more destructive than our other clean scripts, as it removes things like downloaded dependencies and dependency build outputs - so avoiding a `cargo clean` greatly accelerates recompile.
and now that clean doesn't force a full recompile, i also added clean to all-check which is nice for wiping those annoying mjs temp files
=> wasm clean script, all-check clean

packages/ui/components/ui/account-switcher.test.tsx, packages/ui/components/ui/account-switcher.tsx
From #966:
> Toggling between account 0 and 1 makes the title hop a bit left and right. Likely due to arrow not being there for padding.
>
> https://github.com/penumbra-zone/web/assets/16624263/54cc3019-2186-47b1-b0f4-9fc281629607
Now, the next/previous buttons are always showing, but are disabled if we're on the last/first account, respectively:
Closes #966
=> Fix issue with shifting account header

packages/ui/components/ui/tx/view/address-view.tsx
Looks like #885 was mostly outdated, but I at least fixed this issue.
Closes #885
=> Don't break account label

.gitignore, package.json, packages/wasm/package.json, turbo.json
jesse complained about dev startup slowing down so changing dep from build to compile should accelerate it.
i believe the build issues (package exports) present in https://github.com/penumbra-zone/web/commit/4ef2ef7c3874b9bc85a632455cf6456af46f208d that prompted this change are by #995, so there should be no negative effects of this, but watch out for broken HMR or other issues
=> faster dev init, fix wasm clean

packages/ui/components/ui/tx/view/value-with-address.tsx
Closes https://github.com/penumbra-zone/web/issues/902
Given the addresses is already resizable with the truncate class, this just makes the pill in this view not-resizable.
Before:
After:
=> No shrink pill

packages/getters/vite.config.ts
It looks like the getters defined for `BatchSwapOutputData` are exported but never exposed in `vite.config.ts` for downstream users to access. This PR is a one line change to `vite.config.ts` that changes that.
=> Expose `batch-swap-output-data` getters to package consumers

packages/query/src/block-processor.ts, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/auction.rs, packages/wasm/crate/src/dex.rs, packages/wasm/crate/src/lib.rs, packages/wasm/crate/src/metadata.rs, packages/wasm/crate/src/planner.rs, packages/wasm/crate/src/tx.rs, packages/wasm/crate/tests/build.rs, packages/wasm/src/auction.ts
As part of #942, I've made a massive branch with a ton of changes to the Dutch auction UI. To make the review process more manageable, I'm breaking the changes into smaller atomic PRs.
This PR modifies the block processor to identify Dutch auctions, and save their NFTs' metadata to the database when it encounters them. Future PRs will build on top of this.
=> Process Dutch auction NFT metadata in the block processor

.changeset/five-baboons-itch.md, packages/transport-dom/package.json, packages/transport-dom/tsconfig.json, packages/transport-dom/vite.config.ts
- correct `publishConfig` paths
- correct location of `files` field
- `tsconfig.json` excludes build output
- `prepack` script runs build
- `prebuild` script runs clean
- `clean` script removes pack outputs
- vite build reconfigured
- `vite-plugin-externalize-deps` to actually use dependencies
- except for `@penumbra-zone/polyfills` which is configured to inline
=> fix transport-dom package

.github/workflows/compile-wasm.yml
currently, 'Compile WASM' is run simultaneously three times on `main` pushes
(Packages Release and Turbo CI are both running a 'Compile WASM' step)
this PR removes the `main` push trigger. at one point it was necessary, but that is no longer the case.
should also investigate running the publish workflow *after* the 'Turbo CI' workflow, after tests have run, and when it can use the cached builds.
=> remove superfluous compile workflow trigger

packages/wasm/crate/src/tx.rs
(Note that the input metadata was present because the TXP had been filled with that metadata when processing the "Spend" action. However, we don't want to rely on that.)
- Add the same handling for `*Withdraw`/`*End` actions. Punting for now since that flow isn't yet supported on web.
=> Insert missing asset IDs for ActionDutchAuctionSchedule

apps/extension/.env.testnet, apps/minifront/src/components/swap/dutch-auction/auctions.tsx, apps/minifront/src/components/swap/dutch-auction/dutch-auction-loader.ts, apps/minifront/src/components/swap/dutch-auction/index.tsx, apps/minifront/src/state/dutch-auction/index.ts, packages/bech32m/src/format/convert.ts, packages/protobuf/src/registry.ts, packages/query/src/block-processor.ts, packages/services/src/test-utils.ts, packages/services/src/view-service/auctions.test.ts, packages/services/src/view-service/auctions.ts, packages/services/src/view-service/index.ts, packages/storage/src/chrome/test-utils/tests-setup.js, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts, packages/types/src/indexed-db.ts, packages/ui/components/ui/dutch-auction-component.tsx, packages/ui/components/ui/tx/view/action-dutch-auction-schedule-view.tsx, packages/wasm/crate/tests/build.rs
This PR does two things: 1) implements `ViewService#auctions`, and 2) creates a basic UI for viewing your existing auctions (basically as a proof of concept that the RPC method works).
- Create a basic UI for rendering the user's auctions. This will grow over time as we add features to it, like ending/withdrawing from auctions.
- Implement part of the `ViewService#auctions` RPC method (except `queryLatestState` and `includeInactive` — see below).
- Create an `AUCTIONS` IndexedDB table to store `DutchAuctionDescription`s and their corresponding NFTs' `noteCommitment`s, keyed by `AuctionId`.
- Update the block processor to save auction data to the database when it encounters that data.
- Extract a `<DutchAuctionComponent />` that's shared by `<ActionDutchAuctionScheduleViewComponent />` and …
=> `ViewService#auctions` RPC method and basic auctions UI

apps/minifront/src/state/staking/assemble-undelegate-claim-request.ts, packages/getters/src/balances-response.ts, packages/getters/src/get-validator-info-response.ts, packages/services/src/staking-service/get-validator-info.test.ts, packages/services/src/staking-service/get-validator-info.ts, packages/services/src/staking-service/index.ts, packages/services/src/test-utils.ts, packages/services/src/view-service/unbonding-tokens-by-address-index/helpers.ts, packages/services/src/view-service/unbonding-tokens-by-address-index/index.test.ts, packages/services/src/view-service/unbonding-tokens-by-address-index/index.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
> This is because getUndelegateClaimPlannerRequest cannot recover the IdentityKey from the token's value view. The reason for that is that the ValueView is missing extended_metadata which only get populated for bonding tokens.
Now extended_metadata fills in for unbonding tokens as well
close #1043
=> 1043 minifront cannot claim unbonding tokens

apps/extension/.env.testnet, apps/minifront/src/components/swap/dutch-auction/auctions.tsx, apps/minifront/src/components/swap/dutch-auction/dutch-auction-loader.ts, apps/minifront/src/state/dutch-auction/assemble-schedule-request.test.ts, apps/minifront/src/state/dutch-auction/assemble-schedule-request.ts, apps/minifront/src/state/dutch-auction/index.ts, packages/perspective/transaction/classification.ts, packages/perspective/transaction/classify.test.ts, packages/perspective/transaction/classify.ts, packages/ui/components/ui/auction-id-component.tsx, packages/ui/components/ui/dutch-auction-component.tsx, packages/ui/components/ui/tx/view/action-dutch-auction-end.tsx, packages/ui/components/ui/tx/view/action-view.tsx, packages/wasm/crate/src/metadata.rs, packages/wasm/crate/src/planner.rs
Now that auctions can be scheduled and viewed, it's time to allow users to end them!
https://github.com/penumbra-zone/web/assets/1121544/de0dcec0-0b31-461f-ad29-994e3d7ae9f2
- Modify `<DutchAuctionComponent />` to render an "End auction" button.
- Create `<ActionDutchAuctionEndComponent />` to render the action of ending an auction.
- Change metadata symbols for auction NFTs to include the sequence numbers (before: `auction(abcd1234...)`; after: `auction@1(abcd1234...)`
- While I was at it, I changed all the customized symbols to use ellipses, since those display more nicely.
Before:
After:
- Change the shape of the `dutchAuction` state slice; now, there's an `auctionInfos` array instead of an `auctions` array. Each `AuctionInfo` contains the auction ID and the `DutchAuction` (because the …
=> UI for ending auctions

apps/extension/.env.testnet, apps/minifront/src/components/swap/dutch-auction/auctions.tsx, apps/minifront/src/components/swap/dutch-auction/dutch-auction-loader.ts, apps/minifront/src/state/dutch-auction/assemble-schedule-request.test.ts, apps/minifront/src/state/dutch-auction/assemble-schedule-request.ts, apps/minifront/src/state/dutch-auction/index.ts, packages/perspective/transaction/classification.ts, packages/perspective/transaction/classify.test.ts, packages/perspective/transaction/classify.ts, packages/query/src/block-processor.ts, packages/query/src/queriers/auction.ts, packages/query/src/root-querier.ts, packages/services/src/test-utils.ts, packages/services/src/view-service/auctions.test.ts, packages/services/src/view-service/auctions.ts, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts, packages/types/src/indexed-db.ts, packages/types/src/protobuf.test.ts, packages/types/src/protobuf.ts, packages/types/src/querier.ts, packages/ui/components/ui/auction-id-component.tsx, packages/ui/components/ui/dutch-auction-component.tsx, packages/ui/components/ui/tx/view/action-dutch-auction-end.tsx, packages/ui/components/ui/tx/view/action-view.tsx, packages/wasm/crate/src/metadata.rs, packages/wasm/crate/src/planner.rs
`AuctionsRequest`s have an `includeInactive` property that was not yet supported by our `auctions` implementation. This PR adds support for that property by A) keeping track of auctions' sequence numbers to determine whether they're active, and B) filtering out inactive auctions unless `includeInactive` is `true`.
- Add a `seqNum` column to the `AUCTIONS` table (to mimic the `state` column in [core](https://github.com/penumbra-zone/penumbra/blob/main/crates/view/src/storage/schema.sql#L136-L140)'s implementation)
- Upsert the `seqNum` in the block processor when we encounter a Dutch auction-related action.
- Add support for `includeInactive` in the `ViewService#auctions` RPC method.
- Bump the IndexedDB version number.
Relates to #980 (but doesn't close it yet, since `queryLatestState` is …
=> Handle `includeInactive` in `ViewService#auctions`

apps/minifront/src/state/ibc-out.ts
The ibc page is broken if you have unknown assets on your balance
=> Fix unknown assets for ibc-out

packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/planner.rs, packages/wasm/crate/tests/build.rs
Core was previously missing a necessary middleware for its auction endpoint. As a result, calls to that endpoint would fail due to a missing trailer.
This was [recently fixed](https://github.com/penumbra-zone/penumbra/pull/4351), so this PR points the WASM crate to the SHA that fixed that issue, so that calls to get the latest auction state from the fullnode will succeed.
This PR also addresses a couple typings changes from core that resulted from the update.
=> Update WASM crate to point to SHA of core that includes correct middleware

apps/minifront/vite.config.ts, apps/node-status/vite.config.ts
both node-status and minifront vite dev servers clear the terminal by default. this prevents that, so you can see full messages from all dev scripts.
=> vite don't clear terminal

packages/ui/components/ui/dutch-auction-component.tsx, packages/ui/components/ui/tx/view/value/index.tsx
This is by no means a finalized design — just a little improvement from the key/value layout before. A future PR will improve the design of the duration field.
Closes #1081
=> Redesign the input/output UI of a Dutch auction to better illustrate what's happening

apps/minifront/src/components/Status.tsx, apps/minifront/src/components/header/sync-status-section.tsx, apps/minifront/src/components/layout.tsx, apps/minifront/src/components/swap/dutch-auction/auctions.tsx, apps/minifront/src/state/index.ts, apps/minifront/src/state/status.ts, packages/ui/components/ui/dutch-auction-component/duration.tsx, packages/ui/components/ui/dutch-auction-component/get-price.test.ts, packages/ui/components/ui/dutch-auction-component/get-price.ts, packages/ui/components/ui/dutch-auction-component/get-progress.test.ts, packages/ui/components/ui/dutch-auction-component/get-progress.ts, packages/ui/components/ui/dutch-auction-component/get-step-index.test.ts, packages/ui/components/ui/dutch-auction-component/get-step-index.ts, packages/ui/components/ui/dutch-auction-component/index.tsx, packages/ui/components/ui/dutch-auction-component/price-graph.tsx, packages/ui/components/ui/progress.tsx, packages/ui/components/ui/tx/view/asset-icon/index.tsx, packages/ui/components/ui/tx/view/value/index.tsx, packages/ui/lib/toast/transaction-toast.test.tsx, packages/ui/lib/toast/transaction-toast.tsx
Scrub through this video to get a timelapse of part of a 10-minute auction.
https://github.com/penumbra-zone/web/assets/1121544/ad04a0cf-3020-4560-939d-0bd69a15020f
This is a bit of a frilly PR that I prob shouldn't have spent as much time on as I did... Basically it visualizes to the user what the current price is of the input asset in terms of the output asset, as well as how far along we are in the auction.
Again, this is by no means a finalized design, but it's at least an improvement on what we had before.
- Design a live-updating display for Dutch auctions.
- Create a new Zustand `status` slice for storing the sync status (`fullSyncHeight` and `latestKnownBlockHeight`) so it can be used both in the header and in places like Dutch auctions.
- Simplify `<Progress />` to only accept a …
=> Redesign Duration display for Dutch auctions with live-updating price visualization.

apps/minifront/src/state/send.ts, packages/types/src/amount.test.ts, packages/types/src/amount.ts, packages/ui/components/ui/tx/view/value/index.tsx, packages/ui/components/ui/tx/view/value/value.tsx
close #1107 & close #1108
**1. Dashboard**
Before:
After:
<hr>
**2. Send**
Before:
After:
<hr>
**3. Tx page**
Before:
After:
<hr>
=> fix unknownAssetId bugs

apps/extension/src/routes/popup/home/index-header.tsx
Removing this:
It's only needed in minifront. We don't show any balances in the extension.
=> Remove testnet warning from ext

apps/extension/.env.testnet, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
=> idb plainmessage gasprices

apps/minifront/src/components/shared/edu-panels/edu-info-card.tsx, apps/minifront/src/components/swap/dutch-auction/auctions.tsx, apps/minifront/src/components/swap/dutch-auction/query-latest-state-button.tsx, apps/minifront/src/components/swap/swap/unclaimed-swaps.tsx, apps/minifront/src/state/dutch-auction/index.ts, packages/services/src/test-utils.ts, packages/services/src/view-service/auctions.test.ts, packages/services/src/view-service/auctions.ts, packages/ui/components/ui/dutch-auction-component/index.tsx, packages/ui/components/ui/dutch-auction-component/reserves.tsx, packages/ui/components/ui/gradient-header.tsx
- Add a button to the auctions list to query the latest auction state.
- Show the current reserves of the auction if we have them.
- Extract a `<GradientHeader />` component, to avoid having to copy a bunch of Tailwind classes.
- Show an auction's outstanding reserves if there is an entry in the `AUCTION_OUTSTANDING_RESERVES` IDB table (i.e., when an auction has ended but its reserves haven't yet been claimed).
- I realized we could have been doing this all along without even querying the latest state, since we know an auction's reserves when it ends.
Closes #1059
=> Create UI to allow users to query latest auction state

.changeset/cool-bats-change.md, apps/minifront/src/components/root-router.tsx
https://github.com/penumbra-zone/web/assets/16624263/7b28b6cd-ffa0-4c4e-8fca-20a1f746b356
Closes #960
=> Fix issue with how error splash page was rendered

.changeset/empty-panthers-guess.md, apps/minifront/src/state/dutch-auction/index.ts
1. Load the auctions page.
2. Observe that auctions are loading.
3. Click the "Query latest state" button.
The auctions list gets wiped out and reloaded from scratch.
The auctions list does not get wiped out; and eventually, we get thousands of errors about duplicate React keys being used (because the same auction is being rendered multiple times).
The reason behind this is that one request to get auctions is still getting a streaming response while the next request fires off and gets its own streaming response, thus resulting in multiple streams of the same auctions being streamed simultaneously. 
To fix this, I introduced an `AbortController` that gets aborted when a new request starts.
Once I work on #965, we'll hopefully have a more elegant solution to this. …
=> Use an AbortController to cancel in-flight streaming responses when a new request starts

apps/minifront/src/components/extension-unavailable.tsx
WIP 
This essentially fixes #962, but needs to also solve #990 to be able to show the user in the extension toast with a link to the node status page
=> WIP: 962 unavailable page links to app not node status page

packages/wasm/crate/src/view_server.rs, packages/wasm/src/build.ts, packages/wasm/src/view-server.ts
remove the existing call `toJson` and replaces it with `toBinary`.
=> block processor serialization

packages/getters/src/spendable-note-record.ts, packages/services/src/view-service/balances.ts
close #1112 
Based on Henry's suggestion:
> Zero-valued notes shouldn't need to be filtered out at the RPC or UI layers, because we should eliminate them at the scanning layer -- when we detect a note, we should skip recording it if it's zero-valued.
I was considering 3 options:
1. Filter out zero notes at the scanning stage in wasm 
2. Filter zero notes immediately before saving to indexed-db
3. Save zero notes, but filter them only on retrieval where necessary.
The first two options would obviously be preferable from a performance point of view 
- we would store less data in indexed-db
- we could hope that this would have a positive effect on synchronization speed. 
But, both of these options result in us not having enough data to properly display swap transaction info
Therefore, I just …
=> do not display zero balances

.changeset/bright-toys-unite.md, apps/extension/package.json, apps/minifront/package.json, packages/services-context/package.json, packages/storage/package.json, pnpm-lock.yaml
Update registry to latest:
- Fixes Penumbra labs icons+asset ids
- Adds metadata for Starling
@plaidfinch, registries are loaded into the extension. So when we deploy that early next week, this will be visible 🤩
=> Update to latest registry [Starling addition]

.changeset/polite-coins-lie.md, packages/wasm/crate/src/asset.rs, packages/wasm/crate/src/lib.rs, packages/wasm/src/asset.test.ts, packages/wasm/src/asset.ts
this allows a caller to convert from an altBaseDenom string to the binary asset id, by using the core class's acceptance of altBaseDenom as hash input
=> expose wasm asset id generation

.changeset/flat-pillows-hear.md, .changeset/fresh-bugs-pretend.md, .changeset/yellow-walls-drum.md, packages/bech32m/package.json, packages/getters/README.md, packages/getters/package.json, packages/getters/vite.config.ts, packages/perspective/package.json, packages/perspective/vite.config.ts, packages/protobuf/README.md, packages/protobuf/package.json, packages/tailwind-config/package.json, packages/tsconfig/package.json, packages/types/package.json, packages/types/vite.config.ts, packages/wasm/README.md
- correctly locates `files` field of package.json
- removes `/src/` segment from imports of published getters
- externalizes dependencies of perspective, types
- significantly reduces build output
- now uses peer depends for message types
- remove `bundledDependencies` from protobuf package
- i think this wasn't actually working anyway, for pnpm reasons?
- bundledDependencies could not be shared to satisfy peers, which was half the point
added a note about how to enable the BSR to packages that contain readmes.
=> fix some package details

apps/extension/.env.testnet, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/wasm/crate/src/storage.rs, packages/wasm/crate/tests/build.rs
close #1152 
This also emphasizes the difference between rust view service data storage, where a relational database is used, and extension view service where a non-relational indexed-db is used. 
The point is that in the relational model, each `SPENDABLE_NOTES` must have a corresponding record in the `NOTES` table (`note_commitment` is used as a foreign key). Therefore, in rust view service the `NOTES` table stores both notes that do not yet have an associated record in the `SPENDABLE_NOTES` table (we call them advices) and notes that already have an associated record in `SPENDABLE_NOTES`
In indexed-db, we store advices separately in the `ADVICE_NOTES` table, and store spendable notes along with nested notes in the `SPENDABLE_NOTES` table
=> change NOTES in db to ADVICE_NOTES

.changeset/strong-ears-smell.md, packages/wasm/crate/src/tx.rs
=> include transaction id when generating perspective

.changeset/lazy-goats-divide.md, packages/protobuf/src/registry.ts
`DutchAuction` was removed from registry in #1209 as i believed it was included in the auction service definition, but this was incorrect. it's restored in this PR.
=> restore DutchAuction to registry

.changeset/breezy-birds-yell.md, apps/minifront/src/components/swap/swap-form/output/estimated-output-explanation.tsx, apps/minifront/src/components/swap/swap-form/simulate-swap-result/trace/price.tsx, packages/types/src/amount.ts, packages/ui/components/ui/balance-value-view.tsx, packages/ui/components/ui/dutch-auction-component/expanded-details/index.tsx, packages/ui/components/ui/tx/view/value/index.tsx
For higher-precision decimal numbers, we were getting a `NaN` showing in the UI:
Turns out because we were using `formatNumber()` sometimes returns a comma separated string which cannot be put inside the `new BigNumber()` constructor. This PR changes the API for that function to be explicit with commas usage, which fixes it:
===
Extracted from https://github.com/penumbra-zone/web/pull/1151. Merging this will make that PR smaller.
=> `formatAmount()` updated args [bug fix]

docs/adrs/003-action-views.md
References https://github.com/penumbra-zone/web/issues/1040
this spec is intended to inform what information should / should not be comprehended and exposed during signing a penumbra transaction. any suggestions regarding formatting the markdown file would be appreciated!
=> view: audit action views

.changeset/shaggy-knives-protect.md, packages/types/src/value-view.test.ts, packages/types/src/value-view.ts
Reported by @VanishMax
Follow up from https://github.com/penumbra-zone/web/pull/1151
When an asset is known, but has no metadata, we should also be able to format correctly (at the moment, an error bubbles up blocking page view). Added tests as well to cover this case.
=> Properly format if no metadata

.changeset/cuddly-beds-move.md, apps/minifront/src/state/ibc-out.test.ts, apps/minifront/src/state/ibc-out.ts
Closes #1241 
I noticed the tests were skipped in the `ibc-out.test.ts` file. I un-skipped the passing tests and added a comment for the future to fix the broken tests
=> fix: #1241: Fix destination validation in the ibc-out form

.changeset/old-candles-compete.md, .changeset/shiny-steaks-sleep.md, packages/ui/components/ui/box.tsx, packages/ui/components/ui/tx/view/action-details.tsx, packages/ui/components/ui/tx/view/delegate.tsx, packages/ui/components/ui/tx/view/undelegate.tsx, packages/ui/components/ui/tx/view/viewbox.tsx
Closes #1195 
Screenshot of the problem:
=> fix: #1195: Hide the redundant scroll caused by long addresses

.changeset/mean-seahorses-run.md, packages/wasm/crate/src/tx.rs
Defining a wasm-bindgen struct allows for a simpler return value while keeping the same type signature.
Follow up from: https://github.com/penumbra-zone/web/pull/1255#pullrequestreview-2101210513
=> Return a TxInfo struct [#1255 follow up]

apps/minifront/src/components/tx-details/hooks.ts, apps/minifront/src/components/tx-details/tx-viewer.tsx, packages/types/src/environment.ts
References #483 and https://github.com/penumbra-zone/web/issues/1251#issuecomment-2150629725
@jessepinho the `asReceiverTransactionView` translator from the transaction approval dialog is reused in the transaction view page. Currently, i'm displaying _every_ transaction with an associated receiver view which obviously is **not** correct. 
There seems to be some misdirection in the `TransactionViewSwitcher` component that I couldn't quite parse, mainly where the actual filtering is happening that determines if the receiver view should be present or not. Is there a simple way to propagate this filtering to the transaction view page in this PR?
=> views: extract receiver view into transaction view

README.md
We have an email alias set up for team leads, so that external parties have a single entrypoint to disclose security-related issues. This language matches what's already in the Penumbra monorepo, as of [0].
[0] https://github.com/penumbra-zone/penumbra/pull/4298
=> docs: add security email info to readme

apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
Numbers being used as booleans need to be coerced to a boolean in component markup or else they'll show up as `0` when they're equal to `0`.
=> Remove '0' from token swap input

.changeset/sixty-spiders-thank.md, packages/query/src/block-processor.ts
prevents https://github.com/penumbra-zone/penumbra/issues/4577 in the web block processor
=> check height of incoming block

apps/minifront/src/components/shared/asset-selector.tsx
Seems that I missed that when I made a similar animation in `<BalanceSelector />`. This PR fixes that.
You may want to review this with ["Hide whitespace" turned on](https://github.com/penumbra-zone/web/pull/1273/files?diff=split&w=1).
https://github.com/penumbra-zone/web/assets/1121544/5d821348-804d-4ecb-b34e-5bc5152cedba
=> Make AssetSelector dialog appear to grow out of button

.changeset/smart-plums-float.md, apps/minifront/src/components/swap/swap-form/index.tsx, apps/minifront/src/components/swap/swap-form/output/estimated-output-explanation.tsx, apps/minifront/src/components/swap/swap-form/output/index.tsx, apps/minifront/src/state/swap/dutch-auction/index.test.ts, apps/minifront/src/state/swap/dutch-auction/index.ts, apps/minifront/src/state/swap/index.test.ts, apps/minifront/src/state/swap/index.ts, apps/minifront/src/state/swap/instant-swap.ts, packages/getters/src/balances-response.ts
Enforcing that max output is greater than min output, and that the two assets are not the same:
https://github.com/penumbra-zone/web/assets/1121544/760f109e-f1e3-4378-8396-b809588af08e
Enforcing a value greater than 0 for outputs:
https://github.com/penumbra-zone/web/assets/1121544/35c59fba-1dd2-47e8-a55e-3a96726a6739
Closes #1284
Closes #1224
=> Enforce sane inputs for the swap/auction UI

.changeset/gentle-laws-unite.md, packages/getters/src/utils/create-getter.test.ts, packages/getters/src/utils/create-getter.ts
Well, this turned out to be easier than expected!
Previously, we couldn't call `.optional()` at just any point in a getter chain; instead, we had to call it on the first getter in the chain. e.g., 
```ts
const myGetter1 = getter1.optional().pipe(getter2).pipe(getter3) // Will truly be optional
const myGetter2 = getter1.pipe(getter2).pipe(getter3).optional() // Will throw if any getter in the chain returns `undefined`
```
With this PR's change, `.optional()` can now be called at any point in the chain, and it will work as expected!
Closes #1153
=> Tweak getters to allow .optional() to be called at any point in a getter chain

packages/ui/components/ui/tx/view/swap/one-way-swap.tsx
=> Always show the asset logo in swaps

.changeset/wet-fireants-rush.md, apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.test.ts, apps/minifront/src/components/swap/auction-list/index.tsx, apps/minifront/src/fetchers/auction-infos.ts, packages/services/src/view-service/auctions.ts
Full context for this PR, if reviewers are interested:
Dutch auctions have a concept of a ["sequence number"](https://github.com/penumbra-zone/penumbra/blob/v0.77.1/proto/penumbra/penumbra/core/component/auction/v1/auction.proto#L100-L104), which represents which state the auction is in. `0` means the auction is open, `1` means it's closed, and `2`+ means the user has withdrawn the funds from the auction after it's closed. (The user can theoretically do an infinite number of withdrawals, but the first withdrawal results in all funds being withdrawn, so any future withdrawals have no financial impact. For this reason, minifront only shows a Withdraw button for auctions with a sequence number of `1`, and hides the Withdraw button if the sequence number is >= `2`.)
These sequence states are …
=> Use localSeq for determining which sequence number Prax has saved for an auction

.changeset/flat-cups-behave.md, packages/zquery/package.json, packages/zquery/src/index.test.ts
While pairing with @VanishMax on ZQuery, I noticed that there was a TypeScript error in the ZQuery tests that wasn't being caught, and that the ZQuery tests were failing without breaking the build. That was because the `test` script (as well as others) was missing from ZQuery's `package.json`. This PR fixes that, as well as the broken test.
=> Add missing scripts to ZQuery package and fix tests

.changeset/four-forks-turn.md, apps/minifront/src/components/swap/auction-list/index.tsx, apps/minifront/src/components/swap/auction-list/query-latest-state-button.tsx, apps/minifront/src/state/status.ts, apps/minifront/src/state/swap/dutch-auction/index.ts, packages/ui/components/ui/dutch-auction-component/expanded-details/index.tsx, packages/zquery/src/index.ts, packages/zquery/src/types.ts
Previously, ZQuery provided no way to update items in place when a stream was restarted. Instead, when a stream was restarted, ZQuery would set the state to `undefined`, then start processing streaming responses again.
With this PR's change, we can now handle streams a bit more intelligently. ZQuery no longer sets the state to `undefined` when restarting a stream; instead, it calls a new `onStart()` reducer (if it's passed to `createZQuery()`). Similarly, when a stream ends, errors, or is aborted, it calls handlers for those. It also calls an `onValue()` reducer when a value is received from the stream.
All those reducers are now returned by a `stream` function that consumers pass to `createZQuery()`, which allows consumers to maintain a JavaScript scope over the life of a stream. This …
=> Update auctions in place

apps/minifront/src/components/ibc/ibc-in/chain-provider.tsx
Closes https://github.com/penumbra-zone/web/issues/1050
All of these require the project to have a WalletConnect account and API key. Not compatible with a decentralized project. Removing from the list:
Normal chrome extension integrations still in place:
=> Remove mobile wallets from cosmos-kit

.changeset/pretty-snakes-bow.md, apps/minifront/src/components/header/menu/menu.tsx, apps/minifront/src/components/header/menu/provider.tsx, packages/ui/components/ui/network.stories.tsx
Note the page links jammed against the top, and the wrapping chain ID
https://github.com/penumbra-zone/web/assets/1121544/06af0615-4c63-4db8-9431-08ff862c1f26
https://github.com/penumbra-zone/web/assets/1121544/86d5dd42-dcea-4934-9e9c-bf258fa902c4
=> Fix a few issues with the header

.changeset/funny-schools-kick.md, .changeset/poor-rabbits-deny.md, buf-replacer.js, package.json, packages/bech32m/package.json, packages/client/package.json, packages/crypto/package.json, packages/getters/package.json, packages/perspective/package.json, packages/protobuf/package.json, packages/query/package.json, packages/services/package.json, packages/storage/package.json, packages/transport-chrome/package.json, packages/transport-dom/package.json, packages/tsconfig/base.json, packages/tsconfig/vite.json, packages/types/package.json, packages/ui/tsconfig.json, packages/wasm/package.json, pnpm-lock.yaml
uses `tsc-alias` to generate correct import paths for esm support
this may have been related to issues @VanishMax was experiencing
this should permit esm resolution to work properly for the packages' internal modules
edit: okay, tsc-alias doesn't completely solve the issue - 
bundlers are fine now, but anything that needs to use node module resolution (vitest, many consumers) will encounter problems because our packages currently use nonstandard module resolution to identify imports from external dependencies.
the tsc-alias tool is only indended for internal paths.
probably we should just comply with esm path spec internally, but that would require changing nearly every import in the codebase, so this PR now combines tsc-alias and changes imports to name external 'js' files that are not …
=> properly output esm

.changeset/dirty-turtles-fail.md, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/indexed-db.test.ts
=> switch to using IDB_VERSION defined inside the package

.changeset/rude-taxis-raise.md
Fix broken pipelines because the package name does not exist anymore
=> fix: changeset

.changeset/moody-bulldogs-mate.md, .changeset/pink-starfishes-confess.md, .gitignore, apps/minifront/src/components/header/menu/provider.tsx, apps/minifront/src/components/shared/error-boundary.tsx, apps/minifront/src/prax.ts, packages/client/README.md, packages/client/package.json, packages/client/src/create.ts, packages/client/src/error.ts, packages/client/src/index.ts, packages/transport-chrome/src/session-client.ts, packages/transport-dom/src/create.ts, pnpm-lock.yaml
https://github.com/penumbra-zone/web/assets/134443988/00e35e04-1447-4ded-ad79-c86c1f0433a8
closes #1192 
adds disconnect method to page api
page injection is refactored as a class to more explicitly represent and control injection state
origin-agnostic connection init helpers are exported from client package
transport may convey a simple 'false' indicating termination
disconnect minifront ui ready in merged #1276 but commented out
still needs a type guard for the provider manifest
=> disconnect api

.changeset/cuddly-files-share.md, packages/client/src/create.ts
fix should allow minifront to resume deployment at head of main.
this is technically incorrect by the design described but will accommodate the misaligned logic in released providers.
emitting an inappropriate request at this point is harmless because the promise will just be immediately denied
https://github.com/penumbra-zone/web/blob/649e3e7d25f0a2f855ac5a63bc869328b056bd19/packages/client/src/index.ts#L5-L32
=> fix: request for connection upon false isConnected state

.changeset/tasty-pugs-develop.md, apps/minifront/src/state/ibc-in/parse-revision-number-from-chain-id.test.ts, apps/minifront/src/state/ibc-in/parse-revision-number-from-chain-id.ts
Our current parsing is inconsistent with the way the Rust core code is doing this. This PR aligns with the core implementation: https://github.com/penumbra-zone/ibc-types/blob/73da5ee5d06b5f62c186b31ce37f7669edc8bbf2/crates/ibc-types-core-connection/src/identifier.rs#L76-L87 so as to prevent bugs with potential chain ids.
=> Update revision number parsing

.changeset/lovely-teachers-relax.md, apps/minifront/src/components/dashboard/assets-table/index.tsx, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, apps/minifront/src/state/swap/index.ts, apps/minifront/src/state/swap/query-params.test.ts, apps/minifront/src/state/swap/query-params.ts, apps/minifront/src/state/swap/set-initial-assets.test.ts, apps/minifront/src/state/swap/set-initial-assets.ts, apps/minifront/src/utils/empty-balance-response.ts
Closes #1169 
Adds support for `from`, `to`, and `account` query parameters on the Swap page. Also, adds a link from the assets table to trade each available asset.
Query params save `asset.symbol` string and compute the matches by it.
https://github.com/penumbra-zone/web/assets/29180358/ef89dba7-f00f-4d8b-b41d-88431b6a90a3
=> feat: #1169: add swap query params

.changeset/tasty-pugs-develop.md, apps/minifront/CHANGELOG.md, apps/minifront/package.json, apps/minifront/src/fetchers/registry.ts, apps/node-status/CHANGELOG.md, apps/node-status/package.json, packages/crypto/CHANGELOG.md, packages/crypto/package.json, packages/perspective/CHANGELOG.md, packages/perspective/package.json, packages/query/CHANGELOG.md, packages/query/package.json, packages/services/CHANGELOG.md, packages/services/package.json, packages/services/src/test-utils.ts, packages/services/src/view-service/transaction-planner/index.test.ts, packages/services/src/view-service/transaction-planner/index.ts, packages/storage/CHANGELOG.md, packages/storage/package.json, packages/storage/src/indexed-db/index.ts, packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/indexed-db.ts, packages/ui/CHANGELOG.md, packages/ui/components/ui/tx/index.tsx, packages/ui/components/ui/tx/registry.tsx, packages/ui/package.json, packages/wasm/CHANGELOG.md, packages/wasm/package.json, pnpm-lock.yaml
related to https://github.com/prax-wallet/web/pull/66
=> bump registry

apps/minifront/CHANGELOG.md, apps/minifront/package.json, apps/node-status/CHANGELOG.md, apps/node-status/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/crypto/CHANGELOG.md, packages/crypto/package.json, packages/getters/CHANGELOG.md, packages/getters/package.json, packages/perspective/CHANGELOG.md, packages/perspective/package.json, packages/protobuf/CHANGELOG.md, packages/protobuf/package.json, packages/query/CHANGELOG.md, packages/query/package.json, packages/services/CHANGELOG.md, packages/services/package.json, packages/storage/CHANGELOG.md, packages/storage/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/ui/CHANGELOG.md, packages/ui/package.json, packages/wasm/CHANGELOG.md, packages/wasm/package.json
Protobuf package was not published with recent version bumps. This causes peer dependency issues with consumers.
Going to merge this without review to unblock release.
=> Synchronize buf deps

apps/minifront/src/components/dashboard/assets-table/helpers.ts, apps/minifront/src/components/send/helpers.ts, apps/minifront/src/components/shared/selectors/balance-item.tsx
Closes #1372 
Filter out unknown assets from the asset list and from the asset selection. Also fixed the display of unknown assets in case we want to go back to them
=> fix BalanceItem

.changeset/tough-mugs-sneeze.md, packages/services/src/view-service/fees.test.ts, packages/services/src/view-service/fees.ts, packages/services/src/view-service/transaction-planner/index.test.ts, packages/services/src/view-service/transaction-planner/index.ts, packages/wasm/src/planner.ts
Some follow up after https://github.com/penumbra-zone/web/issues/1165
After pairing with @vacekj, noticed a few areas of improvement with type checking + test coverage
=> Fee extraction tests + refactor

.changeset/nine-students-fry.md, apps/minifront/src/components/swap/swap-form/output/index.tsx, apps/minifront/src/state/swap/dutch-auction/index.test.ts, apps/minifront/src/state/swap/dutch-auction/index.ts
- Start with empty max/min output amounts
- Allow users to empty the fields as well
- Only show an error when invalid values have been entered in the fields (not when the fields are empty)
- Show a `0` placeholder to indicate that it's a text field
Closes #1387
=> Fix auction pre-filled amounts

apps/minifront/src/components/header/menu/provider.tsx, apps/minifront/src/components/header/menu/tablet-nav.tsx
This removes the borders between items in the menu dropdown, but that's fine as we're overhauling the design system soon anyway.
=> Fix React warnings about nested <li> elements

apps/minifront/src/components/shared/selectors/asset-selector.tsx, apps/minifront/src/components/shared/selectors/balance-item.tsx, apps/minifront/src/components/shared/selectors/balance-selector.tsx
I started by simply moving the Account column to the left, but then the headers and contents became misaligned:
I then realized that we weren't using a `<Table />` when we should have been, so I converted the `<BalanceSelector />` to use a `<Table />`, and that fixed the layout issues:
But then that gave it borders, which no longer matched `<AssetSelector />`. Plus, its spacing was different. Rather than hack custom styles to make them match, I simply converted `<AssetSelector />` to a `<Table />` instead.
I also noticed that `<AssetSelector />` didn't have an indicator of which one was currently selected (like` <BalanceSelector />` did), so I added a light gray background to the currently selected asset.
I could have gone further (e.g., making the hover/selected background full-width on …
=> Move the Account column to the left of asset selectors; fix a few UI issues

.changeset/light-clouds-look.md, apps/minifront/src/components/root-router.tsx
This fixes an issue where some routes were missing the loader, so the landing page would not show up correctly when the extension was not yet connected.
Closes #1344
Note that #1344 only mentions the transactions page, but the same issue was also present on the `/send/receive` page, since it was also missing the `abortLoader`.
=> Move the abortLoader to the root route

.changeset/silent-cycles-rush.md, packages/ui/components/ui/tx/actions-views/isc20-withdrawal.tsx
Relates to https://github.com/prax-wallet/web/pull/90
Renders the withdrawal transaction like this:
=> fix(ui): format time in UTC for withdrawal transactions

.changeset/tasty-emus-worry.md, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, packages/services/src/view-service/assets.ts
fixes #1371
also fixes the asset out balance issue + priority scores issue in the `assets` service that caused the problem with metadata comparison
=> fix: #1371: candelesticks and the rest

.changeset/clean-jeans-worry.md, .changeset/four-penguins-jump.md, .changeset/lazy-forks-brush.md, apps/minifront/src/state/swap/instant-swap.ts, apps/minifront/src/state/unclaimed-swaps.ts, packages/services/src/view-service/fees.test.ts, packages/services/src/view-service/fees.ts, packages/services/src/view-service/transaction-planner/index.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
references https://github.com/penumbra-zone/web/issues/1407
=> fix swap claim bug for multi-fees

.changeset/ten-bugs-walk.md, apps/minifront/src/components/shared/error-boundary.tsx, packages/client/src/create.ts, packages/client/src/error.ts, packages/client/src/event.ts, packages/client/src/index.ts
Describe interfaces for injection state.
as suggested in https://github.com/penumbra-zone/web/pull/1293#discussion_r1660844191
uses an EventTarget to manage subscribers, and an event type extending CustomEvent
=> injection state and event subscription

packages/ui/components/README.md, packages/ui/package.json, packages/ui/readme.md, packages/ui/tsconfig.json
This sets out some coding standards for the new UI library to ensure file structure, naming, etc. are consistent.
Only requesting a review from Gabe, but others should feel free to review as well.
Closes https://github.com/prax-wallet/web/issues/82
=> README for new UI library

docs/adrs/005-ui-library-css.md
This PR is a request for comments on the ADR I've written. Please read the ADR ([Markdown preview here](https://github.com/penumbra-zone/web/blob/04319e9a79347203f9eea19a5f7d0493dbe54878/docs/adrs/005-ui-library-css.md)), and make inline comments on the file or general comments here in the PR thread.
I've written the ADR as though it's a finished decision, but obviously it's not — I just wrote what my decision would be, as a starting point for the rest of the team to comment on it.
Since our web weekly tomorrow is canceled for July 4th, we'll need to talk about this issue asynchronously here in the PR. Perhaps we can come to a final decision at next Thursday's web weekly, if we haven't already resolved the issue here.
Related to https://github.com/prax-wallet/web/issues/81
=> RFC: styling the UI library

.changeset/cool-coats-complain.md, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, apps/minifront/src/state/swap/getters.ts, apps/minifront/src/state/swap/index.ts
Closes #1225 
Made the arrow button clickable. Reverse actions preserve the account index selected for the assetIn
=> feat(minifront): #1225: reverse swap button

apps/minifront/src/components/ibc/ibc-in/hooks.ts, apps/minifront/src/components/ibc/ibc-in/interchain-ui.tsx
fixes #1449 
ibc page no longer errors, but the page is still not usable because no ibc connections are known to the registry.
=> don't error ibc page if no connections available

.changeset/curly-frogs-grin.md, packages/crypto/package.json, packages/query/package.json, packages/services/package.json, packages/storage/package.json, packages/transport-chrome/package.json, packages/types/package.json
Found a bug while using the `types` package in the Next.js example template saying [`Module not found: Error: Default condition should be last one`](https://stackoverflow.com/questions/76127288/module-not-found-error-default-condition-should-be-last-one). Happens in Next.js and  [microbundle](https://github.com/developit/microbundle) environment.
=> fix: exports default

apps/minifront/src/components/tx-details/tx-viewer.tsx
fixes https://github.com/penumbra-zone/web/issues/1359
=> feat: display block height in tx detail

packages/services/src/view-service/transaction-planner/assert-transaction-source.ts, packages/services/src/view-service/transaction-planner/index.test.ts, packages/services/src/view-service/transaction-planner/index.ts
references https://github.com/penumbra-zone/web/issues/1433
=> check for source in transaction planner request

packages/react/tsconfig.json
this corrects the `@penumbra-zone/react` build which was producing an empty package, due to a rebase mistake
=> `@penumbra-zone/react` tsconfig corrected

apps/minifront/src/state/swap/helpers.ts, apps/minifront/src/state/swap/price-history.ts
fixes https://github.com/penumbra-zone/web/issues/1347 #1183
due to the way price data is recorded, symmetric comparisons do not return symmetric data. to get the complete picture, the client must combine both datasets.
1. query the intended comparison direction (start token -> end token)
2. query the opposite comparison direction (end token -> start token)
3. invert the opposite data (reciprocal values, high becomes low)
4. combine the data (blocks with duplicate records use the highest high, lowest low, sum volumes)
you'll need to run a local devnet and conduct trading activity to view a chart.
=> use inverse candlestick data in chart

.changeset/moody-carrots-rhyme.md, packages/react/README.md, packages/react/src/components/penumbra-context-provider.tsx
Metaframeworks have diverse techniques for segregating server-side and client-side execution, and there is no existing cross-framework solution to identify client side packages.
This PR requires an identified penumbra provider to be passed as a prop to the context wrapper, so that consumers of the package will be required to obtain the injection client-side before it's possible to execute anything requiring context.
=> Force clientside use of `@penumbra-zone/react`

.github/workflows/deploy-ui-preview-pr.yml
Manual testing:
- I pushed up [b598f3a](https://github.com/penumbra-zone/web/pull/1515/commits/b598f3ae1c02bfb5b10060f6a3c627eed0916fad) (the Github workflow change) and observed that this PR [did not deploy an ephemeral Storybook preview URL](https://github.com/penumbra-zone/web/actions/runs/9997927541).
- I then pushed up [0872ecb](https://github.com/penumbra-zone/web/commit/0872ecbc4d537129b5e8fd8e96e80fb74abe9592) (a temporary change to a file inside `packages/ui/src`) and observed that this PR [_did_ deploy an ephemeral Storybook preview URL](https://github.com/penumbra-zone/web/actions/runs/9997999327).
- I then `git reset --hard b598f3a` to go back to the first commit. Note that the `github-actions` comment for the ephemeral Storybook URL is still there — it doesn't get …
=> Only deploy an ephemeral Storybook preview for PRs that make changes to the UI package

.changeset/fresh-camels-live.md, packages/client/package.json, packages/client/src/assert.ts, packages/client/src/index.ts, packages/client/src/manifest.ts, packages/client/tsconfig.json, pnpm-lock.yaml
`PenumbraManifest` type now refers to `@types/chrome` instead of creating a type from scratch
=> export better manifest type

.changeset/hungry-flowers-worry.md, packages/react/src/penumbra-context.ts
missed one lingering reference in a type definition - this should now generally be safe for use without special client/server config
=> remove last window reference from `@penumbra-zone/react`

packages/ui/src/Colors.mdx, packages/ui/src/Colors.stories.tsx
Creates [this page](https://penumbra-ui-preview--pr1500-jessepinho-colors-xw8bzgdf.web.app/?path=/docs/ui-library-colors--docs) in Storybook
=> Create Storybook stories for Penumbra colors

.changeset/shiny-eggs-do.md, apps/minifront/src/components/ibc/ibc-out/ibc-out-form.tsx, apps/minifront/src/components/send/send-form/index.tsx, apps/minifront/src/components/shared/input-token.tsx, apps/minifront/src/components/shared/number-input/index.tsx, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, apps/minifront/src/state/helpers.ts, apps/minifront/src/state/ibc-out.ts, apps/minifront/src/state/send/index.ts
Closes #1139 
Does two things:
- Prohibits entering the number with fractional part length greater than the exponent of a selected token
- Displays a validation error in case this amount was entered, extends the `isValidAmount` function. It can happen when, for example, user first enters the amount in 'UM' token, then changes to a token with different exponent
See how the 'Send' button is disabled. Previously, entering the incorrect decimal amount was considered ok
=> feat(minifront): #1139: decimals validation

.changeset/angry-guests-pay.md, apps/minifront/src/components/ibc/ibc-in/destination-addr.tsx, apps/minifront/src/components/shared/number-input/use-wheel-prevent.ts, apps/minifront/src/components/shared/selectors/balance-item.tsx, apps/minifront/src/components/staking/account/use-staking-tokens-and-filter.ts, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, apps/minifront/src/state/swap/helpers.ts, eslint.config.js, packages/react/src/components/penumbra-context-provider.tsx, packages/ui/components/ui/candlestick-plot/index.tsx, packages/ui/components/ui/tx/index.tsx, packages/zquery/src/get-use-hook.ts
=> re-enable react hooks lint

.changeset/rare-hotels-nail.md, eslint.config.js, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/src/session-manager.ts, packages/transport-dom/src/ReadableStream.from.ts, packages/transport-dom/src/adapter.ts, packages/transport-dom/src/create.test.ts, packages/transport-dom/src/create.ts, packages/transport-dom/src/messages.ts
this will enable consumers to more gracefully abort pending requests, active streams, and transports as a whole
=> add abort signalling and controls to transport

.changeset/late-dancers-check.md, packages/getters/src/delegator-vote-view.ts, packages/perspective/src/translators/action-view.ts, packages/perspective/src/translators/delegator-vote-view.test.ts, packages/perspective/src/translators/delegator-vote-view.ts, packages/ui/components/ui/tx/action-view.tsx, packages/ui/components/ui/tx/actions-views/delegator-vote.tsx
Adds action view support to the tx-details page. Paired w/ @plaidfinch to get current design.
Visible:
Opaque:
=> Delegator voting action view

.changeset/silly-buckets-dream.md, packages/client/src/create.ts, packages/react/src/hooks/use-penumbra-transport.ts, packages/services/src/view-service/util/custody-authorize.ts, packages/transport-chrome/src/session-manager.ts, packages/transport-dom/src/create.ts
- increased to 60 by default
- options applied to one helper that was missing them
- authorization request explicitly disabled timeout
- correctly respect 0-value timeouts in options (like connectrpc)
=> transport timeouts

apps/minifront/vite.config.ts
An action item after https://github.com/penumbra-zone/web/pull/1539 when it was discovered that dev mode is not being passed properly if a prod build
=> check for vite dev mode

.changeset/thirty-avocados-listen.md, packages/perspective/src/plan/view-action-plan.ts
Enables action view in approval window. Without this, there isn't data populated.
=> Action plan -> delegator vote view

.changeset/old-rocks-count.md, packages/wasm/crate/src/auction.rs, packages/wasm/crate/src/metadata.rs
Vote receipt tokens now have proper symbols:
Before:
After:
Also related to https://github.com/penumbra-zone/web/issues/1546, fixed a bunch of tests
=> Customize vote symbol

package.json
prevents accidentally referring to old tarballs
=> rm -fv tgz before dev:pack

packages/ui/src/SegmentedPicker/index.tsx, packages/ui/src/Tabs/index.stories.tsx, packages/ui/src/Tabs/index.test.tsx, packages/ui/src/Tabs/index.tsx, packages/ui/src/utils/button.ts
This PR addresses @VanishMax 's [comment](https://github.com/penumbra-zone/web/pull/1516#discussion_r1687901787) about accessibility issues with the `<SegmentedPicker />` component. To address the issues, I refactored `<SegmentedPicker />` to use Radix UI's fully accessible `<Tabs />` component under the hood. Per Sam's agreement, I also renamed this component to `<Tabs />`.
This component may be modified further once it's being used in actual pages, so this is just a gradual improvement for now.
=> `<SegmentedPicker />`: Use Radix UI's Tabs component under the hood, and rename to `<Tabs />`

packages/ui/.storybook/preview.jsx, packages/ui/README.md, packages/ui/src/Button/index.stories.tsx, packages/ui/src/Button/index.tsx, packages/ui/src/ButtonGroup/index.stories.tsx, packages/ui/src/ButtonGroup/index.tsx, packages/ui/src/Pill/index.stories.tsx, packages/ui/src/Pill/index.tsx, packages/ui/src/Table/index.stories.tsx, packages/ui/src/ValueViewComponent/AssetIcon/index.tsx, packages/ui/src/ValueViewComponent/index.stories.tsx, packages/ui/src/ValueViewComponent/index.tsx, packages/ui/src/utils/button.ts
After my previous PR for [introducing the `<Density />` component](https://github.com/penumbra-zone/web/pull/1545) was merged, we now have a `<Density />` component that sets a context variable for components to use to determine whether to render with `compact` or `sparse` density.
Previously, a bunch of the new UI library components were using a `size` prop to control density. In that previous PR, I mentioned that I would create a follow-up PR to remove their `size` props and instead use the new `useDensity()` hook, which uses the context value set by the `<Density />` component.
This PR is that follow-up PR. It makes that change for the `<Button />`, `<ButtonGroup />`, `<Pill />`, and `<ValueViewComponent />` components.
It also introduces a `density` tag for Storybook stories, which …
=> Use the new `<Density />` component in place of the `size` prop throughout the new UI components

.changeset/nice-mangos-hammer.md, packages/transport-chrome/src/session-manager.ts
Relates to https://github.com/prax-wallet/web/pull/129#issuecomment-2253255191
=> fix(transport-chrome): allow http for localhost

apps/minifront/src/components/swap/swap-form/simulate-swap-result/index.tsx
After a swap claim is successful, if you have the swap estimate component active, it will throw this error:
The reason is because the swap amount in the slice is reset on success and leaves the valueview component with bad inputs (an empty string versus something that can be parsed into a number).
=> NaN bug with simluate selector

.changeset/pretty-poets-rescue.md, apps/minifront/src/state/helpers.ts, packages/services/src/view-service/fees.ts, packages/services/src/view-service/transaction-planner/index.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/wasm/crate/src/storage.rs
references https://github.com/penumbra-zone/web/issues/1604
=> 1604 hastokenbalance should ignore randomizer and use index only

packages/ui/src/Button/index.tsx, packages/ui/src/Tabs/index.tsx, packages/ui/src/utils/button.ts
The `<Tabs />` component was recently redesigned in Figma, so this PR updates how they look. Demo [here](https://penumbra-ui-preview--pr1597-jessepinho-tabs-segm-szcywjtq.web.app/?path=/docs/ui-library-tabs--docs).
=> Redesign `<Tabs />` per Figma

.changeset/gorgeous-toys-compare.md, apps/minifront/src/state/swap/dutch-auction/index.ts
fixes #1619 
Users are confused when the 'Auctions' section of the swap page does not show elapsed auctions. As elapsed auctions require user interaction, these should be visible by default.
This PR is a single-line change to this effect.
=> Show 'All' auctions by default

.changeset/three-sheep-arrive.md, packages/services/src/view-service/delegations-by-address-index.test.ts, packages/services/src/view-service/delegations-by-address-index.ts, packages/types/src/assets.ts
At the moment, the `delegationsByAddressIndex` rpc method is filtering out jailed validators. This prevents users from being able to see the balance on the staking page.
This PR addresses this by performing two steps:
Step 1: query the current list of validators, send those as normal
Step 2: for the delegation token balances that have not been queried, send those in a separate for loop
A PR should follow this to display status more prominently in the frontend.
=> Display jailed validators

.changeset/itchy-files-flow.md, packages/ui/components/ui/copy-to-clipboard/copy-to-clipboard-icon-button.tsx, packages/ui/components/ui/copy-to-clipboard/copy-to-clipboard.tsx
Closes #1590 
Simply removes the unnecessary 'Copied' text from the CopyButton in most of the cases. The green checkmark is visually enough to demonstrate the success state of the button.
=> fix(minifront): #1590: fix copy button styles

.changeset/slow-trees-drum.md, apps/minifront/src/components/staking/account/delegation-value-view/validator-info-component.tsx, apps/minifront/src/components/staking/account/delegation-value-view/validator-state-label.tsx, apps/minifront/src/state/staking/index.ts, packages/getters/src/validator-info.ts, packages/query/src/block-processor.ts, packages/query/src/queriers/staking.ts, packages/services/src/stake-service/get-validator-info.test.ts, packages/services/src/stake-service/get-validator-info.ts, packages/services/src/test-utils.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/types/src/querier.ts
Follow up from: https://github.com/penumbra-zone/web/pull/1640
Does three things:
- Clears out stale validator info entries in the database anytime we need to refetch
- `getValidatorInfo` view service endpoint has a fallback to the node in the case (like jailed validators) it is not in the db
- Adds a component to prominently display bad statuses of validators
=> Jailed validators pt 2: block processor + getValidatorInfo endpoint

apps/minifront/src/components/layout.tsx, apps/minifront/src/components/syncing-dialog/index.tsx
Follow-up to my previous PR that created (but disabled) the syncing dialog. This also makes the dialog dismissible, hence the extra logic.
=> Enable the syncing dialog; make it dismissible

packages/ui/src/SegmentedControl/index.stories.tsx, packages/ui/src/SegmentedControl/index.test.tsx, packages/ui/src/SegmentedControl/index.tsx
This PR creates a `<SegmentedControl />` component built on top of Radix's `<RadioGroup />` component, making it fully accessible and keyboard-controllable.
=> Create SegmentedControl component

docs/adrs/006-web-apis.md
static and instance methods on `PenumbraClient`
- client static methods allow consumers to inspect available providers
- client instance is created to interact with a specific provider
implementation following soon
=> adr 006 changes

.changeset/polite-otters-cheer.md, apps/minifront/src/components/ibc/ibc-out/ibc-out-form.tsx, apps/minifront/src/state/ibc-out.ts, apps/minifront/src/state/index.ts, packages/getters/src/balances-response.ts
~~this PR will conditionally filter um tokens within the ibc out state slice, before they reach the UI asset picker~~
when celestia is selected, filter um tokens from the token picker, when passed into the component prop.
this was easier to confirm behavior than filtering in the state slice.
currently the ibc form will have a pre-filtered set of balances that are already restricted to a chain's native tokens plus um. so, on celestia chain id condition, um is filtered.
=> forbid um ibc out to celestia

.changeset/grumpy-swans-look.md, apps/minifront/src/components/shared/selectors/balance-selector.tsx, apps/minifront/src/components/shared/selectors/helpers.ts, apps/minifront/src/state/send/index.ts, apps/minifront/src/state/swap/dutch-auction/index.ts, apps/minifront/src/state/swap/instant-swap.ts
Closes #1591 
- Refetches BalancesResponse query after successful swap and send
- Updates the BalancesSelector with new value
Demo 1: Send
https://github.com/user-attachments/assets/c8cef95b-b68b-4efa-b12a-207e82fd7efc
Demo 2: Swap
https://github.com/user-attachments/assets/63345360-cf11-46bc-97d6-bb19f19ae168
=> fix(monorepo): #1591: refetch balancesResponses after successful swap and send

.changeset/short-parents-punch.md, apps/minifront/src/components/swap/auction-list/claim-all-button.tsx, apps/minifront/src/components/swap/auction-list/end-or-withdraw-all-button.tsx, apps/minifront/src/components/swap/auction-list/helpers.ts, apps/minifront/src/components/swap/auction-list/index.tsx, apps/minifront/src/state/swap/dutch-auction/index.ts
Demo: 
https://github.com/user-attachments/assets/764af8a2-e251-40c8-9d11-808feee305a9
The limit of max 48 auctions in one transaction is set, but I still have the bug https://github.com/prax-wallet/web/issues/130 , reviewers, please let me know if you have the same.
=> Added end/withdraw all auctions button

.changeset/few-monkeys-thank.md, .changeset/spicy-dragons-do.md, .syncpackrc, apps/minifront/package.json, apps/minifront/src/components/ibc/ibc-out/chain-selector.tsx, apps/minifront/src/state/ibc-in/index.tsx, apps/minifront/src/state/ibc-out.ts, apps/minifront/src/state/shared.ts, apps/node-status/package.json, package.json, packages/client/package.json, packages/getters/package.json, packages/perspective/package.json, packages/protobuf/package.json, packages/query/package.json, packages/react/package.json, packages/services/package.json, packages/storage/package.json, packages/transport-chrome/package.json, packages/transport-dom/package.json, packages/types/package.json, packages/ui/components/ui/tx/actions-views/isc20-withdrawal.tsx, packages/ui/package.json, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/planner.rs, packages/wasm/crate/tests/test_deserialize.rs, packages/wasm/package.json, pnpm-lock.yaml
Part 1 of https://github.com/penumbra-zone/web/issues/1656
Updates to latest bufbuild and penumbra core types
=> Update to types w/ useCompatAddress

.changeset/hungry-jobs-teach.md, packages/ui/.storybook/main.js
@hdevalence noticed that the Penumbra sidebar was rendering incorrectly, because the Poppins font wasn't loaded in Storybook:
This PR fixes that by adding the Google font CSS for Poppins to the Storybook head.
=> Add Poppins font to the Penumbra Storybook head

apps/minifront/src/components/ibc/ibc-out/chain-selector.tsx
Closes https://github.com/penumbra-zone/web/issues/1656
Final step in re-enabling noble in minifront.
=> Re-enable noble Ics20Withdraws

apps/minifront/src/components/root-router.tsx, apps/minifront/src/components/v2/dashboard-layout/assets-card-title.tsx, apps/minifront/src/components/v2/dashboard-layout/assets-page/equivalent-values.tsx, apps/minifront/src/components/v2/dashboard-layout/assets-page/index.tsx, apps/minifront/src/components/v2/dashboard-layout/assets-page/table-title.tsx, apps/minifront/src/components/v2/dashboard-layout/index.tsx, apps/minifront/src/components/v2/dashboard-layout/transactions-card-title.tsx, apps/minifront/src/components/v2/dashboard-layout/transactions-page/index.tsx, apps/minifront/src/components/v2/layout.tsx, apps/minifront/src/components/v2/root-router.tsx, apps/minifront/src/fetchers/page-path.ts, packages/ui/src/Button/index.tsx, packages/ui/src/Card/index.tsx, packages/ui/src/Dialog/index.tsx, packages/ui/src/Display/index.stories.tsx, packages/ui/src/Display/index.tsx, packages/ui/src/Grid/index.tsx, packages/ui/src/PenumbraUIProvider/theme.ts, packages/ui/src/Table/index.tsx, packages/ui/src/ValueViewComponent/index.tsx, packages/ui/src/utils/hexOpacity.ts
This PR creates the first two v2 pages! I started with the simplest ones (assets/transactions) even though they're not 100% ready yet in Figma, because I wanted to just get something shipped.
Note that the layouts are a bit narrow at the moment. But I'm just following Figma designs, so please direct design feedback to Sam 😆 That said, these can be merged as a work in progress, because we're still building out the v2 layouts.
https://github.com/user-attachments/assets/bea9a89b-85fd-4d7f-aec5-21327ba47f77
- Create [v2-prefixed routes](https://github.com/penumbra-zone/web/pull/1607/files#diff-d76fa2d1aa95b7c0191339695bee2306207d3bc5fa8bd2eabcf208b2094f8e64) for the new pages, and [add them to the main router](https://github.com/penumbra-zone/web/pull/1607/files#diff-7a5d45039c54d2c203035a013c …
=> Implement the v2 assets/transactions pages using PenumbraUI

docs/adrs/006-web-apis.md
Specs for the `client` package API. 
Slogan of this PR is: **better developer experience, greater penumbra adoption**
=> feat: add ADR-006 for web APIs and general description

.changeset/wise-buses-switch.md, apps/minifront/src/components/v2/dashboard-layout/assets-page/index.tsx, apps/minifront/src/components/v2/dashboard-layout/index.tsx, packages/ui/src/Button/helpers.ts, packages/ui/src/Button/index.tsx, packages/ui/src/ButtonGroup/index.tsx, packages/ui/src/Card/index.stories.tsx, packages/ui/src/Card/index.tsx, packages/ui/src/Colors.stories.tsx, packages/ui/src/FormField/index.stories.tsx, packages/ui/src/FormField/index.tsx, packages/ui/src/Input/index.stories.tsx, packages/ui/src/Input/index.tsx, packages/ui/src/PenumbraUIProvider/theme.ts, packages/ui/src/SegmentedControl/index.stories.tsx, packages/ui/src/SegmentedControl/index.tsx, packages/ui/src/Tabs/index.tsx, packages/ui/src/TextInput/index.stories.tsx, packages/ui/src/TextInput/index.tsx, packages/ui/src/hooks/useDisabled/index.test.tsx, packages/ui/src/hooks/useDisabled/index.ts, packages/ui/src/utils/ActionType.ts, packages/ui/src/utils/DisabledContext.ts, packages/ui/src/utils/button.ts
This is another PR where I was planning on making some new v2 pages, but then realized how many more components still had to be built before I could create the pages.
- Build out the `<Card />` component further with `<Card.Stack />` and `<Card.Section />` sub-components.
- Update a few theme values.
- Create `<FormField />` and `<TextInput />` components.
- Make it possible to disable an entire `<SegmentedControl />` (rather than just one of its options).
- Create a new `DisabledContext` and `useDisabled()` hook.
- This allows users to pass `disabled` to `<FormField />` without having to _also_ pass it to whatever input component is the `<FormField />`'s children. `<FormField />` then sets the disabled context to `true`, which is then read by the child input component.
- Extract …
=> Build out the `<FormField />` and `<TextInput />` components, and add other features in preparation for new v2 pages

packages/ui/src/Button/index.stories.tsx, packages/ui/src/Button/index.tsx, packages/ui/src/utils/button.ts
Previously, it was too tight around the icon, so we removed it entirely. That causes accessibility issues, though, so this PR adds it back and adds an offset so that it doesn't look cramped.
In situ ^ (see third row of the table)
This addresses @VanishMax 's bullet points 2-3 [here](https://github.com/penumbra-zone/web/pull/1607#discussion_r1709221930)
=> Fix icon adornment outline

packages/ui/src/Tabs/index.tsx
They're supposed to have rounded top left and right corners, but they were previously square. This PR fixes that.
See @VanishMax 's first bullet point [here](https://github.com/penumbra-zone/web/pull/1607#discussion_r1709221930)
=> Fix tabs' border radius on hover

packages/ui/README.md
This adds some sections about guiding principles, and then moves some of the existing guidelines to fit underneath those sections.
=> Add guiding principles to Penumbra UI README; reorganize a bit

.changeset/odd-cheetahs-help.md, apps/minifront/src/components/dashboard/assets-table/index.tsx
Closes #1593 
Sorts asset groups by account index on the dashboard of minifront in ascending order
=> fix(minifront): #1593: sort asset groups by account index

packages/ui/src/AccountSelector/AccountSelectorAddress.tsx, packages/ui/src/AccountSelector/IbcDepositToggle.tsx, packages/ui/src/AccountSelector/index.stories.tsx, packages/ui/src/AccountSelector/index.tsx, packages/ui/src/AccountSelector/useAccountSelector.ts, packages/ui/src/CopyToClipboardButton/index.stories.tsx, packages/ui/src/CopyToClipboardButton/index.tsx, packages/ui/src/Text/index.tsx, packages/ui/src/TextInput/index.stories.tsx, packages/ui/src/TextInput/index.test.tsx, packages/ui/src/TextInput/index.tsx, packages/ui/src/Toggle/index.stories.tsx, packages/ui/src/Toggle/index.test.tsx, packages/ui/src/Toggle/index.tsx, packages/ui/src/utils/button.ts, packages/ui/src/utils/typography.ts, packages/wasm/package.json
Creating more components for the v2 send/receive pages
- Create the v2 `<AccountSelector />` component
- Create a v2 `<Toggle />` component
- Note that this component is incomplete, as it doesn't yet visually support disabled and focused states. But those are coming soon in mockups.
- Add `disabled` prop to `<CopyToClipboardButton />`.
- Extract a `truncate` CSS mixin.
- Add support for `startAdornment` and `endAdornment` props in `<TextInput />`, as these are needed for `<AccountSelector />`. Also, add `max`/`min` prop support.
=> Create Toggle and AccountSelector components

.github/workflows/deploy-ui-preview-main.yml, .github/workflows/deploy-ui-preview-pr.yml, .github/workflows/deploy-ui-release.yml
this changes storybook CI to run proto codegen before trying to build storybooks.
changing `install` to not use the ui working directory has no effect, because `pnpm install` always runs at workspace level.
=> fix storybook CI

apps/minifront/src/components/v2/dashboard-layout/assets-card-title.tsx, apps/minifront/src/components/v2/dashboard-layout/assets-page/index.tsx, apps/minifront/src/components/v2/dashboard-layout/index.tsx, apps/minifront/src/components/v2/dashboard-layout/transactions-card-title.tsx, packages/ui/src/Card/Title.tsx, packages/ui/src/Card/index.tsx, packages/ui/src/CharacterTransition/index.stories.tsx, packages/ui/src/CharacterTransition/index.tsx, packages/ui/src/Table/index.tsx
This PR adds some animation features to Penumbra UI and the v2 minifront:
1. The Swap button animates in from the right on hover, in the assets table.
2. The `<CharacterTransition />` component animates individual characters when the text inside it changes. This is used for the card title of the transactions/assets pages:
3. The `<Card />` component animates its size changes as it accommodates new content.
4. The dashboard page titles now animate characters between each other.
=> Add animation features to v2 components

.changeset/fresh-hornets-hang.md, packages/ui/src/Button/index.tsx, packages/ui/src/PenumbraUIProvider/theme.ts, packages/ui/src/Popover/index.stories.tsx, packages/ui/src/Popover/index.test.tsx, packages/ui/src/Popover/index.tsx
Closes https://github.com/prax-wallet/web/issues/156
Implements Popover component but not the MenuItem that can be nested in the Popover – will do it in a separate PR.
Check it here: https://penumbra-ui-preview--pr1696-feat-prax-156-popov-940s7bhy.web.app/?path=/docs/ui-library-popover--docs
=> feat(ui): Popover

packages/ui/src/Density/index.tsx, packages/ui/src/hooks/useDensity/index.ts
Closes https://github.com/prax-wallet/web/issues/157
=> Add better docs for density

apps/minifront/package.json, apps/minifront/src/components/dashboard/assets-table/index.tsx, apps/minifront/src/fetchers/balances/index.ts, apps/minifront/src/state/shared.ts, apps/minifront/src/state/staking/index.test.ts, eslint.config.js, pnpm-lock.yaml
=> feat: loading spinner for assets table

apps/minifront/src/components/ibc/ibc-in/asset-utils.tsx, apps/minifront/src/components/ibc/ibc-in/assets-table.tsx, apps/minifront/src/components/ibc/ibc-in/ibc-in-request.tsx
If UM is not in the counterparty chain registry, it will not show an icon but display an identicon gradient (like other unidentified assets). This has caused some confusion for users that IBC to a chain and then can't find it. 
This PR adds an icon for ibc UM if they do not have an entry in the counterparty chain's registry. We already have the code that can identify UM from the IBC hash. This just looks for the `isPenumbra` field.
=> Display UM fallback if not in registry

apps/minifront/src/components/swap/auction-list/end-or-withdraw-all-button.tsx
Temporary mitigation for: https://github.com/penumbra-zone/web/issues/1702
A full 24 action auction batch takes ~2mins on my computer (m1 max). I wonder if this is a good setting just generally.
=> Lower batch limit (auctions)

.changeset/unlucky-cows-rush.md, apps/minifront/src/components/header/menu/provider.tsx, packages/client/src/manifest.ts
manifest access was slightly awkward in #1734 so this change improves the manifest type to provide more consistent access (fields no longer use index access, allow dot notation, don't optionalize existing required fields)
=> improve manifest type

apps/minifront/src/components/staking/account/use-staking-tokens-and-filter.ts
On other `reselect` usages, the conditional is opposite. It makes sense for the reselector to run when the data object has changed (not when remaining the same).
On testnet noticed this fixes a bug with navigating the staking page (arrows illuminated only when balances in another account). Not seen on mainnet as I believe the longer validator list causes re-renders (?). Not sure why.
https://github.com/penumbra-zone/web/blob/5616a7a6d54ebdc37127f398ec773edbc0e8ccf7/apps/minifront/src/components/dashboard/assets-table/index.tsx#L55
https://github.com/penumbra-zone/web/blob/5616a7a6d54ebdc37127f398ec773edbc0e8ccf7/apps/minifront/src/components/v2/dashboard-layout/assets-page/index.tsx#L39
=> Fix reselect conditional

.changeset/tame-llamas-remain.md, packages/ui/src/Dialog/index.tsx
This fixed the issues with z-index for v1 of minifront. However, it introduces even more problems for v2. We will have to tackle them separately in #1756
=> fix(ui): dialog content z-index

.changeset/young-mice-drive.md, apps/minifront/src/components/shared/selectors/asset-selector.tsx, apps/minifront/src/components/shared/selectors/balance-item.tsx, apps/minifront/src/components/shared/selectors/balance-selector.tsx, apps/minifront/src/fetchers/balances/by-priority-score.ts, apps/minifront/src/state/swap/helpers.ts
Closes #1120 
- Added the sorting "by priority score" for balances in the swap asset selector
- Fixed the paddings in the asset selectors
Might look a little unexpected first but it is designed for better UX – users will see their top-valued assets first
=> fix(minifront): #1120: sort the balances by priority score, fix styles

apps/minifront/src/components/ibc/ibc-in/asset-utils.test.ts, apps/minifront/src/components/ibc/ibc-in/asset-utils.tsx, packages/types/src/lo-hi.ts
When we are doing an IBC-in, if the user selects a number sufficiently big, the notation will convert to the exponential form: `1.12e+20`. This, however, is not a valid input as a coin amount for a ibc transfer message. It needs to be the full form.
This PR fixes this bug by overriding the default exponential config when performing the IBC-in to ensure it does not go to the exponential form. 
Related: https://github.com/noble-assets/noble/issues/404
=> Fix exponential string bug

.changeset/three-suns-complain.md, apps/minifront/src/components/shared/input-token.tsx, apps/minifront/src/components/shared/number-input/index.tsx, apps/minifront/src/components/swap/swap-form/token-input-error.tsx, apps/minifront/src/components/swap/swap-form/token-swap-input.tsx, apps/minifront/src/state/swap/index.ts
Closes #1675 
Renders the errors in case of insufficient funds or incorrect decimals in the balance selector in the swap page.
=> fix(minifront): #1675: decimals validation

eslint.config.js, package.json, pnpm-lock.yaml
react fast refresh is an acceleration to HMR, and it doesn't affect production code.
it is supported by vite and enabled by `@vitejs/plugin-react-swc`, so technically it is used in this repository. https://github.com/vitejs/vite-plugin-react-swc#consistent-components-exports
the lint rule was included in eslint config at some point, but its use was unclear. the eslint rules from the eslint plugin aren't actually enabled, so the eslint plugin is unused.
work in #1721 did not re-enable this rule that was provisionally disabled.
the rule should be enabled or deleted.
many components do not respect the requirements of react-fast-refresh, so enabling it would require many changes, including breaking changes to exports.
this PR deletes the eslint plugin and the disabled rule.
=> remove react-refresh lint

packages/types/src/staking.ts
Found on testnet. If a validator has zero staking commission, the array reduce will error out. Initializing w/ zero to prevent an error on this edge case.
=> Initialize reduce w/ zero

.changeset/hungry-yaks-carry.md, apps/minifront/package.json, packages/storage/package.json, packages/storage/src/indexed-db/indexed-db.test.ts, pnpm-lock.yaml
related: https://github.com/prax-wallet/registry/pull/89
=> Update to registry v11.2

.changeset/eight-hounds-compare.md, .changeset/late-peas-tap.md, .changeset/twenty-tomatoes-travel.md, packages/query/src/block-processor.ts, packages/query/src/helpers/identify-txs.test.ts, packages/query/src/helpers/identify-txs.ts, packages/storage/src/indexed-db/config.ts
Closes https://github.com/penumbra-zone/web/issues/1792
We should only be processing transactions that have nullifiers, spends, or swaps we recognize. At the moment, if there is a relevant tx in a block, we later process the entire block. This caused the original issue of an LP position misattributed to the owner when it was external.
Note, we need to version the DB given users may have in their db's LP NFTs and Auction NFTs that happened to be in the same block as another person's.
=> Only process relevant transactions

.changeset/afraid-coins-give.md, .changeset/clean-lions-carry.md, .changeset/old-emus-perform.md, .changeset/rotten-starfishes-watch.md, .changeset/smooth-trains-reflect.md, .changeset/wise-papayas-lay.md, apps/minifront/package.json, apps/minifront/src/components/tx-details/tx-viewer.tsx, packages/bech32m/src/penumbracompat1.ts, packages/protobuf/src/registry.ts, packages/protobuf/src/services/cosmos-ibc-core.ts, packages/protobuf/src/web.ts, packages/query/src/block-processor.ts, packages/query/src/helpers/identify-txs.test.ts, packages/query/src/helpers/identify-txs.ts, packages/storage/package.json, packages/storage/src/indexed-db/index.ts, packages/storage/src/indexed-db/stream.ts, packages/types/src/address.test.ts, packages/types/src/address.ts, packages/types/src/servers.ts, packages/ui/components/ui/tx/action-view.tsx, packages/ui/components/ui/tx/actions-views/ibc-relay.tsx, packages/ui/components/ui/tx/actions-views/isc20-withdrawal.tsx, packages/wasm/crate/src/keys.rs, packages/wasm/crate/src/view_server.rs, packages/wasm/crate/tests/test_keys.rs, packages/wasm/src/address.ts, packages/wasm/src/view-server.ts, pnpm-lock.yaml
At the moment, after a user makes a Ics20Transfer, Prax is not indexing the transaction for the IbcRelay action. This can cause confusion for users wondering the status of transaction.
This PR detects the relay action and, if the user is the recipient, adds it to the tx db.
=> Detect relevant IbcRelay actions

.changeset/good-penguins-battle.md, apps/minifront/src/components/syncing-dialog/index.tsx, apps/minifront/src/components/v2/header/status-popover.tsx, apps/minifront/src/components/v2/header/sync-bar.tsx, apps/minifront/src/state/status.ts, packages/ui/src/Button/index.tsx, packages/ui/src/Dialog/index.tsx, packages/ui/src/DropdownMenu/Content.tsx, packages/ui/src/Popover/index.tsx, packages/ui/src/Progress/index.tsx, packages/ui/src/utils/popover.ts
- Adds a temporary `zIndex` prop to the Dialog component. It is only needed for minifront v1 and must be removed when we stop supporting the v1.
- Improves the styles of the v2 sync bar and popover like this (notice the beautiful background):
=> fix(ui, minifront): v2 nav style fixes

packages/ui/components/ui/tx/actions-views/ibc-relay.tsx
A follow up from: https://github.com/penumbra-zone/web/pull/1805
Able to display IBC relay acknowledgements & timeouts in the transaction details page:
=> Ack & timeout relay msgs

.changeset/blue-onions-return.md, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/planner.rs, packages/wasm/crate/src/storage.rs, packages/wasm/crate/tests/test_planner_send_max.rs
references https://github.com/penumbra-zone/web/issues/1660, and partially references https://github.com/penumbra-zone/web/issues/692. 
Implements wasm bindgen unit tests for sanity-checking the critical logic paths and safety checks for the send max feature.
https://github.com/penumbra-zone/web/pull/1698 to follow.
=> wasm: handle spend transaction planner requests in planner

.changeset/cold-mails-sleep.md, packages/ui/src/AssetSelector/ListItem.tsx, packages/ui/src/AssetSelector/index.tsx, packages/ui/src/AssetSelector/shared/groupAndSort.ts, packages/ui/src/AssetSelector/shared/helpers.ts
Asset selector was failing to display real data because of mis-version of protobufs – somehow `isMetadata` was returning `false` for normal metadata in the DEX. I updated these functions and improved filtering of assets
=> fix(ui): asset selector fixes

apps/minifront/vite.config.ts, package.json, pnpm-lock.yaml
Removing the tooling that makes dev mode `https://localhost` and just uses `http`.
No longer necessary after prax update removing the requirement (for localhost only).
=> localhost SSL no longer required

.changeset/tough-mayflies-collect.md, packages/query/src/block-processor.ts
Previously, the loop was using a version of `updatePriceForValidatorDelegationToken()` that made a request for metadata from the node. This caused rate-limiting issues that a throttle was put into place to slow down the requests: https://github.com/penumbra-zone/web/pull/1392.
Now that delegation metadata is generated locally (versus a request) with https://github.com/penumbra-zone/web/issues/1189, we can get rid of the throttle. 
This will also be helpful to have the speedup so the staking page is immediately populated on a fresh sync and doesn't have to wait for +1 minute to get all validator infos.
=> Remove validator info throttler

.changeset/thick-parrots-lie.md, packages/ui/src/ValueViewComponent/index.tsx
Fixes #1806 
Now it truncates and adds a title on hover
=> fix(ui): #1806: add truncation to `ValueViewComponent`

.changeset/spicy-terms-reflect.md, packages/query/src/block-processor.ts, packages/storage/src/indexed-db/updater.ts
references https://github.com/penumbra-zone/web/issues/1814
collectively yields **~8%** syncing improvement. 
Profiling indicates that the block processor performs substantially more database reads than writes. The most resource-intensive DB operations are "saveScanResult," "identifyNewAssets," and "resolveNullifiers," which account for the majority of disk I/O operations.
Currently, storage operations are executed sequentially (ie. saving transactions, metadata, etc.) in indexDB. Storage R/W blocks sync since each storage operation has an associated `await`, causing each to wait for the previous one to finish before continuing.
Those operations were refactored to use `Promise.all()`, ensuring the block processor isn't _artificially_ blocked on each `await` call. This means a concurrent …
=> database batching 

packages/ui/components/ui/block-sync-status/block-sync-status.tsx
Simply adds a "Reload" button next to the error message in sync status.
Relates to https://github.com/prax-wallet/prax/pull/217 as it gives users a sense that the error might be recovered by the refresh
=> fix(ui): add refresh button to block sync status

.changeset/proud-ducks-marry.md, packages/ui/src/Dialog/RadioItem.tsx
Before:
https://github.com/user-attachments/assets/27af6cf7-87de-4a12-b56c-683ea6ced49b
After:
https://github.com/user-attachments/assets/5248f3db-83f1-48ce-b7ac-9c8d06c5b980
When a user clicks on the item, the `onMouseDown` event fires, the unmounting of the component prevents the `onClick` from firing.
=> Fix asset selector onchange event

.changeset/grumpy-carpets-kiss.md, apps/minifront/src/fetchers/assets.ts, packages/services/src/view-service/util/asset-priority-score.ts
As part of https://github.com/penumbra-zone/web/issues/1829
=> Sort assets by priority score

.changeset/seven-coins-jog.md, packages/protobuf/package.json
Related to: https://github.com/penumbra-zone/penumbra/pull/4900
=> Update protos to latest definitions (with badges on Metadata)

.changeset/mean-steaks-wave.md, packages/getters/package.json, packages/ui/package.json, packages/ui/vite.config.ts, pnpm-lock.yaml
Relates to https://github.com/penumbra-zone/dex-explorer/issues/115 and https://github.com/penumbra-zone/dex-explorer/pull/114
This PR improves the `dev:pack` command of the UI package. Before this, it would build the lib with Vite but not pack the tarball, or pack it in the wrong timing, making the behavior unexpected. I updated the pack command to use `execa` lib.
=> fix(ui): improve UI lib hot reloading

.changeset/shy-dogs-draw.md, packages/ui/package.json, packages/ui/vite.config.ts
Currently we can't access theme and lib/toast within the dex-explorer. This should fix that.
=> Add theme & lib/toast UI exports

.changeset/quiet-cars-add.md, packages/ui/src/AddressViewComponent/index.tsx, packages/ui/src/Button/index.tsx, packages/ui/src/DropdownMenu/Item.tsx, packages/ui/src/utils/menuItem.ts
Some changes here and there to fix or improve components to unblock the following design
=> fix(ui): fix styles for subaccount selector

.changeset/forty-pumpkins-eat.md, packages/ui/src/Toast/open.ts
Add ReactNode to Toast description prop type.
Needed to provide a progress bar to the transaction toast.
=> Add ReactNode to Toast description prop type

.changeset/orange-boxes-suffer.md, packages/ui/package.json, packages/ui/src/PenumbraUIProvider/index.tsx, packages/ui/vite.config.ts
- Removed deprecated toast exports
- theme is now exported from PenumbraUIProvider/index.tsx
- added utils/typography to exports
=> Update ui exports

scripts/link-externally.js
Currently pnpm linking does not work because the exports inside the package.json files of the packages refer to the src files:
```
"exports": {
".": "./src/index.ts",
"./*": "./src/*.ts"
},
```
This script can temporarily set the exports to the value of the `publishConfig.exports`, so that the exports will point to the dist folder.
It would work like this:
```
// inside penumbra-zone/web
node scripts/link-externally.js enable
cd packages/ui && dev:pack
// inside dex-explorer
pnpm link ../penumbra-zone/web/packages/ui
// to revert:
node scripts/link-externally.js disable
```
> PS: Possible improvement would be to directly build a monorepo's package within the dex-explorer as part of the build pipeline.
=> Script to enable `pnpm link`

.changeset/spicy-rings-happen.md, packages/ui/.storybook/preview.tsx, packages/ui/package.json, packages/ui/src/Density/index.tsx, packages/ui/src/Tabs/index.tsx, packages/ui/src/Text/index.tsx, packages/ui/src/Text/types.ts, packages/ui/src/Toggle/index.stories.tsx, packages/ui/src/Toggle/index.tsx, packages/ui/src/theme/theme.ts, packages/ui/src/utils/density.ts, packages/ui/src/utils/typography.ts, pnpm-lock.yaml
Changeset:
- Add Toggle UI component – adapt it from `ui-deprecated`
- Add `medium` density – new density type introduced in the DEX Figma, implemented in at least Tabs component
- Add `xxs` Text style – new typography type with 11px font-size
- Improve the styles of `Tabs` component – add support for `medium` density
Check here: https://penumbra-ui-preview--pr1913-fix-tab-styles-tf62cbwe.web.app/
=> feat(ui): toggle component and more

.changeset/curly-squids-learn.md, .changeset/loud-beers-yawn.md, apps/minifront/package.json, apps/minifront/src/components/swap/swap-form/simulate-swap-result/traces/trace/price.tsx, packages/types/package.json, packages/types/src/amount.ts, packages/types/src/round.test.ts, packages/types/src/round.ts, packages/types/src/shortify.test.ts, packages/types/src/shortify.ts, packages/ui/src/ValueView/index.tsx, pnpm-lock.yaml
Updating `ValueViewComponent` to support displaying for this view on the dex explorer:
At the moment those display raw numbers, but given the metadata of the assets, we need them to be `ValueViewComponent` to handle the display exponents.
=> Shortened amount props for ValueViewComponent

.changeset/rude-fireants-pump.md, apps/minifront/src/components/swap/swap-form/simulate-swap-result/traces/index.tsx, apps/minifront/src/components/swap/swap-form/simulate-swap-result/traces/trace/index.tsx, apps/minifront/src/components/swap/swap-form/simulate-swap.tsx
references https://github.com/penumbra-zone/web/issues/1919
https://github.com/user-attachments/assets/bd5707f2-df2e-4929-971f-ea36d6650c7b
=> automatically perform swap estimation on user input

.changeset/dull-bikes-reflect.md, packages/ui/src/ValueView/index.tsx
the V2 `ValueViewComponent` needs a `showValue` prop. For instance the [prepaid claim fee](https://github.com/penumbra-zone/web/issues/889) amount can't be shown in the public view and will need to set the prop to `false`.
=> views: prop for optionally displaying value on ValueViewComponent

.changeset/two-hotels-lie.md, packages/ui/.storybook/preview.tsx, packages/ui/src/Button/index.tsx, packages/ui/src/Density/index.tsx, packages/ui/src/Tabs/index.tsx, packages/ui/src/ValueView/index.tsx, packages/ui/src/theme/theme.ts, packages/ui/src/utils/action-type.ts, packages/ui/src/utils/button.ts, packages/ui/src/utils/color.ts, packages/ui/src/utils/density.ts, packages/ui/src/utils/menu-item.ts, packages/ui/src/utils/popover.ts, packages/ui/src/utils/typography.ts
This PR aligns basic UI components with the latest designs:
- Sync colors and gradients
- Remove `medium` density and add `slim` density, while replacing `medium` for `compact`
- Update `Button` component to support all existing variants
Check here: https://penumbra-ui-preview--pr1939-feat-asset-selector-bd416kcb.web.app/?path=/docs/ui-library-button--docs
=> feat(ui): updates for button, density and colors

.changeset/tasty-pears-knock.md, packages/client/src/client.ts
references https://github.com/penumbra-zone/dex-explorer/issues/154
this is a subtle wallet connection bug. Initially, I thought the culprit was related to mobx's observer HOC, where the connection state wasn't properly being observed. Upon digging deeper, I narrowed in on the client connection implementation, specifically this [no-op](https://github.com/penumbra-zone/web/blob/main/packages/client/src/client.ts#L151-L153) comment. If the connection is set, indicating an active connection, the nullish coalescing operator prevents initializing a new connection. Debugging the connection state revealed that this no-op behavior becomes problematic in a specific (yet common) case: the connection is _set_, but the underlying connection is broken. This could be from either the connection timing …
=> client: fix connection persistence bug

.changeset/real-goats-cover.md, packages/ui/src/AddressView/index.stories.tsx, packages/ui/src/AddressView/index.tsx, packages/ui/src/Text/index.tsx, packages/ui/src/utils/bufs/address-view.ts, packages/ui/src/utils/bufs/balances-responses.ts
aligns `Address View` V2 UI component with the latest figma designs – review the storybook preview link. Some pointers would be helpful cc @VanishMax
=> feat(ui): updates for address view 

apps/minifront/src/components/ibc/deposit-skip/index.tsx
At the moment, we are defaulting to usdc in (not currently supported)
=> Update skip pre-selected assets

.changeset/brown-suns-tickle.md, packages/types/src/pnum.test.ts, packages/types/src/pnum.ts, scripts/link-externally.js, scripts/link.js, scripts/unlink.js
- `input instanceof ValueView` didn't work apparently.
=> Fix pnum parsing ValueView

.changeset/pink-rabbits-fry.md, apps/minifront/src/components/tx-details/tx-viewer.tsx, packages/ui-deprecated/components/ui/tx/memo-view.tsx
reorders the transaction view visibility settings in https://github.com/penumbra-zone/web/issues/1873 and addresses the truncated memo field flagged by the beta reviewers.
-----------------------------
_before_
_after_
=> minifront: transaction view rendering 

.changeset/strange-nails-perform.md, packages/ui/src/Tooltip/tooltip.tsx
- Update Tooltip message prop to support ReactNode
=> Update Tooltip message prop to support ReactNode

packages/wasm/crate/Cargo.toml
Recently, CI jobs started failing on the `rust:lint` step. One suitable workaround was to ignore the questionable lints
via Cargo.toml:
```
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
```
This seems to resolve. I also tried bumping the `wasm-bindgen` dep to 0.2.100, which didn't resolve on its own. See related discussion in [0].
[0] https://github.com/rustwasm/wasm-bindgen/issues/4283
An example failing job can be see here: https://github.com/penumbra-zone/web/actions/runs/12819463583/job/35747206149?pr=1980
=> ci: fix rust:lint job

docs/adrs/003-action-views.md
This pull request resolves a typo in the `003-action-views.md` documentation file. The word **"similiar"** has been corrected to **"similar"** in the following context:
> `DutchAuctionDescription`: <u>**_opaque_**</u> field since the amounts and asset types can be public **similiar** to swaps.
> `DutchAuctionDescription`: <u>**_opaque_**</u> field since the amounts and asset types can be public **similar** to swaps.
- Corrected the typo to improve the clarity and professionalism of the document.
- **Commit Hash:** _<commit_hash_here>_
- **Author:** @VitalikBerashvili
- **Date:** January 20, 2025
- **Branch:** `Fix-typo`
- **Base Branch:** `main`
- **Status:** Able to merge.
This minor change enhances the
=> Typo fix 003-action-views.md

.changeset/tender-bobcats-invite.md, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml
update wasm deps to latest [tagged v0.81.3 release
](https://github.com/penumbra-zone/penumbra/releases/tag/v0.81.3)
=> wasm: bump deps to v0.81.3

.changeset/spotty-emus-notice.md, packages/ui/src/theme/font-sizes.css
Closes https://github.com/penumbra-zone/dex-explorer/issues/307
This PR simply comments out the XL screen size responsiveness. 
Sam and Artur made UI typography styles responsive, so, for example, a `text-textBase` class is 0.875rem (14px) on mobile and tablet screens, 1rem (16px) on desktop and large screens, 1.125rem (18px) on XL screens.
This feature was implemented in https://github.com/penumbra-zone/web/pull/1978 to meet the v2 designs requirements. This lead to mobile and tablet screens become pixel-perfect, better-looking for users of the DEX. However, DEX designs do not support XL text responsiveness as the components are extremely dense and need smaller text styles.
For text style reference, see the screenshots in https://github.com/penumbra-zone/web/pull/1978
=> fix(ui): stop XL font responsiveness

docs/README.md
This pull request fixes a minor typo in the `README.md` file. The word **`manger`** has been corrected to **`manager`**.
- Fixed the typo: `package manger` → `package manager`.
=> fix typo README.md

docs/adrs/003-action-views.md
Fix Typo in 003-action-views.md  
---
This pull request fixes a typo in the `003-action-views.md` file located in the `docs/adrs/` directory.
- **Original:** `amonst`  
- **Corrected:** `amongst`  
The typo was found in the explanation of the `SwapPlaintext` field.
---
---
If further adjustments or reviews are needed, feel free to comment! 🚀
=> Typo 003-action-views.md

packages/ui-deprecated/components/ui/block-sync-status/block-sync-status.tsx
Previously, syncing displayed varying illegible error states (eg. `ConnectError` and `DataCloneError`). These can be caused by unstable internet connections, locking the wallet which [resets the service worker](https://github.com/prax-wallet/prax/pull/62/files#diff-649ac305e4633910768bd425c904f22bf9fe627e30b0762fb18d19bbe8fa0d52R74-R78) for security, etc. The error handling has been improved to provide a clearer error message and programmatically reload the page with `window.location.reload()` every **5s** when a sync error occurs. 
_update:_ because of the investigation in https://github.com/penumbra-zone/web/issues/1885#issuecomment-2614630687, this PR simply just makes the error messaging nicer rather than doing any auto page reloading. 
references …
=> web: readable sync error message

.changeset/curvy-buses-doubt.md, packages/services/src/view-service/latest-swaps.test.ts, packages/services/src/view-service/latest-swaps.ts
After discussing Prax <–> Pindexer connection with protocol devs, it turned out that Pindexer stores swap execution data based on the time when the swap happened, but `latestSwaps` method of the ViewService was returning the height when user claimed the swap. This PR fixes the issue, so that `latestSwaps` can be easily merged with Pindexer data
=> fix: latest swaps

.changeset/sixty-fishes-travel.md, packages/services/src/test-utils.ts, packages/services/src/view-service/transaction-info.test.ts, packages/services/src/view-service/transaction-info.ts, packages/storage/src/indexed-db/config.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
Previously, transactions were populating in a random order. To address this, we load transactions in order of block height and the [storage](https://github.com/penumbra-zone/web/blob/main/packages/storage/src/indexed-db/index.ts) package has been updated to:
- extend the idb schema to _Index_ the `TRANSACTIONS` object store by height,
- introduce a new `TRANSACTION_INFO` object store to save the transaction perspectives (TxP) and transaction views (TxV)
- introduce new `saveTransactionInfo` and `getTransactionInfo` storage methods
We lazily compute and store TxP + TxV from expensive calls like [generateTransactionInfo](https://github.com/penumbra-zone/web/blob/main/packages/services/src/view-service/transaction-info.ts#L23) rather than redundantly recalculating them every page reload. …
=> transaction table: index store by height 

.changeset/three-lies-tickle.md, apps/minifront/package.json, packages/storage/package.json, pnpm-lock.yaml
bumps registry to latest tagged release, `v12.4.0`
https://github.com/prax-wallet/registry/releases/tag/v12.4.0
=> registry: bump deps to v12.4.0

packages/protobuf/package.json, packages/protobuf/src/services/penumbra-core.ts, packages/protobuf/src/web.ts, packages/services/src/view-service/index.ts, packages/services/src/view-service/lqt-voting-notes.ts, packages/services/src/view-service/tournament-votes.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts, packages/types/src/querier.ts, packages/ui-deprecated/components/ui/tx/action-view.tsx, packages/wasm/crate/src/lib.rs, packages/wasm/crate/src/voting.rs, packages/wasm/src/voting.ts
WIP: `LqtVotingNotes` and `TournamentVotes` view service rpc impls.
- leverages existing IndexedDB storage method `getNotesForVoting` to retrieve eligible voting notes.
- exposes an equivalent utility storage method in wasm. 
- extends queriers to the funding service, enabling nullifier checks for voting eligibility.
references https://github.com/penumbra-zone/web/issues/2027 and https://github.com/penumbra-zone/web/issues/2028 and https://github.com/penumbra-zone/penumbra/pull/5080
pairs with https://github.com/prax-wallet/prax/pull/290
=> view service: LQT scaffolding 

.changeset/stale-walls-bow.md, packages/ui/src/Tabs/index.tsx
Part of https://github.com/penumbra-zone/dex-explorer/issues/357
This makes it possible to change the tabs to an `"a"` or next `Link` with a provided `href` prop.
Related PR: https://github.com/penumbra-zone/dex-explorer/pull/360
=> Make tabs extensible

.changeset/six-colts-sip.md, packages/ui/src/Tabs/index.tsx
A follow up for https://github.com/penumbra-zone/web/pull/2039 to fix the lint error related to the tabProps type.
=> Change tabProps prop type

scripts/build-for-deployment.sh
I ran `shellcheck` on the script used to export a bundled minifront, suitable for inclusion in `pd`. These are small changes intended to make the script more resilient, e.g. failing fast and handling directories with spaces in the name.
Prepared while working on
https://github.com/penumbra-zone/penumbra/issues/5089.
Refs https://github.com/penumbra-zone/penumbra/issues/5089.
No app-code changes, only a script to export artifacts is changed. Still, I did consume the results of this modified script, as part of testing for https://github.com/penumbra-zone/penumbra/issues/5089.
=> lint: shellcheck on minifront bundled asset script

package.json, packages/mock-chrome/package.json, packages/mock-chrome/src/chrome.d.ts, packages/mock-chrome/src/event.mock.ts, packages/mock-chrome/src/event.test.ts, packages/mock-chrome/src/runtime/channel.fixtures.ts, packages/mock-chrome/src/runtime/channel.mock.ts, packages/mock-chrome/src/runtime/channel.test.ts, packages/mock-chrome/src/runtime/connect.api.ts, packages/mock-chrome/tsconfig.json, packages/mock-chrome/vitest.config.ts, packages/transport-chrome/package.json, packages/transport-chrome/src/global.d.ts, packages/transport-chrome/src/session-client.test.ts, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/src/session-manager.test.ts, packages/transport-chrome/src/util/test-utils.ts, packages/transport-chrome/src/with-dom.test.ts, packages/transport-chrome/vitest.config.ts, pnpm-lock.yaml
implement mocks for chrome runtime messaging in a new package. this is an alternative approach to implementing a new testing harness with puppeteer and dedicated dapp/ext fixtures
use mocks to test transport-chrome. ~~session client tests are mostly written, session manager tests are less complete. after unit tests of session-client and session-manager are implemented, the mocks could be used to test the full transport and connectrpc stack.~~
many tests written.
this will be ordered before #2018, then #2034 will break down into two sets of changes: an incremental improvement PR, and then the lifecycle changes.
testing will help ensure the series of changes in connection-lifecycle-branch aren't changing unexpected behavior/functionality. a complete solution testing real interaction with …
=> mock chrome runtime messaging and test transport-chrome

.changeset/violet-coats-remember.md, packages/transport-chrome/src/session-client.test.ts, packages/transport-chrome/src/session-client.ts
`CRSessionClient` of `@penumbra-zone/transport-dom` no longer retains a `MessagePort` and no longer uses a singleton pattern.
fixes #1736 
rebased onto #2040 
Tested in combination with other work, not yet tested alone.
=> don't retain port in `CRSessionClient`, remove singleton pattern

packages/transport-chrome/src/session-client.test.ts, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/src/session-manager.test.ts, packages/transport-chrome/src/session-manager.ts
splitting the difference from #2018  towards #2034
contains all changes except reconnect, mostly focusing on reliability.
- typed senders make it harder to emit a malformed message
- incoming message checking is more thorough
- poisons transport in fewer cases
- matches errors up with relevant requests in more cases
- fewer data clone failures #2014
=> incremental transport-chrome session improvements

packages/transport-chrome/src/session-client.test.ts, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/src/session-manager.test.ts, packages/transport-chrome/src/session-manager.ts
session-client will now automatically request to reconnect when disconnected.
to support this, session-manager now uses a callback parameter to validate connection requests, instead of depending on external management of port injection.
considerations:
- reconnect won't automatically retry individual failed requests
- reconnect can't prevent in-flight requests from being interrupted by a disconnect
- reconnect can't prevent a page from persistently using an actually-dead transport
discovered issues:
- permissions check must be async, so listener attachment became async. this causes a race condition under which early requests may arrive before a listener is attached.
potential issues:
- some clients may be using structural typing or string matching to detect errors. continuing to …
=> session client reconnect

packages/wasm/crate/rust-toolchain.toml
fixes https://github.com/penumbra-zone/web/issues/2076
by matching rust-toolchain.toml in core https://github.com/penumbra-zone/penumbra/blob/main/rust-toolchain.toml
=> use rust-toolchain.toml

docs/README.md, docs/adrs/004-privacy-invariants.md, docs/extension-services.md, docs/guiding-principles.md
- `reuseable` to `reusable`.
- `extranous` to `extraneous` and `possiblity` to `possibility`.
- `re-useable` to `reusable`.
- `re-use` to `reuse`.
=> Fix spelling errors across Documentation Files

.changeset/empty-ads-repeat.md, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/vitest.config.ts, packages/transport-dom/src/create.ts, packages/transport-dom/vitest.config.ts
Moves client streaming request support to a `globalThis.__DEV__` conditional, which will be codesplit by bundlers or skipped in execution unless defined.
=> disable client-streaming in transport-dom outside of dev mode

.changeset/curly-icons-sniff.md, .changeset/khaki-pandas-worry.md, packages/transport-chrome/src/with-dom.test.ts, packages/transport-dom/src/create.test.ts, packages/transport-dom/src/create.ts, packages/transport-dom/src/messages.ts, packages/transport-dom/src/util.ts, packages/transport-dom/src/util/normalize-header.ts
Restrict the use of `HeadersInit` in a `TransportEvent` or `TransportError` to only permit jsonifiable members.
Serialize timeout into the request header as in typical connectrpc.
Technically, an exported type becomes narrower, but the now-omitted member was invalid, and no external API has changed its accepted input/output formats.
=> correctly serialize headers and timeout

.changeset/popular-keys-look.md, packages/transport-chrome/src/with-dom.test.ts, packages/transport-dom/src/create.test.ts, packages/transport-dom/src/create.ts
Streaming responses now use the per-request or transport default timeout configuration to abort a stalled stream.
=> time out stalled streams, emit stream abort events

.changeset/seven-dots-change.md, packages/ui-deprecated/components/ui/block-sync-status/block-sync-status.tsx
Presently, the header progress bar will display a 'Genesis sync' status when it's waiting for status data. This change will cause the header progress bar to only display a 'Genesis sync' status when the synced height is zero/undefined, but a remote block height is known.
https://github.com/penumbra-zone/web/issues/2064
=> minifront: detect genesis sync state more accurately

.changeset/friendly-mugs-push.md, apps/minifront/src/fetchers/status.ts
reverts https://github.com/penumbra-zone/web/pull/2080/commits/7fa28d100c8c6be9c92c24a643e33be0fa0d9955
I think the timeout may be too long — I can't consistently replicate the behavior I was seeing in https://github.com/penumbra-zone/web/pull/2080#discussion_r1974112717 which the user should be actively seeing while the status stream attempts to self-correct.
=> minifront: reduce status stream timeout

scripts/build-for-deployment.sh
As long as the zip files are exported from the same git commit, the resulting archives should be byte-for-byte identical. Having fully reproducible builds will require comprehensive dependency pinning, e.g. via nix flake or similar, to ensure that the wasm artifacts are built identically, but for now, simply clobbering the timestamps of the exported asset files provides decent reproducibility.
No request in an issue, simply making opportunistic improvements, as with #2056. Was motivated to try this while updating the bundled assets in https://github.com/penumbra-zone/penumbra/pull/5119. 
^ N/A, as this script only makes changes to build scripts, not to app code.
=> build: make zip file exports deterministic

.changeset/chilly-pandas-grow.md, apps/minifront/package.json, apps/minifront/src/state/ibc-in/index.tsx, apps/minifront/src/state/ibc-out.ts, packages/ui-deprecated/components/ui/tx/actions-views/isc20-withdrawal.tsx, pnpm-lock.yaml
reverts t-addr support in mininfront ibc components and ui lib
after https://github.com/skip-mev/skip-go/pull/873 lands in next skip release, we can bump the deps accordingly.
references https://github.com/penumbra-zone/web/issues/2023 and pairs with https://github.com/prax-wallet/prax/pull/295
=> web: minimal t-addr reversion 

.changeset/forty-buckets-know.md, packages/transport-chrome/docs/sessions.md, packages/transport-chrome/package.json, packages/transport-chrome/src/channel-names.ts, packages/transport-chrome/src/session-client.test.ts, packages/transport-chrome/src/session-client.ts, packages/transport-chrome/src/session-manager.test.ts, packages/transport-chrome/src/session-manager.ts, packages/transport-chrome/src/session.ts, packages/transport-chrome/src/util/chrome-errors.ts, packages/transport-chrome/src/util/rpc-errors.ts, packages/transport-chrome/src/util/senders.ts, pnpm-lock.yaml
- `CRSessionManager` now focuses primarily on connection lifecycles and sender validation
- Sender validation is now a callback parameter instead of built-in
- `CRSessionManager.killOrigin` returns the set of affected senders for additional cleanup
- Created manager-owned `CRSession` class to encapsulate individual client sessions
- Sync session init supports async validation while avoiding dropped messages
- Added `CRSessionClient.end()` static method to terminate all clients in document
- Improved error handling including context loss
- Improved lifecycle including client reconnect
- Added session lifecycle documentation in `docs/sessions.md`
- Detailed initialization, communication flows, and termination scenarios
=> Session improvements

.changeset/soft-wasps-kick.md, apps/minifront/package.json, pnpm-lock.yaml
bumps skip-go version dep to [3.4.1](https://www.npmjs.com/package/@skip-go/widget) following https://github.com/skip-mev/skip-go/pull/873
--------------
N/A
=> skip-go widget version bump

.changeset/wicked-rings-grow.md, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml
bumps wasm deps to the latest tagged release, `v2.0.0-alpha.4`
=> bump wasm deps

apps/veil/src/pages/tournament/api/use-previous-epochs.ts, apps/veil/src/pages/tournament/api/use-voting-rewards.ts, apps/veil/src/pages/tournament/ui/page.tsx, apps/veil/src/pages/tournament/ui/previous-epochs.tsx, apps/veil/src/pages/tournament/ui/vote.tsx
Closes #2119
Previous epochs table with dummy data. For connected to wallet state shows 5 columns, for disconnected – 3 columns. Navigates user to the epoch detail page.
=> feat(veil): #2119: previous epochs

.changeset/eighty-areas-fry.md, apps/minifront/package.json, apps/veil/src/entities/transaction/api/plan-build-broadcast.tsx, apps/veil/src/pages/inspect/tx/ui/tx-viewer.tsx, apps/veil/src/pages/portfolio/api/use-transactions.ts, packages/ui-deprecated/package.json, packages/ui-deprecated/src/Toast/provider.tsx, packages/ui/package.json, packages/ui/src/ActionView/actions/output.tsx, packages/ui/src/ActionView/actions/spend.tsx, packages/ui/src/Toast/provider.tsx, pnpm-lock.yaml
Closes #2142 
Closes #2141 
Closes #2140 
Fixes:
- Updated Sonner to v2.0.3 and tested that it doesn't break nor Veil, nor Minifront
- Added a link to the inspect page in transaction success toast
- Truncated addresses correctly in action and transaction views
- Reversed transaction order in Veil portfolio page
=> fix(ui, veil): #2141: transaction-related bug fixes

apps/veil/src/pages/trade/ui/chart.tsx
Closes #2153 
The default Trading View behavior without using `.fitContent()` appears to be just what we need. Time frames like '1m', '15m', '1h', '4h', '1d' look very good with consistent bar width. The '1w' and '1mo` time frames lack data a little, but generally good to look consistent.
=> fix(veil): #2153: consistent x axis

packages/client/src/client.ts
after https://github.com/penumbra-zone/web/pull/2099, more carefully track client connection status. This is more important now that client connection is more reliable.
marked ready for review so you can get eyes on it, but this probably needs some thorough testing.
=> Client connection status

apps/minifront/src/components/ibc/deposit-skip/index.tsx
_explicitly_ disables analytics rather than relying on the default behavior, even though skip-go appears to not enable analytics by default
https://github.com/penumbra-zone/web/issues/2212
=> skip widget config

.changeset/stupid-groups-bet.md, packages/types/src/swap.ts, packages/ui/src/ActionView/swap/swap.tsx
Fixes the issue with certain swap ActionViews that don't have metadata inside them, usually in opaque views.
=> fix(types, ui): better swap getters

.changeset/forty-laws-refuse.md, .changeset/slow-wings-glow.md, apps/minifront/src/state/staking/assemble-undelegate-claim-request.ts, apps/minifront/src/state/staking/index.ts, packages/types/src/assets.test.ts, packages/types/src/assets.ts
Port of pcli fix https://github.com/penumbra-zone/penumbra/pull/5084 to the minifront planning UI
>This fixes an edge-case in pcli tx undelegate-claim that would compute an invalid penalty range for dated delegation tokens.
>Instead of using the current epoch as the end of the penalty range, we compute a more precise bound using the block delay chain parameter. This fixes processing old delegation tokens bound to a validator that transitioned in and out of penalty states.
https://github.com/penumbra-zone/penumbra/pull/5084
=> fix: unbonding penalty calculation

.changeset/eleven-corners-write.md, packages/perspective/src/plan/view-action-plan.ts
Prax wasn't rendering LQT Action View in approval dialog. That's how it renders it after the changes:
=> fix(perspective): lqt plan to action view

.changeset/happy-sites-sink.md, packages/protobuf/package.json, packages/services/src/view-service/lqt-voting-notes.test.ts, packages/services/src/view-service/lqt-voting-notes.ts
pairs with https://github.com/penumbra-zone/penumbra/pull/5158 – a more amenable way for consumers of the view service impl to determine whether LQT notes have already been used to vote in the current epoch.
requires associated proto changes before merging
N/A
=> LQT: generalize view service response

apps/veil/src/pages/trade/ui/order-form/order-form-limit.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-market.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-range-liquidity.tsx, apps/veil/src/pages/trade/ui/order-form/store/OrderFormStore.ts
Implements https://github.com/penumbra-zone/web/issues/2163 and https://github.com/penumbra-zone/web/issues/2164
Sets the max decimals of an input to the assets exponent
Replacement of https://github.com/penumbra-zone/web/pull/2223
Depends on https://github.com/penumbra-zone/web/pull/2237
=> Order form: Set max decimals of input to exponent

.changeset/sharp-doors-remain.md, packages/getters/src/swap-view.ts, packages/types/src/pnum.ts, packages/types/src/swap.ts, packages/ui/src/ActionView/actions/ics-20-withdrawal.tsx, packages/ui/src/ActionView/actions/liquidity-tournament-vote.tsx, packages/ui/src/ActionView/position/position-close.tsx, packages/ui/src/ActionView/position/position-open.tsx, packages/ui/src/ActionView/position/position-reward-claim.tsx, packages/ui/src/ActionView/position/position-withdraw.tsx, packages/ui/src/ActionView/swap/swap-claim.tsx, packages/ui/src/ActionView/swap/swap.tsx
The bug is specific to opaque swap views, it was following us from the first versions of the ActionView UI component.
Before (notice how the amounts are duplicated for both input and output):
After:
=> fix: action view swap bugs

apps/minifront/src/utils/commit-info-vite-plugin.ts
I did some research and found that the "GIT_ORIGIN_URL" variable gets its value from "execSync('git remote get-url origin')". This works fine when the repo is cloned using HTTPS, but if it's cloned via SSH, it returns something like [git@github.com](mailto:git@github.com):username/reponame. When this SSH URL is used in an tag, the browser treats it as a relative URL, which is why it gets prefixed with "http://localhost/:.."
To fix this, I detect the fetched URL, and if it is in SSH format, I convert it to the corresponding HTTPS format.
Closes #2057 
=> feat: minifront_version_in_footer_is_a_broken_link

.github/workflows/deploy-ui-preview-main.yml, .github/workflows/deploy-ui-release.yml
use node setup action in deploy-ui workflows, to match others. these workflows broke recently due to new engine requirements in veil.
should probably centralize tool-versions with something like mise.
https://github.com/penumbra-zone/web/actions/runs/14231070370/job/39914124285
=> use node setup action in workflows

.changeset/silver-cows-throw.md, packages/services/src/stake-service/index.ts, packages/services/src/stake-service/validator-status.ts
stake service validator status method implementation somehow dropped from https://github.com/penumbra-zone/web/pull/2201 🙃
https://github.com/penumbra-zone/web/issues/2236
=> validator status method implementation

packages/ui/src/ActionView/actions/liquidity-tournament-vote.tsx
**Description:**
This PR updates the variable naming in the liquidity tournament vote action to maintain consistency:
- Renames `receipient` to `recipient` to fix typo
- Updates variable references throughout the file to match the corrected naming
- Maintains the same functionality while improving code clarity
The changes affect the address comparison logic in the tournament vote handling code.
=> Fix recipient variable naming in liquidity-tournament-vote.tsx

.github/actions/setup-nix/action.yml, .github/workflows/compile-wasm.yml, .github/workflows/turbo-ci.yml, .prettierignore, flake.lock, flake.nix, justfile
We want a single declaration of tooling dependencies required to work on
the apps in the web monorepo. Extending the nix flake so that it's used
in CI, as well, ensuring that CI failures are easily replicable.
There's a single omission, for the sake of velocity: I haven't ported
the playwright tests to use the nix env. That'll take another pass, but
punting on it for now, so that we have green CI again on the web
monorepo.
Refs #2290.
No changes to app code, this is just CI-wrangling.
=> ci: use nix devshell for workflows

apps/veil/src/pages/tournament/ui/delegator-rewards.tsx
created `DelegatorRewards` parent react component that wraps `DelegatorTotalRewards`, and lifted connection check into the parent. The child component now conditionally renders when the wallet is connected, avoiding unnecessary hook execution. 
react v19 warnings are [separate](https://github.com/penumbra-zone/web/issues/2296)
----------
https://github.com/user-attachments/assets/a8b84111-b902-4d19-9f2f-9c9a23dc9ebd
https://github.com/penumbra-zone/web/issues/2294
=> bug(veil): add connection status check to rewards card

apps/veil/src/pages/tournament/ui/delegator-leaderboard.tsx, apps/veil/src/shared/api/registry.ts
the `useStakingTokenMetadata` hook was originally calling into [getAssetMetadataById](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/shared/api/metadata.ts#L20-L24), which attempts to fetch the metadata from the view service (in-memory registry cache). However, if the wallet wasn't connected and the remote registry hadn't been fetched yet, this would return undefined and display unknown assets.
this updates the hook to explicitly call `registryQueryFn`, which pays a one-time cost to fetch the full remote registry when the wallet isn't connected. Then it calls the registry helper `getMetadata` to retrieve the staking token metadata. React query then caches subsequent hook invocations. 
additionally, adds more stringent `isLoading` checks to the reward cell within …
=> bug(veil): fetch registry object unconditionally

.changeset/sixty-icons-spend.md, apps/minifront/package.json, apps/veil/package.json, packages/storage/package.json, pnpm-lock.yaml
bumps registry version to `12.7.0` and pairs with https://github.com/prax-wallet/prax/pull/334
=> registry: bump version

apps/veil/src/pages/tournament/ui/voting-info.tsx
Alternate approach to #2327, with a more minimal change.
I think the hook for getting your votes is broken right now, which is the real source of the issues. This kind of papers over that, so we should open a subsequent issue to track.
Closes #2326.
=> veil: make voting button not load forever

.changeset/giant-peas-watch.md, packages/services/src/view-service/tournament-votes.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
references https://github.com/penumbra-zone/web/blob/main/packages/storage/src/indexed-db/index.ts#L524-L534. Recent registry changes exacerbated this issue by exposing breakage whereby the asset Id used at the time of voting no longer exists in the current registry, preventing metadata (and by extension the vote) from being saved.
pairs with https://github.com/prax-wallet/prax/pull/339
N/A
=> storage: store incentivized asset id instead of metadata

apps/veil/src/pages/tournament/api/use-lp-rewards.ts, apps/veil/src/pages/tournament/ui/lp-rewards.tsx
The bug here is that we were treating the case where we knew the user had no positions and the case where we were waiting to learn if the user had any positions identically, causing an infinite load.
This handles things correctly now, returning an empty rewards response when you have no positions.
Closes #2348.
=> veil: bug: distinguish no lp rewards and loading

apps/veil/src/shared/api/assets.ts
We were using getMetadata, which throws, instead of tryGetMetadata, which doesn't throw
This causes a runtime error, instead of being gracefully handleable.
references https://github.com/penumbra-zone/web/issues/2352
=> veil: bug: make useGetMetadata hook actually fallible

apps/veil/src/pages/explore/ui/waves.tsx, apps/veil/src/pages/tournament/ui/delegator-rewards.tsx
Implements Figma comments:
1. Add a tooltip to zero-balance rewards: https://www.figma.com/design/QSQzywrHh5M6dGdVtFOY5j?node-id=601-220343&m=dev#1208168955
2. Change title in the total rewards section: https://www.figma.com/design/QSQzywrHh5M6dGdVtFOY5j?node-id=601-222608&m=dev#1203576816
3. Not from Figma. Tournament & Explore & Portfolio pages used to have horizontal scroll because of changes to Penumbra Waves component. This PR fixes the component and removes annoying horizontal scroll.
=> fix(veil): apply figma comments

.changeset/thick-flowers-knock.md, packages/perspective/src/action-view/relevant-assets.ts
Closes #2280
Applies correct sides to assets of swap and swap claim action views to transaction summary component, as the issue suggests.
Doesn't do anything with issue's claim of "the swap only shows input amount and no output amount" – that's an expected behavior of the swap view – output amount is shown in the swap claim summary.
=> fix(perspective): #2280: tx summary swap rendering

apps/veil/src/pages/tournament/api/use-personal-rewards.ts, apps/veil/src/pages/tournament/server/delegator-history.ts, apps/veil/src/pages/tournament/ui/lp-rewards.tsx, apps/veil/src/pages/tournament/ui/previous-epochs.tsx, apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx, apps/veil/src/shared/ui/loading-row.tsx
Closes #2350 
In this PR:
1. Fix: Returned correct loading and empty states to "LPs rewards" and "Voting rewards" tables within the tournament landing page, as the issue suggests
2. Feat: added sorting by rewards, not only by epoch to "Voting rewards" table. Previously, only sorting by epoch was supported
3. Refactor: removed all JS-based rewards and power calculation from the server, delegated this logic to SQL. Works faster now, easier to maintain and read. Tested that the result is the same as it was before.
4. Fixed a bug of pagination limit not being correctly applied in the voting rewards table
=> fix(veil): #2350: personal rewards tables

.changeset/shaggy-adults-jam.md, packages/services/src/test-utils.ts, packages/services/src/view-service/lqt-voting-notes.test.ts, packages/services/src/view-service/lqt-voting-notes.ts, packages/services/src/view-service/tournament-votes.test.ts, packages/storage/src/indexed-db/index.ts, packages/types/src/indexed-db.ts
Fresh wallets leverage instant sync by consuming the latest frontier, and therefore need to persist the latest remote epoch fetched from the full node. This provides an auxiliary helper storage method to do that. 
pairs with https://github.com/prax-wallet/prax/pull/346
=> storage: store remote epoch

.github/workflows/packages-release.yml
For manual package releases, ensure wasm-pack is installed to avoid build failures. relevant failure in https://github.com/penumbra-zone/web/pull/2377 cc @conorsch 
=> CI runner for package release workflow

apps/minifront/src/components/extension-not-connected.tsx, pnpm-lock.yaml
now it just stays on the current page
useful for redirecting to minifront staking from veil, without a wallet connected
fixes #2375
=> fix: don't redirect to dashboard after connecting a wallet

apps/veil/src/pages/tournament/ui/previous-epochs.tsx
We were rendering an extra column for the voting rewards, even when the user is not connected, causing a rendering error.
**Before:**
**After:**
=> fix: display previous epochs table correctly when not connected

apps/veil/src/pages/tournament/ui/previous-epochs.tsx
This now makes the previous epochs table work for both connected and not-connected states
now:
before:
=> fix: Previous Epochs table, again (woops)

.changeset/beige-cloths-try.md, apps/veil/src/pages/tournament/ui/vote-dialog/index.tsx, packages/services/src/view-service/address-by-index.ts, packages/types/src/address.ts, packages/ui/src/AddressView/index.tsx, packages/wasm/crate/src/keys.rs, packages/wasm/crate/tests/test_keys.rs, packages/wasm/src/keys.ts
- Uses a specific LQT randomizer if vote is revealed.
- Adjusts UI components to render it correctly.
- Uses an ephemeral randomizer if vote is not revealed.
- Fixes a bug in the view service where getting the address by index would ignore the randomizer.
Closes #2266.
Closes #2333.
=> Handle vote revelation correctly

apps/veil/src/pages/tournament/api/use-current-epoch.ts, apps/veil/src/pages/tournament/ui/voting-info.tsx
Closes: https://github.com/penumbra-zone/web/issues/2386
Solution is to only render the loading state when the requests haven't been called yet using the `isFetched` prop.
=> Fix Perpetual Voting Buttons Loading state

.changeset/silver-things-bet.md, apps/veil/src/pages/trade/ui/order-form/store/OrderFormStore.ts, packages/ui/package.json
1. Correct account index comparison in Veil order form
2. CSS build correction for Veil – as a result breaks Minifront pages related to v2 only, so no users will be affected. Will revisit this later
=> hotfix: veil

apps/veil/src/pages/tournament/ui/social-card-dialog.tsx, apps/veil/tsconfig.json, flake.nix, justfile, package.json, scripts/benchmark-tests, scripts/playwright-setup, turbo.json
It's somewhat cursed what I'm doing here, but the goal was:
* get playwright tests running under linux, so i can run them locally
* use the nix env to provide tooling
* ergo: run the playwright tests within the devshell
Surprisingly difficult! Playwright demands binaries in a very specific location, and the binaries it downloads are dynamically linked, to paths that will be filtered out of the nix devshell's LD_LIBRARY_PATH, and therefore the browsers won't run. Even if we override the devshell's library path, we'd still be referencing incompatible shared objects.
We can instead install suitable browsers within nix and cache them, although instructing Playwright to use them is actually quite difficult. So we cheat, and create symlinks at the paths Playwright watches, pointing to the …
=> dev: support nix env for playwright tests

README.md, apps/minifront/README.md, apps/minifront/package.json, apps/veil/README.md
- Updates our build instructions after https://github.com/penumbra-zone/web/pull/2409 to include the required `pnpm dev:build` step in minifront to ensure proper consumption of CSS deps,
- Adds build instructions for Veil in the web root,
- Renames all instances of "dex-explorer" to Veil 
pairs with https://github.com/prax-wallet/prax/pull/355
=> docs: fix build instructions

.changeset/old-frogs-flash.md, apps/minifront-v2/package.json, apps/minifront-v2/vite.config.ts, apps/minifront/package.json, apps/minifront/vite.config.ts, apps/veil/next.config.mjs, apps/veil/package.json, package.json, packages/stubs/package.json, packages/stubs/src/amplitude-analytics-browser.cts, packages/stubs/src/global.d.ts, packages/stubs/tsconfig.json, pnpm-lock.yaml
Provides an empty package to override `@amplitude/analytics-browser` and stubs for `@skip-go/widget` imports from `@amplitude/analytics-browser` to completely omit the package from build output
references https://github.com/penumbra-zone/web/issues/2212
=> stub skip-go dep

.github/actions/setup-nix/action.yml, .github/actions/setup-turbo/action.yml, .github/workflows/compile-wasm.yml, .github/workflows/deploy-dex-explorer.yml, .github/workflows/deploy-ui-preview-main.yml, .github/workflows/deploy-ui-preview-pr.yml, .github/workflows/deploy-ui-release.yml, .github/workflows/packages-release.yml, .github/workflows/turbo-ci.yml, justfile
Reduces CI runtime on the primary "Turbo CI" workflow, by:
1. careful management of nix devshell for tooling
2. careful management of `.turbo/` directory for turbo cache
3. removing unnecessary workflow serialization
Rerunning the "Turbo CI" workflow on this changeset shows a 2-3x reduction in wall time:
* [Run 1](https://github.com/penumbra-zone/web/actions/runs/15219766711), 6m5s
* [Run 2](https://github.com/penumbra-zone/web/actions/runs/15219872779), 6m23s
* [Run 3](https://github.com/penumbra-zone/web/actions/runs/15220037312), 6m11s
Whereas previous runs were clocking in at ~15-20m. See more detailed timing info in #2410.
Closes #2410. 
First, review and merge https://github.com/penumbra-zone/web/pull/2419, since this PR includes that changeset, as well. Once that PR is merged, the …
=> ci: leverage turborepo caching

apps/veil/src/pages/tournament/server/delegator-history.ts, apps/veil/src/pages/tournament/ui/lp-rewards.tsx, apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx, apps/veil/src/pages/tournament/ui/vote.tsx
Closes #2437 
Additionally, this PR uses Link component instead of programmatic routing in delegator history tables and fixes asset icon display in delegator voting rewards. Previously, all assets were unknown like here:
Now, it renders like this:
Some old assets are undefined. I think it was before the switch to phobos-3 chainId, – all assets had different ids
=> fix(veil): #2437: vote percentage round

apps/veil/src/pages/tournament/ui/voting-info.tsx
Conditionally removes the details button from `VotingInfo` component on the round page since it's no-op. 
N/A
=> round card: remove details button 

.changeset/plenty-worlds-study.md, packages/ui/src/Dialog/Content.tsx, packages/ui/src/Display/index.tsx
Closes #2405 
XL screens were hitting the maximum width of content, and without proper centering it was moving the dialog to the left
=> fix(ui): #2405: center dialog for XL screens

apps/veil/src/entities/leaderboard/ui/table.tsx, apps/veil/src/pages/tournament/ui/previous-epochs.tsx, apps/veil/src/pages/tournament/ui/round/round-card.tsx
1. Originally, the asset selector in LP leaderboard (round page) displayed the user's balance next to the complete list of assets. On the page where it was implemented, I initially tried replacing it with the VotingAssetSelector to match a similar structure, but that didn’t quite work out. Instead, I decided to combine elements from both approaches and ultimately kept the `AssetSelector` from the UI package, with some modifications:
```ts 
<AssetSelector
assets={metadataAssets}
balances={undefined}
value={selectedAsset}
onChange={setSelectedAsset}
/>
```
Set the balances entry to undefined (since we're only interested in the assets), and filter for the gauge assets by calling `useEpochResults` API, then pass those directly into the `AssetSelector`.
2. Introduces smoother animations and …
=> LP leaderboard: fix asset selector

.changeset/fine-wings-sin.md, apps/minifront-v2/src/app/global.css, packages/ui/package.json, packages/ui/src/styles/main.css
We noticed a regression in fallback fonts when using the prod builds. The same issue wasn't present in the dev env (i.e. `pnpm dev`), because the dev env loads assets directly from disk. For prod builds, we must explicitly prepare outputs, such as static assets, so here we make two changes:
1. ensure that the UI package explicitly imports the fonts css, so it's included in the generated tailwind outputs
2. ensure that the font file WOFFs are copied to the dist/ output directory of the ui package.
After rerunning a prod build locally with these changes, the font loading problem was resolved on my machine.
Closes #2479.
I did not test anything related to minifront, only veil. 
The way I tested this locally was to build and run a local container on main and this branch, and observe the font …
=> fix(ui): proper font loading for prod builds

apps/veil/src/entities/leaderboard/ui/page.tsx, apps/veil/src/entities/leaderboard/ui/table.tsx, apps/veil/src/pages/tournament/ui/page.tsx, apps/veil/src/pages/tournament/ui/round/page.tsx
Closes #2482 
Reuses the existing component and adds the "Epoch #{epoch}" block and a section subtitle per new designs.
=> fix(veil): #2482: add LPs leaderboard to landing tournament page

apps/veil/src/features/cosmos/chain-provider.tsx, apps/veil/src/features/cosmos/use-augmented-balances.ts
a regression may have been introduced where localhost and testnet environments (https://dex-explorer.testnet.plinfra.net/portfolio) using `penumbra-testnet-phobos-3` failed to trigger Cosmos wallet connections.
specifically calling:
```ts
const wallet = useWallet();
```
would return `undefined`. 
To debug, I traced the "Connect Cosmos Wallet" callsites, which pointed to [cosmos-connect-button.tsx](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/features/cosmos/cosmos-connect-button.tsx) and its corresponding chain provider in [chain-provider.tsx](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/features/cosmos/chain-provider.tsx). 
After logging this code snippet:
```ts
const { data: registry } = useRegistry();
const penumbraIbcChains = …
```
=> veil(portfolio): support cosmos wallet connections on testnet

apps/veil/src/entities/position/api/use-positions.ts, apps/veil/src/entities/position/ui/table.tsx, apps/veil/src/pages/portfolio/ui/position-tabs.tsx, apps/veil/src/pages/trade/ui/history-tabs.tsx
follow-up to https://github.com/penumbra-zone/web/pull/2492
currently, `PositionsTable` performs state filtering internally. Instead of filtering based on the `showInactive` boolean, we move the state logic up to the calling component, and update `PositionsTable` to accept  an explicit array of `PositionState_PositionStateEnum` proto type values. This fixes a regression that caused open positions to appear in the closed positions table on the portfolio page.
---------
https://github.com/user-attachments/assets/d9620d53-f939-4736-8469-5406b93fc40d
N/A
=> positions: display proper position states in the tables

apps/veil/eslint.config.js, apps/veil/src/pages/tournament/ui/voting-info.tsx
This fixes some of the lints causing CI to be red across our various PRs.
- Disables the console.log related lints in the `apps/veil/src/scripts` directory.
- Fixes a few lints we regressed on last night with our bug fixes.
=> fix the lints

apps/veil/src/pages/tournament/ui/social-card-dialog.tsx
We missed correcting the exponent here.
The social card renderer expects display units for everything.
Closes #2535.
=> fix: render earnings in social card correctly

apps/veil/src/pages/tournament/ui/landing-card/index.tsx, apps/veil/src/pages/tournament/ui/round/current-voting-results/table-row.tsx, apps/veil/src/pages/tournament/ui/vote-dialog/asset-selector.tsx, apps/veil/src/pages/tournament/ui/vote-dialog/vote-dialog-asset.tsx
fixes bug where every time you click a different asset in the vote dialog an existing asset is added to the modal. 
https://github.com/penumbra-zone/web/issues/2540 as follow-up work.
https://github.com/user-attachments/assets/69c0cc41-37f8-4f0d-a03c-061b2c64c843
https://github.com/penumbra-zone/web/issues/2539
=> fix: enforce displaying unique gauge assets in asset selector

apps/veil/src/pages/trade/ui/order-form/order-form-limit.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-market.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-range-liquidity.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-simple-liquidity.tsx, apps/veil/src/pages/trade/ui/order-form/order-input.tsx, apps/veil/src/pages/trade/ui/order-form/store/SimpleLPFormStore.ts, packages/ui/src/TextInput/index.tsx
Closes #2544 
Trailing zeros were adding an overhead for value rendering in order inputs. Now, it uses `round` function only if the input is not focuses. Previously, `round` was used to prevent entering more decimal numbers than the asset exponent, now `onKeyDown` controls it.
=> fix(veil): #2544: allow zeros in order input

apps/veil/src/entities/position/ui/action-button.tsx, apps/veil/src/entities/position/ui/table.tsx, apps/veil/src/shared/utils/position.ts
The logic was simply wrong, making the assumption that only closed positions can be withdrawn.
Instead, this adds a little helper to check if a position is "fullyWithdrawn", i.e. has no reserves, and is withdrawn.
This is the kind of thing where having an actual domain library would be helpful.
Closes #2552.
=> fix: allow withdrawing withdrawn positions with reserves

apps/veil/src/pages/tournament/api/use-epoch-results.ts, apps/veil/src/pages/tournament/ui/vote-dialog/asset-selector.tsx, apps/veil/src/pages/tournament/ui/vote-dialog/index.tsx, apps/veil/src/pages/tournament/ui/vote-dialog/vote-dialog-asset.tsx
Closes #2540 
In voting dialog, splits all assets into 2 categories: above and below the threshold. If there's no assets above it, doesn't split into groups.
Also, removes grayscale from asset icons that are below the threshold.
=> fix(veil): #2540: introduce threshold bounds in voting dialog

apps/veil/src/shared/math/position.ts, packages/perspective/src/plan/view-action-plan.ts, packages/ui-deprecated/components/ui/tx/action-view.tsx, packages/ui/src/ActionView/action-view.tsx, packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/dex.rs, packages/wasm/crate/src/planner.rs, packages/wasm/src/build.ts, packages/wasm/src/dex.ts
- bumps wasm deps to `v2.0.1` tag,
- the `PositionOpen` transaction planner request in the planner is amended to generate a bundle identifier and include it in the position metadata object, as part of the `ActionPlan` payload.
references https://github.com/penumbra-zone/web/issues/2500, and extends https://github.com/penumbra-zone/web/pull/2508
=> wasm: add position metadata to wasm planner

apps/veil/src/pages/tournament/ui/landing-card/explainer.tsx, apps/veil/src/pages/trade/ui/order-form/order-form-simple-liquidity.tsx, apps/veil/src/pages/trade/ui/pair-selector/default-results.tsx, apps/veil/src/shared/utils/is-lqt-eligible.ts
Closes #2579 
Closes #2577 
Adds a check that one asset in a pair must be UM, while other is an IBC asset. Allows UM/USDC, SHITMOS/UM, but disallows TIA/USDC.
=> fix(veil): #2579: correct LQT eligibility

apps/veil/src/pages/tournament/server/previous-epochs.ts, apps/veil/src/pages/tournament/ui/landing-card/explainer.tsx
Closes #2576 
Previously, incorrect pagination happened due to limit applying to the underlying query. Also, total rows count was incorrect.
=> fix(veil): #2576: epochs pagination

apps/veil/src/pages/tournament/api/use-voting-info.ts, apps/veil/src/pages/tournament/ui/landing-card/index.tsx, apps/veil/src/pages/tournament/ui/round/round-card.tsx, apps/veil/src/pages/tournament/ui/voting-info.tsx
fixes regression from https://github.com/penumbra-zone/web/pull/2557
the `VotingInfo` component has two call sites: the [landing card](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/pages/tournament/ui/landing-card/index.tsx#L86) and [round card](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/pages/tournament/ui/round/round-card.tsx#L128). Notably, the landing card renders `<VotingInfo />`, while the latter passes an epoch prop via `<VotingInfo epoch={epoch} />`. This distinction allows `VotingInfo` to infer which page it's on and conditionally render the details button in the UI only when used on the landing page.
the regression here is that if you inspect the previous code,
notice the details button used the epoch field from  `useVotingInfo` to construct its …
=> fix details button 

apps/veil/src/pages/tournament/ui/social-card-dialog.tsx
The social card dialog logic was using `process.env` to try to look up the site's base URL. That can't work. While we want to standardize on a pattern for app config that works in all cases, e.g. [0], we also want an immediate fix for near-term to resolve bugs [1], which is why I'm submitting this stopgap.
[0] https://github.com/penumbra-zone/web/pull/2593
[1] https://github.com/penumbra-zone/web/issues/2575
=> fix(veil): hardcode veil fqdn in social card

apps/veil/src/pages/tournament/ui/landing-card/explainer.tsx, apps/veil/src/pages/tournament/ui/landing-card/results.tsx, apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx, apps/veil/src/pages/tournament/ui/round/current-voting-results/table-row.tsx, apps/veil/src/pages/tournament/ui/shared/provide-liquidity-button.tsx, apps/veil/src/pages/tournament/ui/vote-dialog/vote-dialog-asset.tsx
Closes #2610 
New looks according to the PRD "Make the gauge voting threshold more apparent on the LQT landing page  - Mini PRD"
Landing card
A tooltip
A modal that opens for <5% items
Round page
=> fix(veil): #2610: update gauge voting designs

packages/wasm/crate/Cargo.lock, packages/wasm/crate/Cargo.toml, packages/wasm/crate/src/dex.rs, packages/wasm/crate/src/planner.rs, packages/wasm/src/dex.ts
CI is currently failing due to outdated proto definitions. Once https://github.com/penumbra-zone/web/pull/2508 lands, everything should compile correctly.
- bumps wasm deps to v2.0.1 tag,
- the `PositionOpen` transaction planner request in the planner is amended to generate a bundle identifier and include it in the position metadata object, as part of the `ActionPlan` payload.
https://github.com/penumbra-zone/web/issues/2500
=> wasm: encrypted position metadata support

.changeset/sixty-boats-fry.md, apps/veil/src/shared/utils/transaction-classify.ts, packages/perspective/src/transaction/classification.ts, packages/perspective/src/transaction/classify.ts, packages/ui-deprecated/components/ui/tx/action-view.tsx, packages/ui-deprecated/components/ui/tx/actions-views/position-open-view.tsx, packages/ui/src/ActionView/action-view.tsx, packages/ui/src/TransactionSummary/use-classification.ts
Temporary fix to restore the action view for position opens for opaque / visible action views on current main, allowing history to continue populating. It still _doesn't_ distinguish between visible and opaque views—where the visible view includes all the information of the opaque view, plus the decrypted position metadata. 
https://github.com/penumbra-zone/web/issues/2503 and pairs with https://github.com/prax-wallet/prax/pull/395
=> action views: encrypted position metadata support

apps/veil/src/shared/api/server/shielding-deposits.ts, apps/veil/src/shared/database/schema.ts, apps/veil/src/widgets/shielding-ticker/index.tsx
fixes #2605 
This makes the individual deposit links go to the tx of the deposit instead of the block.
Currently, the new pindexer changes that add the tx_hash are not live yet, so it falls back to block. Once they are live, it will default to the tx page.
=> feat: redirect to tx in explorer if present

.changeset/stupid-camels-lay.md, apps/minifront-v2/src/shared/stores/transfer-store.ts, apps/minifront/src/components/ibc/deposit-manual/asset-utils.test.ts, apps/minifront/src/components/ibc/deposit-manual/asset-utils.tsx, apps/minifront/src/components/swap/swap-form/simulate-swap-result/traces/trace/price.tsx, apps/minifront/src/state/helpers.ts, apps/minifront/src/state/ibc-out.ts, apps/minifront/src/state/send/index.ts, apps/minifront/src/state/staking/index.ts, apps/minifront/src/state/swap/dutch-auction/get-sub-auctions.ts, apps/minifront/src/state/swap/helpers.ts, apps/minifront/src/state/swap/instant-swap.ts, apps/veil/src/entities/position/model/position-adapters.test.ts, apps/veil/src/entities/transaction/model/validations.ts, apps/veil/src/pages/portfolio/ui/unshield-dialog.tsx, packages/types/src/amount.ts, packages/types/src/lo-hi.test.ts, packages/types/src/lo-hi.ts, packages/types/src/pnum.test.ts, packages/types/src/pnum.ts, packages/ui-deprecated/components/ui/block-sync-status/block-sync-status.tsx
Use default import for `bignumber.js` instead of destructuring import.
https://github.com/penumbra-zone/web/issues/2632
=> Import `BigNumber` correctly

.dockerignore, apps/veil/app/app.tsx, apps/veil/next.config.mjs, apps/veil/src/widgets/footer/index.ts, apps/veil/src/widgets/footer/ui/footer.tsx, apps/veil/src/widgets/footer/ui/veil-version.tsx, apps/veil/tsconfig.json, apps/veil/types/env.d.ts, ci/containerfiles/Containerfile-veil-fly, justfile
Adds a git hash in the footer for Veil, so that it's obvious which commit is running on a given instance. There are multiple frontends managed by multiple orgs, all on their own deploy schedule, so this change is intended to make it clear whether a given fix has in fact been deployed to a given environment.
Closes https://github.com/penumbra-zone/web/issues/2154
It looks like this:
Functionality-wise, this looks "good enough" to me, but I'm mostly concerned about the shape of the implementation. What you see is mostly what the LLM thought was a good idea. In particular, please scrutinize the overriding the node env and the resulting process.env calls; should we instead use an api env route as described in https://github.com/penumbra-zone/web/pull/2593?
=> feat: add git version to veil footer

apps/veil/src/pages/portfolio/api/use-unified-assets.ts, apps/veil/src/pages/portfolio/index.tsx, apps/veil/src/pages/portfolio/ui/asset-bars.tsx, apps/veil/src/pages/portfolio/ui/assets-table.tsx, apps/veil/src/widgets/footer/ui/footer.tsx, apps/veil/src/widgets/header/ui/connection.tsx, apps/veil/src/widgets/shielding-ticker/index.tsx
Closes #2598 
After looking at the #2598 issue, I found that the UX issue won't be fixed by adding new state in the connection store, rather the portfolio page needed a major rework to eliminate content layout shift and jumps.
In this PR, I used `connectedLoading` variable introduced by @cronokirby to render better connection states in the header and in the portfolio pages. Here's the final result in a video – compare it with [how it was before](https://github.com/user-attachments/assets/4477f7e7-a0eb-432e-89cd-da2f7147635a).
I also fixed css issues here and there while working on portfolio page.
https://github.com/user-attachments/assets/8b85176d-fc0c-4ff5-97be-3bc58106c95f
=> fix(veil): #2598: eliminate layout shifts in portfolio page

apps/minifront/src/fetchers/status.ts
The syncing modal appears too aggressively, especially on dense blocks. This change increases the timeout from 15s to 60s as a conservative adjustment.
https://github.com/penumbra-zone/web/issues/2254
=> Increase syncing modal timeout

apps/veil/src/shared/utils/format-time.ts
rounds the remaining timer display to whole seconds when below 60 seconds.
https://github.com/penumbra-zone/web/issues/2651
=> fix: rounding time pluralization

.changeset/upset-ads-find.md, packages/storage/src/indexed-db/index.ts
a conditional check in storage fails when subaccount is 0 (falsy in JS), causing it to evaluate to false and skip the filtering logic. This in turns returns the votes for each subaccount, so voting in one account will incorrectly evaluate each subaccount as already voted. This seems to have been an issue since the reactor in https://github.com/penumbra-zone/web/pull/2557 which exposed this issue. However, this appears to be an edge case that only arises when voting is initiated from a subaccount first, and then followed by an attempt to vote with the main account—rather than the other way around.
https://github.com/penumbra-zone/web/issues/2648
=> fix: correctly apply subaccount filtering for historical votes in storage
