penumbra-zone/web

apps/extension/package.json
package.json
packages/crypto/package.json
packages/eslint-config-custom/package.json
packages/ui/package.json
packages/wasm/package.json
packages/wasm/src/keys.test.ts
packages/wasm/src/keys.ts
pnpm-lock.yaml

Updates based on new CI/CD publishing: https://github.com/penumbra-zone/penumbra/pull/2956

Update packages new @penumbra-zone org

---

docs/README.md
docs/message-passing.md
docs/protobufs.md
docs/web-workers.md

Web workers, protobufs, and message passing

Docs catchup

---

packages/types/src/state-commitment-tree.ts

Related to: https://github.com/penumbra-zone/web/issues/83

Add height created to zod type

---

apps/extension/src/hooks/last-block-synced.ts
apps/extension/src/routes/service-worker/view-protocol-server/router.ts
apps/extension/src/routes/service-worker/view-protocol-server/status-stream.ts
apps/extension/src/services/index.ts
apps/webapp/app/balances/display-balances.tsx
apps/webapp/app/header/block-sync.tsx
apps/webapp/app/header/header.tsx
apps/webapp/app/header/notifications.tsx
apps/webapp/app/transactions/all-transactions.tsx
apps/webapp/hooks/balances.ts
packages/query/src/block-processor/index.ts
packages/query/src/queriers/tendermint.ts
packages/storage/src/indexed-db/index.ts
packages/storage/src/indexed-db/updater.ts
packages/transport/src/hooks.ts
packages/transport/src/index.ts
packages/transport/src/looper.ts
packages/transport/src/stream.ts
packages/types/src/indexed-db.ts

Dapp now has syncing blocks with actual live data

Status stream

---

apps/extension/src/routes/service-worker/view-protocol-server/balances.test.ts
apps/extension/src/routes/service-worker/view-protocol-server/balances.ts
apps/extension/src/routes/service-worker/view-protocol-server/status-stream.ts
apps/webapp/hooks/balances.ts
apps/webapp/hooks/calculate-balance.ts
apps/webapp/hooks/sorted-asset.ts
packages/query/src/block-processor/index.ts
packages/storage/src/indexed-db/index.ts
packages/types/src/indexed-db.ts

Closes #91 
Also, the last PR introduced a bug that skipped the balances of block 0. This fixes that as well.

Fix balances bugs

---

apps/webapp/app/header/navbar.tsx

Gray out disabled nav links

---

apps/webapp/app/dashboard/transaction-table.tsx
apps/webapp/app/page.tsx
packages/types/src/string.test.ts
packages/types/src/string.ts

Adding real data to tx table

---

apps/extension/package.json
apps/webapp/package.json
packages/query/package.json
packages/router/package.json
packages/storage/package.json
packages/transport/package.json
packages/types/package.json
packages/wasm/package.json
pnpm-lock.yaml

Reverting proto version

---

apps/webapp/state/send.ts
packages/router/package.json
packages/router/src/grpc/custody/authorize.ts
packages/router/src/grpc/custody/router.ts
packages/router/src/root-router.ts
packages/types/src/transaction.ts
packages/wasm/index.ts
packages/wasm/src/build.ts
pnpm-lock.yaml

User can request authorization for their plan

Custody routes in place

---

apps/webapp/app/send/send-form.tsx
apps/webapp/state/send.ts
packages/crypto/src/encryption.ts
packages/router/package.json
packages/router/src/grpc/clients.ts
packages/router/src/grpc/view-protocol-server/broadcast.ts
packages/router/src/grpc/view-protocol-server/router.ts
packages/router/src/grpc/view-protocol-server/witness-build.ts
packages/types/src/transaction.ts
packages/wasm/src/build.ts
pnpm-lock.yaml

Note: Broadcast bug being investigated still.

Support for building tx

---

apps/webapp/app/header/notifications.tsx
apps/webapp/app/page.tsx
apps/webapp/app/send/page.tsx

hide unused elements

---

apps/webapp/app/dashboard/assets-table.tsx
apps/webapp/app/dashboard/transaction-table.tsx
apps/webapp/hooks/address.ts
apps/webapp/hooks/sorted-asset.ts
apps/webapp/shared/select-token-modal.tsx
apps/webapp/state/send.ts

A new display for balances on dashboard. Also refactoring a good deal of how we handle balances.

Number formatting

---

apps/webapp/state/send.test.ts
packages/types/src/address.test.ts
packages/types/src/address.ts
packages/types/src/state-commitment-tree.ts
packages/types/src/string.test.ts
packages/types/src/string.ts
packages/wasm/package.json
packages/wasm/src/sct.ts
packages/wasm/src/view-server.ts
pnpm-lock.yaml

addresses
* wasm crate version bump
* nct-sct rename penumbra-zone/penumbra@167e8e5d1eaee3d238f39de1646804647cde964a
* prefix change penumbra-zone/penumbra#1320

Update web for testnet63 changes

---

apps/webapp/app/page.tsx

Add padding to table

---

packages/router/src/grpc/view-protocol-server/ephemeral-addr.ts
packages/router/src/grpc/view-protocol-server/router.ts
packages/wasm/src/keys.test.ts
packages/wasm/src/keys.ts

Add support for generating ephemeral addresses

---

apps/webapp/app/dashboard/assets-table.tsx

Closes #174
This could surely be done in a better way but some text here is better than none.

Add text suggesting using the faucet when balances are empty

---

packages/constants/config.ts

fix: transaction view bug

---

apps/extension/src/service-worker.ts
packages/router/src/grpc/types.ts
packages/transport/src/chrome-runtime/background-connection-manager.ts
packages/transport/src/chrome-runtime/client-connection-manager.ts
packages/transport/src/chrome-runtime/errors.ts
packages/transport/src/chrome-runtime/stream.ts
packages/transport/src/create.ts
packages/transport/src/stream.ts
packages/transport/src/types/channel-messages.ts

fixes #280 #287 and should make debugging any failures a bit nicer

more robust error propagation and handling

---

apps/extension/src/clients/index.ts
apps/webapp/src/clients/grpc.ts
apps/webapp/src/clients/penumbra-port.ts
apps/webapp/src/fetchers/index-by-address.ts
apps/webapp/src/state/ibc.ts
apps/webapp/src/state/send.ts
packages/transport/src/create.ts

Don't immediately init transport connection, wait until use.

---

package.json
packages/router/src/grpc/view-protocol-server/broadcast.ts
packages/router/src/grpc/view-protocol-server/note-by-commitment.ts
packages/router/src/grpc/view-protocol-server/nullifier-status.test.ts
packages/router/src/grpc/view-protocol-server/nullifier-status.ts
packages/router/src/grpc/view-protocol-server/router.ts
pnpm-lock.yaml

Closes #233
Given we already have database subscriptions in place, this was much easier than I thought.

Await detection impls

---

packages/router/src/grpc/view-protocol-server/nullifier-status.test.ts
packages/router/src/grpc/view-protocol-server/nullifier-status.ts

Thanks to @turbocrime for finding this one. Follow up from: https://github.com/penumbra-zone/web/pull/301. @Valentine1898 fyi.
Previously, the promise that "lost" the race was dropped. This would mean that the slower detected swap/note would not be checked again on the next iteration. `mergeAsyncGenerators` has been updated to retain the slower.

Retain lost promise racer

---

packages/transport/src/chrome-runtime/background-connection-manager.ts
packages/transport/src/chrome-runtime/errors.ts

suppress more errors

---

apps/webapp/src/components/send/send-form.tsx
apps/webapp/src/components/shared/edu-panels/content.ts
apps/webapp/src/components/shared/input-block.tsx
apps/webapp/src/state/ibc.ts
apps/webapp/src/state/send.test.ts
apps/webapp/src/state/send.ts
packages/ui/components/ui/select-account.tsx

Cf https://github.com/penumbra-zone/penumbra/issues/3381#issuecomment-1869311071

Change terminology to IBC Deposit Address

---

apps/extension/src/offscreen.ts

offscreen.ts incorrect import path

---

apps/webapp/src/components/send/send-form.tsx
apps/webapp/src/state/send.test.ts
apps/webapp/src/state/send.ts

form validation for memo

---

apps/webapp/src/state/send.ts

correct memo length

---

apps/extension/src/offscreen.ts
apps/extension/src/wasm-build-action.ts

properly detect worker errors

---

packages/router/src/grpc/view-protocol-server/gas-prices.ts

Added gas prices docs

---

packages/query/src/queriers/tendermint.ts

Closes https://github.com/penumbra-zone/web/issues/352
It's probably too aggressive to throw an error on _any_ Tendermint log

Warn on unknown tendermint log

---

apps/extension/src/offscreen.ts
apps/extension/src/wasm-build-action.ts

fixes #416 by simply reverting a subset of 4a59f62 which attempted to use better types and handle more failures

don't break offscreen

---

apps/extension/src/routes/popup/approval/is-controlled-address.test.ts
apps/extension/src/routes/popup/approval/is-controlled-address.ts
packages/types/src/translators/address-view.test.ts

This fixes an import issue.
Relatedly: I've messaged @grod220 about requiring PRs to be built against latest `main` to avoid broke import issues like this in the future.

Fix client import

---

package.json
pnpm-lock.yaml

fixes turbo unable to launch vite

downgrade turbo

---

apps/webapp/src/components/header/constants.tsx
apps/webapp/src/components/header/navbar.tsx
apps/webapp/src/components/root-router.tsx
apps/webapp/src/components/send/send-form.tsx
apps/webapp/src/components/shared/asset-icon.tsx
apps/webapp/src/components/swap/asset-out-box.tsx
apps/webapp/src/components/swap/asset-out-selector.tsx
apps/webapp/src/components/swap/layout.tsx
apps/webapp/src/components/swap/swap-form.tsx
apps/webapp/src/fetchers/address.ts
apps/webapp/src/fetchers/balances.ts
apps/webapp/src/state/ibc.ts
apps/webapp/src/state/swap.test.ts
apps/webapp/src/state/swap.ts
packages/constants/assets.ts
packages/query/src/queriers/tendermint.ts
packages/router/src/grpc/view-protocol-server/transaction-planner.ts
packages/services/src/index.ts
packages/types/src/services.ts
packages/types/src/transaction/perspective.ts
packages/ui/components/ui/tx/view/action-view.tsx
packages/ui/components/ui/tx/view/swap.tsx
packages/wasm/src/tx-planner.ts

Closes: https://github.com/penumbra-zone/web/issues/390
The first part of the multi-part PR series in doing swaps. Does a few things:
- Implements new swap asset selector components
- Refactor swap slice
- Implement transaction wasm planning for swaps

Swap [ui part 1]

---

apps/webapp/src/state/helpers.ts
packages/eslint-config-custom/index.js
packages/query/src/block-processor.ts
packages/transport/src/chrome-runtime/adapter.ts

Require annotations on uinitialized vars

---

apps/extension/package.json
apps/extension/src/hooks/chain-id.ts
apps/extension/src/hooks/last-block-synced.ts
apps/extension/src/hooks/onboarding.ts
apps/extension/src/routes/popup/settings/settings-rpc.tsx
apps/webapp/src/fetchers/chain-id.ts
package.json
packages/constants/config.ts
packages/query/package.json
packages/query/src/block-processor.ts
packages/query/src/queriers/app.ts
packages/router/src/grpc/view-protocol-server/app-parameters.test.ts
packages/router/src/grpc/view-protocol-server/app-parameters.ts
packages/router/src/grpc/view-protocol-server/transaction-planner.ts
packages/router/src/std/internal-client.ts
packages/router/src/std/router.ts
packages/router/src/std/routes/clear-cache.ts
packages/router/src/std/routes/sync.ts
packages/services/package.json
packages/services/src/index.ts
packages/storage/src/indexed-db/index.ts
packages/types/src/block-processor.ts
packages/types/src/indexed-db.ts
packages/types/src/querier.ts
packages/types/src/services.ts
packages/types/src/std-route.ts
packages/wasm/src/tx-planner.ts
pnpm-lock.yaml

wip. having difficulty with some kind of proto spec mismatch
edit: ready to go

even more v0.65 updates 

---

apps/extension/src/clients/extension-service.ts
apps/extension/src/clients/transport-options.ts
apps/extension/src/service-worker.ts
apps/webapp/src/clients/grpc.ts
apps/webapp/src/fetchers/address.ts
package.json
packages/router/src/grpc/view-protocol-server/address-by-index.test.ts
packages/router/src/grpc/view-protocol-server/address-by-index.ts
packages/transport/src/chrome-runtime/adapter.ts
packages/transport/src/create.ts
packages/transport/src/stream.ts
packages/types/src/json-options.ts
packages/types/src/registry.ts
pnpm-lock.yaml

- JsonReadOptions are now more permissive and consistent throughout repo
- getAddressByIndex now handles missing inputs
- fetchers for same slightly adjusted

v0.65 updates round 4

---

apps/webapp/src/components/tx-details/index.tsx
packages/query/src/block-processor.ts
packages/router/src/grpc/view-protocol-server/transaction-info-by-hash.ts
packages/types/src/block-processor.ts

Closes https://github.com/penumbra-zone/web/issues/448
Some minor cleanup. Moves tx info logic. Also, given we show public information as a fallback already, remove the "can't see this?" copy.

Move tx info into rpc call

---

packages/router/src/grpc/view-protocol-server/status.test.ts
packages/router/src/grpc/view-protocol-server/test-utils.ts

add status tests

---

packages/router/src/grpc/view-protocol-server/assets.ts
packages/router/src/grpc/view-protocol-server/transaction-info.ts

Temporary fix until #495 is resolved
For swaps, this is done in #498

Temporarily fix IDB streaming for transactionInfo and assets

---

apps/webapp/src/components/send/ibc/ibc-form.tsx
apps/webapp/src/state/ibc.test.ts
apps/webapp/src/state/ibc.ts
apps/webapp/src/state/send.ts
packages/constants/chains.ts
packages/types/src/registry.ts

Currently blocked from full enabling and end-to-end testing given we have no relayers. Will de-prioritize ibc work, but wanted to get some of these changes in so they aren't lost.
Context: https://discord.com/channels/824484045370818580/930154881040404480/1207033076299862016

Minor ibc updates

---

apps/extension/src/offscreen.ts
apps/extension/src/wasm-build-action.ts
apps/webapp/src/components/shared/toast-content.tsx
apps/webapp/src/state/helpers.ts
apps/webapp/src/state/ibc.ts
apps/webapp/src/state/send.ts
apps/webapp/src/state/swap.ts
packages/router/src/grpc/offscreen-client.ts
packages/router/src/grpc/view-protocol-server/authorize-and-build.ts
packages/router/src/grpc/view-protocol-server/util/build-tx.ts
packages/router/src/grpc/view-protocol-server/util/custody-authorize.ts
packages/router/src/grpc/view-protocol-server/witness-and-build.ts
packages/types/src/internal-msg/offscreen.ts
packages/types/src/promise-with-resolvers.ts

slight motion towards transaction progress indication. discussed in #324

broadcast toast

---

packages/router/src/grpc/view-protocol-server/note-by-commitment.test.ts
packages/router/src/grpc/view-protocol-server/note-by-commitment.ts
packages/router/src/grpc/view-protocol-server/swap-by-commitment.test.ts
packages/router/src/grpc/view-protocol-server/test-utils.ts

407 add tests for swapbycommitmentrequest

---

.github/workflows/compile-wasm.yml
.github/workflows/test-wasm.yml
.github/workflows/turbo-ci.yml
turbo.json

forgot the last bit of new workflows: the ui

name workflows, allow dispatch

---

packages/wasm/crate/Cargo.toml
packages/wasm/package.json
pnpm-lock.yaml

pin rust deps to `v0.67.1` release tag

v0.67.1 tags

---

.github/workflows/turbo-ci.yml
README.md

Fix CI in main branch

---

packages/ui/index.ts

don't bundle large video

---

apps/webapp/src/components/shared/toast-content.tsx
apps/webapp/src/state/send.ts
packages/router/src/ctx/approver.ts

Show a more helpful toast when the user denies a transaction

---

.github/workflows/compile-wasm.yml
.github/workflows/turbo-ci.yml

- fixes cargo tree package target
- removes lock file update requirement (otherwise will throw on minor deps bump on crates.io)
- runs on main

Remove exact cargo.lock requirement

---

.github/workflows/compile-wasm.yml

Follow up to: https://github.com/penumbra-zone/web/pull/574

Git diff on file changes

---

docs/adrs/002-framework.md

Consequence of: https://github.com/penumbra-zone/web/issues/310

ADR 002: Client-side rendering

---

apps/extension/src/clients/extension-page.ts
packages/transport/src/create.ts

improves reliability of intra-extension transport

init ext page port once

---

packages/router/src/grpc/view-protocol-server/test-utils.ts
packages/router/src/grpc/view-protocol-server/wallet-id.test.ts

add tests for wallet-id

---

apps/webapp/src/components/shared/input-token.tsx
apps/webapp/src/components/shared/select-token-modal.tsx
apps/webapp/src/components/swap/asset-out-box.tsx
apps/webapp/src/components/swap/asset-out-selector.tsx

Closes: https://github.com/penumbra-zone/web/issues/583
Culprits in issue ⬆️

Remove redundant icons in ui

---

apps/extension/public/um-token.svg
packages/constants/assets/local-asset-registry.json

add um token logo svg

---

apps/webapp/src/components/swap/swap-loader.tsx

Filter out assets that are not available for swap from asset selector

---

packages/storage/src/chrome/migration.test.ts

doesn't seem to have any effect

remove pointless await

---

packages/ui/components/ui/tooltip.tsx

this has been cluttering the extension log

remove pointless ref

---

apps/extension/src/routes/popup/settings/settings-rpc.tsx
packages/eslint-config-custom/index.js
packages/storage/src/indexed-db/indexed-db.test.ts
packages/transport/src/chrome-runtime/client-connection-manager.ts

enforce triple-equals over coercive double-equals.
exception for null comparisons - should null comparisons be excepted?

eslint eqeqeq

---

apps/webapp/src/components/footer/index.tsx

Clarify that the software runs on the end-user device.

Frontend footer tweaks

---

apps/webapp/src/components/shared/select-token-modal.tsx

now the tokens aren't truncated

fix columns in send token modal

---

packages/ui/styles/globals.css

fix undefined tailwind accent foreground

---

apps/webapp/src/components/staking/account/delegation-value-view/staking-actions/index.tsx
apps/webapp/src/state/staking.test.ts
apps/webapp/src/state/staking.ts
packages/router/src/grpc/view-protocol-server/transaction-planner.ts
packages/types/src/staking.ts
packages/ui/components/ui/tx/view/action-view.tsx
packages/ui/components/ui/tx/view/undelegate.tsx
packages/wasm/crate/src/wasm_planner.rs
packages/wasm/src/tx-planner.ts

This builds out the UI for undelegating from a validator.
https://github.com/penumbra-zone/web/assets/1121544/edddcac9-bdba-40ec-9101-d376028a75a8
Closes #542

Allow users to undelegate from a validator

---

apps/extension/src/service-worker.ts

this was useful during dev but should have been removed for merge

remove clearing of connectedSites

---

packages/wasm/crate/src/planner.rs

Fixes #681
Thanks to @hdevalence for finding the bug's source + fix

Fix source address in WASM planner

---

apps/extension/src/impls.ts
apps/extension/src/utils/rethrow-impl-errors.test.ts
apps/extension/src/utils/rethrow-impl-errors.ts

Per @grod220 's comment [here](https://github.com/penumbra-zone/web/pull/700#discussion_r1516027514)

Fix typings for impls

---

apps/minifront/src/state/staking/index.ts

This fixes an issue where, if you switch quickly back and forth between account indexes on the staking page, multiple copies of the same delegations are sometimes rendered since the previous request is still loading.

Prevent duplicate renders of delegations by aborting earlier requests when new ones start

---

apps/extension/src/routes/popup/popup-needs.ts

Needs to return null or a loader error is propagated:

Loader null bug

---

apps/extension/package.json
apps/extension/src/utils/tests-setup.js
apps/minifront/package.json
apps/minifront/promise.withresolvers.d.ts
apps/minifront/tests-setup.ts
packages/transport-dom/src/create.ts
pnpm-lock.yaml

Make sure errors get surfaced when the RPC is unavailable

---

packages/transport-dom/src/create.test.ts
packages/transport-dom/src/create.ts

 propagate listener errors and transport failure from streaming requests

---

packages/client/package.json
packages/constants/package.json
packages/getters/package.json
packages/polyfills/package.json
packages/transport-dom/package.json
packages/types/package.json
turbo.json

Closes https://github.com/penumbra-zone/web/issues/750

Wildcards exports

---

.github/workflows/packages-release.yml

Adds workflow for versioning or publishing npm packages to main merges

Update packages-release workflow

---

apps/extension/src/service-worker.ts

don't attempt to onboard at services init

---

apps/minifront/src/components/dashboard/assets-table.tsx
apps/minifront/src/components/send/send-form/index.tsx
apps/minifront/src/fetchers/balances/by-account.ts
apps/minifront/src/state/staking/index.ts
packages/wasm/crate/src/planner.rs
packages/wasm/crate/src/storage.rs

Bug description in issue https://github.com/penumbra-zone/web/issues/798

 #798  [Bug] planner throws an error in cases where we need to spend more than one note

---

packages/ui/components/ui/json-viewer.tsx

They're too small to click otherwise!

Tweak arrow size

---

packages/ui/components/ui/json-viewer.tsx
packages/ui/package.json
pnpm-lock.yaml

im sorry im like this.
but try inspecting a tx with this it's a much nicer experience

too fancy json view

---

apps/minifront/src/components/header/tablet-nav-menu.tsx

this has been broken for months

fix tablet nav current page display

---

docs/README.md
docs/debugging.md

Follow up from https://github.com/penumbra-zone/web/pull/882

Docs for debugging SCT

---

apps/extension/src/get-rpc-impls.ts
packages/transport-dom/src/proxy.ts

adds information and suppresses the error
fixes #689

explain unhandled context

---

.changeset/flat-foxes-punch.md
.changeset/large-eyes-doubt.md
.changeset/poor-buttons-count.md
apps/extension/CHANGELOG.md
apps/extension/package.json
apps/extension/public/manifest.json
apps/minifront/CHANGELOG.md
apps/minifront/package.json
apps/node-status/CHANGELOG.md
apps/node-status/package.json
packages/crypto/CHANGELOG.md
packages/crypto/package.json
packages/query/CHANGELOG.md
packages/query/package.json
packages/router/CHANGELOG.md
packages/router/package.json
packages/services/CHANGELOG.md
packages/services/package.json
packages/storage/CHANGELOG.md
packages/storage/package.json
packages/transport-chrome/CHANGELOG.md
packages/transport-chrome/package.json

For publishing v6.3.0 https://github.com/penumbra-zone/web/issues/938

Version npm packages + update manifest

---

.gitignore
.prettierignore
package.json
packages/eslint-config-custom/index.js
turbo.json

not sure why these started showing up but they're annoying. adds a specific pattern to ignorefiles, and provides a cleanup script

declutter vitest temp files

---

apps/extension/webpack.config.ts

rm unused webpack rule

---

apps/extension/src/get-rpc-impls.ts
apps/minifront/src/clients.ts
apps/minifront/src/state/ibc.test.ts
apps/minifront/src/state/ibc.ts
packages/types/src/registry.ts

Closes #812
Reference implementation: https://github.com/penumbra-zone/penumbra/blob/main/crates/bin/pcli/src/command/tx.rs#L1055-L1067
Also fixed our method to getting the timeout blocks

IBC out: round up to nearest 10min

---

.github/workflows/turbo-ci.yml
apps/extension/package.json
apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
apps/minifront/package.json
apps/minifront/src/components/ibc/ibc-in/chain-dropdown.tsx
apps/minifront/src/components/ibc/ibc-in/chain-picker.tsx
apps/minifront/src/components/ibc/ibc-in/chain-provider.tsx
apps/minifront/src/components/ibc/ibc-in/config/defaults.ts
apps/minifront/src/components/ibc/ibc-in/ibc-in-form.tsx
apps/minifront/src/components/ibc/ibc-in/interchain-ui.tsx
apps/minifront/src/components/ibc/ibc-out/chain-selector.tsx
apps/minifront/src/components/ibc/ibc-out/ibc-out-form.tsx
apps/minifront/src/components/ibc/layout.tsx
apps/minifront/src/components/ibc/long-arrow.tsx
apps/minifront/src/fetchers/registry.ts
apps/minifront/vite-plugin-node-stdlib-browser.d.ts
apps/minifront/vite.config.ts
packages/ui/components/ui/tx/view/address-view.tsx
pnpm-lock.yaml

Part 1 of a multi-part task of getting support for IBC'ing into Penumbra. This has been copied over and modified from the [asset lists interchain ui](https://cosmology.zone/products/create-cosmos-app) example. The subsequent PRs will be incorporating more and more from this example.
First up is to get support for a chain out selector.
https://github.com/penumbra-zone/web/assets/16624263/215bbd4b-724d-4a7e-8546-ba33d4f3796f

Interchain UI -> chain selection

---

apps/extension/src/service-worker.ts

Check out https://github.com/penumbra-zone/web/issues/963 before review 
That closes #963 and #993
It's important for us to fix #963 before the release, which will be Monday, so I propose such an ugly but simple solution, suggestions?

custom grpcEndpoint migration

---

.github/workflows/extension-publish.yml
.github/workflows/packages-release.yml

larger buildjet for publish and release ci

---

docs/extension-services.md

brief docs demonstrating client init, just to have something we can link.

document client

---

apps/extension/src/routes/popup/home/index-header.tsx
apps/minifront/src/components/header/header.tsx
apps/minifront/src/components/header/top-row.tsx
apps/minifront/src/components/layout.tsx
packages/ui/components/ui/testnet-banner.test.tsx
packages/ui/components/ui/testnet-banner.tsx

adds a testnet disclaimer banner to minifront and prax

testnet banner in minifront and prax

---

apps/minifront/src/components/swap/swap/index.tsx

Closes https://github.com/penumbra-zone/web/issues/1009
Prevents panel height expansion

Prevent expanding panels

---

apps/minifront/src/components/swap/helpers.ts
apps/minifront/src/components/swap/swap/asset-out-box.tsx
apps/minifront/src/components/swap/swap/swap-loader.tsx

filter out delegationTokens and unbondingTokens from swap asset selector

---

apps/extension/public/manifest.json

Closes https://github.com/penumbra-zone/web/issues/1028
Corresponds with our `Promise.withResolvers` usage.

Add chrome version req

---

apps/extension/src/routes/popup/approval/transaction/index.tsx

Closes https://github.com/penumbra-zone/web/issues/1039

Only show raw json for sender view

---

apps/extension/package.json
apps/minifront/package.json
packages/services-context/package.json
packages/storage/package.json
pnpm-lock.yaml

update asset registry version to point to new chain id `penumbra-testnet-deimos-8`

update registry version

---

packages/ui/components/ui/tx/view/address-view.tsx
packages/ui/components/ui/tx/view/memo-view.tsx

Tweak layout for sender return address

---

apps/extension/package.json
apps/minifront/package.json
packages/services-context/package.json
packages/storage/package.json
pnpm-lock.yaml

To get new noble channels: https://github.com/prax-wallet/registry/pull/34

Update registry to latest

---

apps/minifront/src/components/ibc/ibc-in/chain-provider.tsx
apps/minifront/src/components/ibc/ibc-in/destination-addr.tsx
apps/minifront/src/state/ibc-in.ts

Closes https://github.com/penumbra-zone/web/issues/1049
Before we were hardcoding a standard fee. This doesn't work generally across chains. Now we are doing tx simulations to get these estimates.

Properly estimate ibc gas fees

---

apps/extension/src/storage/onboard.ts
packages/storage/src/chrome/base.ts

onboarding storage subscriptions were busted, fixed now.
needs tests, probably. better typed wrapper in another pr

onboarding hotfix

---

.changeset/shaggy-kangaroos-invent.md
apps/extension/package.json
apps/minifront/package.json
packages/services-context/package.json
packages/storage/package.json
pnpm-lock.yaml

Refs https://github.com/prax-wallet/registry/pull/35

chore: bump registry 7.2.1 -> 7.2.2

---

.changeset/strange-doors-itch.md
apps/extension/package.json
apps/minifront/package.json
packages/services-context/package.json
packages/storage/package.json
pnpm-lock.yaml

Pairs with https://github.com/prax-wallet/registry/pull/39
Noble channel expired and a new one has spun up.

Update registry [new noble channel]

---

apps/minifront/src/state/status.ts
packages/services/src/view-service/status.test.ts
packages/services/src/view-service/status.ts
packages/ui/components/ui/block-sync-status/condensed.tsx

fix sync status section

---

.github/workflows/deploy-firebase-dapp.yml

Now that our APIs are stable, moving back to continuous deployment

Deploy minifront on merge to main

---

apps/extension/public/manifest.json
apps/extension/src/listeners/index.ts
apps/extension/src/listeners/message-external.ts
apps/extension/src/listeners/message-prax-request.ts
apps/extension/src/listeners/tabs-updated-prax-init.ts
apps/extension/src/service-worker.ts

adds permission to manifest for `<all_urls>` and provides a riddle for users at the endpoint

basic externally connectable

---

apps/extension/public/manifest.json
packages/wasm/crate/Cargo.lock
packages/wasm/crate/Cargo.toml
packages/wasm/crate/src/metadata.rs

Relates to #1161 
See that ticket for remaining tasks after this PR is merged

Release 8.1.0

---

apps/minifront/src/components/dashboard/assets-table/helpers.ts
apps/minifront/src/components/send/helpers.ts
apps/minifront/src/components/shared/asset-selector.tsx
apps/minifront/src/components/swap/helpers.ts
packages/ui/components/ui/tx/view/value/index.tsx

close #1172
This PR also contains other asset display fixes

fix the display of some known assets

---

apps/extension/package.json
apps/minifront/package.json
packages/services-context/package.json
packages/storage/package.json
pnpm-lock.yaml

Pairs with: https://github.com/prax-wallet/registry/pull/42
New gm/gn icons + fixed uusdc numeraire

Update to latest registry

---

apps/extension/.env.testnet
apps/minifront/src/components/shared/asset-selector.tsx
packages/query/src/block-processor.ts
packages/services/src/view-service/asset-metadata-by-id.ts
packages/ui/components/ui/tx/view/value/index.test.tsx
packages/ui/components/ui/tx/view/value/index.tsx
packages/wasm/crate/src/metadata.rs

Discussion regarding this PR: https://discord.com/channels/824484045370818580/1044457038886998137/1245709532701917336

customize ICS20 assets symbol

---

.changeset/tasty-eels-live.md
apps/extension/package.json
apps/minifront/package.json
apps/node-status/package.json
package.json
packages/bech32m/package.json
packages/client/package.json
packages/getters/package.json
packages/perspective/package.json
packages/protobuf/package.json
packages/query/package.json
packages/services-context/package.json
packages/services/package.json
packages/storage/package.json
packages/transport-chrome/package.json
packages/transport-dom/package.json
packages/types/package.json
packages/ui/package.json
packages/wasm/package.json
pnpm-lock.yaml

also added a convenience script to root package.json
https://github.com/penumbra-zone/web/blob/cd9b1758c834a92f2c498089ee6feab98d6e1cb3/package.json#L9

update buf packages

---

packages/wasm/crate/Cargo.lock
packages/wasm/crate/Cargo.toml

follows https://github.com/penumbra-zone/web/pull/1222

v0.77-deps

---

.changeset/chilly-terms-tease.md
packages/bech32m/package.json
packages/client/package.json
packages/getters/package.json
packages/perspective/package.json
packages/protobuf/package.json
packages/transport-dom/package.json
packages/wasm/package.json

not sure why this failure didn't surface before publish :/

"default export should be the last one"

---

.changeset/fair-monkeys-sell.md
apps/minifront/src/components/ibc/ibc-out/ibc-out-form.tsx
apps/minifront/src/components/send/send-form/index.tsx
apps/minifront/src/components/shared/input-token.tsx
apps/minifront/src/components/staking/account/delegation-value-view/staking-actions/form-dialog.tsx
apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
packages/types/src/lo-hi.ts
packages/types/src/value-view.ts
packages/ui/components/ui/balance-value-view.test.tsx
packages/ui/components/ui/balance-value-view.tsx
packages/ui/components/ui/tx/view/value/index.tsx

Closes https://github.com/penumbra-zone/web/issues/1069
Allows the ibc, send, and swap forms to click the balance to insert max amount (quite helpful for amounts with many digits).
https://github.com/penumbra-zone/web/assets/16624263/421f13a2-d572-42a2-b815-ba27b618a2f0

Select max input option

---

.changeset/healthy-kids-taste.md
apps/minifront/src/components/tx-details/tx-viewer.tsx
packages/protobuf/src/registry.ts
packages/wasm/crate/src/tx.rs
packages/wasm/package.json
packages/wasm/src/transaction.ts
pnpm-lock.yaml

fixes #1254 
relevant https://github.com/penumbra-zone/penumbra/issues/4563

IBC `Any` ser/de

---

README.md

Added some basic info that I missed during the onboarding

fix(docs): update installation info

---

apps/minifront/src/state/swap/dutch-auction/time-until-next-event.ts

@erwanor does this look OK to you? And does the comment describe it accurately?

Simplify Poisson distribution function

---

packages/getters/src/swap-view.ts

@grod220 missed this, references https://github.com/penumbra-zone/web/commit/a522feb33bc898c82bad1eb0b80a86cc5ef9e2da#r143040583

getter type inference

---

packages/query/src/block-processor.ts

References https://github.com/penumbra-zone/web/issues/1308.

cleanup comments in block processor

---

.changeset/calm-mirrors-repair.md

Fixes changeset publishing block on main

Update changeset package name

---

packages/crypto/src/encryption.ts

References https://github.com/penumbra-zone/web/pull/1140#discussion_r1609735586

encryption: avoid throwing error

---

.changeset/pretty-snakes-bow.md

can't release without fixing changeset

fix changeset

---

.changeset/fuzzy-ravens-dream.md
apps/minifront/src/components/shared/balance-selector.tsx
apps/minifront/src/components/swap/helpers.ts
apps/minifront/src/state/send.ts

This fixes bugs related to unknown assets, users can still send unknown assets 
closes #1328
closes #1289

fix balance selector search

---

docs/adrs/004-privacy-invariants.md

references https://github.com/penumbra-zone/web/issues/1345

audit privacy invariants

---

README.md
apps/minifront/README.md
packages/ui/package.json

closes https://github.com/penumbra-zone/web/issues/1329

Add minifront deployment docs

---

.changeset/afraid-pans-crash.md
packages/ui/components/ui/tx/actions-views/undelegate.tsx

feat: #1318: undelegate epoch

---

packages/transport-dom/src/create.ts

remove unnecessary warning

---

apps/minifront/src/components/send/send-form/index.tsx
apps/minifront/src/components/shared/input-token.tsx
apps/minifront/src/components/shared/selectors/asset-selector.tsx
apps/minifront/src/components/shared/selectors/balance-selector.tsx
apps/minifront/src/components/shared/selectors/loading-indicator.tsx
apps/minifront/src/components/swap/swap-form/token-swap-input.tsx

Show a loading indicator for asset selectors

---

.changeset/honest-pears-fly.md
apps/minifront/src/components/swap/auction-list/filters.tsx
apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.test.ts
apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.ts
apps/minifront/src/components/swap/auction-list/helpers.ts
apps/minifront/src/components/swap/auction-list/index.tsx
apps/minifront/src/state/swap/dutch-auction/index.ts

See inline comments.
Closes #1388

Combine upcoming + active auctions

---

.github/workflows/compile-wasm.yml
.github/workflows/deploy-firebase-dapp.yml
.github/workflows/packages-release.yml
.github/workflows/turbo-ci.yml
package.json

update pnpm action

---

.github/workflows/compile-wasm.yml
.github/workflows/packages-release.yml
.github/workflows/turbo-ci.yml

update buildjet cache action version

---

apps/minifront/src/components/header/header.tsx
apps/minifront/src/components/header/menu/nav-style.tsx
apps/minifront/src/components/header/menu/provider.tsx
apps/minifront/src/components/header/menu/tablet-nav.tsx

fix(minifront): #1379: fix header menu position and styles

---

packages/ui/components/ui/tx/action-view.tsx
packages/ui/components/ui/tx/actions-views/swap/index.test.tsx
packages/ui/components/ui/tx/actions-views/swap/index.tsx
packages/ui/components/ui/tx/index.tsx

corresponding prax PR: https://github.com/prax-wallet/web/pull/85. fixes regressions from https://github.com/penumbra-zone/web/issues/1265
**before**
----------------------------------------------------------------------------------------------------------------------------
**after**

improve fee rendering in transaction details page

---

.changeset/large-avocados-decide.md
packages/services/src/view-service/balances.test.ts
packages/services/src/view-service/balances.ts
packages/storage/src/indexed-db/index.ts
packages/storage/src/indexed-db/indexed-db.test.ts
packages/types/src/assets.ts
packages/types/src/indexed-db.ts

1441 use the epochduration based price relevance thresholds for delegation token prices

---

.changeset/five-jobs-speak.md
apps/minifront/src/components/header/menu/menu.tsx
apps/minifront/src/components/header/menu/tablet-nav.tsx

fix: #1447: fix tablet menu

---

.changeset/three-oranges-beam.md
packages/transport-dom/src/create.ts

annotate return type of createChannelTransport

---

.changeset/small-queens-drum.md
packages/client/src/manifest.ts

fix(client): manifest check

---

packages/ui/package.json
pnpm-lock.yaml

This is one of a number of PRs I'm splitting off from https://github.com/penumbra-zone/web/pull/1464/files

Uninstall unused @mui/material package

---

apps/minifront/src/components/swap/unclaimed-swaps.tsx

references https://github.com/penumbra-zone/web/issues/1437
https://github.com/user-attachments/assets/25119b6a-6b4f-4664-bb89-e6523cbd6e07

swaps: prevent multiple swap claims

---

apps/minifront/src/state/swap/dutch-auction/index.ts

references https://github.com/penumbra-zone/web/issues/1494

auctions: add source to transaction planner request

---

packages/react/src/components/penumbra-context-provider.tsx

i'm not sure why this was able to merge with a format violation. possibly related to https://github.com/penumbra-zone/web/pull/1504

remove space???

---

.changeset/gentle-yaks-tickle.md
packages/protobuf/src/penumbra-core.ts
packages/protobuf/src/web.ts

Unblocks delegator voting type issues

Add additional query services

---

.changeset/eleven-bugs-relate.md
apps/minifront/src/fetchers/block-date.ts
packages/query/src/queriers/sct.ts
packages/query/src/root-querier.ts
packages/services/src/sct-service/index.ts
packages/services/src/sct-service/timestamp-by-height.test.ts
packages/services/src/sct-service/timestamp-by-height.ts
packages/services/src/test-utils.ts
packages/types/src/querier.ts

1479 replace getblockdate implementation

---

.changeset/gorgeous-shrimps-push.md
packages/wasm/crate/src/tx.rs

Unblocks delegator vote building

Add witness for delegator vote plans

---

apps/minifront/src/components/shared/edu-panels/content.tsx

references https://github.com/penumbra-zone/web/issues/1548
open to suggestions here

modify description for shielded swaps

---

.changeset/afraid-seals-sit.md
apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.test.ts
apps/minifront/src/components/swap/auction-list/index.tsx
apps/minifront/src/fetchers/auction-infos.ts
apps/minifront/src/state/swap/dutch-auction/index.ts
packages/ui/components/ui/dutch-auction-component/expanded-details/index.tsx
packages/ui/components/ui/dutch-auction-component/index.tsx

1555 cannot end and withdraw auction from accounts other than 0 account

---

apps/minifront/src/components/swap/swap-form/index.tsx
apps/minifront/src/components/swap/swap-form/price-history.tsx
apps/minifront/src/components/swap/swap-form/simulate-swap-result/index.tsx
apps/minifront/src/components/swap/swap-form/simulate-swap.tsx
apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
apps/minifront/src/state/swap/helpers.ts
apps/minifront/src/state/swap/price-history.ts
packages/ui/components/ui/candlestick-plot/index.tsx

fixes https://github.com/penumbra-zone/web/issues/1530
fixes #1529 
- move candlestick chart from token input to independent component
- use zquery for fetching candlestick data
- some minor changes to graph rendering

candlestick chart updates

---

.changeset/afraid-trains-compare.md
packages/perspective/src/plan/view-action-plan.ts
packages/perspective/src/transaction/classification.ts
packages/perspective/src/transaction/classify.test.ts
packages/perspective/src/transaction/classify.ts
packages/ui/components/ui/tx/action-view.tsx
packages/ui/components/ui/tx/actions-views/delegator-vote.tsx
packages/ui/components/ui/tx/actions-views/validator-vote.tsx
packages/ui/package.json
pnpm-lock.yaml

Closes https://github.com/penumbra-zone/web/issues/1572
Adds remaining tx labels & validator vote action views.
Before:
After:

More classifications

---

.changeset/forty-ties-serve.md
.changeset/giant-years-deny.md
packages/services/src/view-service/asset-metadata-by-id.test.ts
packages/services/src/view-service/asset-metadata-by-id.ts
packages/storage/src/indexed-db/config.ts

Allows for receipt tokens not seeing previously to be rendered correctly

Customize symbol on denom query

---

.changeset/afraid-seals-sit.md
.changeset/afraid-trains-compare.md
.changeset/forty-ties-serve.md
.changeset/giant-years-deny.md
.changeset/gold-crews-know.md
.changeset/old-jobs-type.md
apps/minifront/CHANGELOG.md
apps/minifront/package.json
apps/node-status/CHANGELOG.md
apps/node-status/package.json
packages/perspective/CHANGELOG.md
packages/perspective/package.json
packages/query/CHANGELOG.md
packages/query/package.json
packages/services/CHANGELOG.md
packages/services/package.json
packages/storage/CHANGELOG.md
packages/storage/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/wasm/CHANGELOG.md
packages/wasm/package.json
pnpm-lock.yaml

Running manually so I can update the registry along with these

Version packages

---

.changeset/khaki-rabbits-reflect.md
apps/minifront/src/components/ibc/ibc-out/ibc-out-form.tsx
apps/minifront/src/components/send/send-form/index.tsx
apps/minifront/src/components/shared/input-token.tsx
apps/minifront/src/state/ibc-out.ts
apps/minifront/src/state/send/index.ts

fix send form memory bug

---

apps/minifront/src/components/dashboard/assets-table/index.tsx
apps/minifront/src/state/helpers.ts

Update text + remove temp source remover

---

apps/minifront/src/components/ibc/ibc-out/chain-selector.tsx

~~merge this to main to revert the entire repository to a31d54a5b2d10541daf8ed0b4fb9b218003b2126 (the last PD bundled version) plus a~~ one-line diff to disable noble https://github.com/penumbra-zone/web/pull/1617/commits/7b34ee4071951f2b900f9c35f02d718738bc62db
this will activate minifront-deployer actions within 6 hours
https://github.com/penumbra-zone/minifront-deployer/blob/main/.github/workflows/deploy-minifront.yml
edit: just a one-line diff

disable noble

---

apps/minifront/src/components/dashboard/assets-table/index.tsx
apps/minifront/src/fetchers/balances/index.ts
apps/minifront/src/state/shared.ts
apps/minifront/src/state/staking/index.test.ts

feat: loading spinner and streaming for assets table

---

apps/minifront/src/components/dashboard/assets-table/index.tsx
apps/minifront/src/fetchers/balances/index.ts
apps/minifront/src/state/shared.ts
apps/minifront/src/state/staking/index.test.ts

Reverts penumbra-zone/web#1625
avoiding rebase conflict with #1623

Revert "feat: loading spinner and streaming for assets table"

---

.changeset/chilled-wombats-approve.md
apps/minifront/src/components/staking/account/delegation-value-view/index.test.tsx
apps/minifront/src/state/staking/index.test.ts
packages/services/src/view-service/auctions.test.ts
packages/services/src/view-service/auctions.ts
packages/services/src/view-service/delegations-by-address-index.ts
packages/services/src/view-service/unbonding-tokens-by-address-index/index.ts

this is the correct way to create a packed `Any` message

use `Any.pack` instead of manually creating `Any` message

---

.changeset/beige-files-promise.md
.changeset/good-ligers-tan.md
.changeset/modern-wombats-shake.md
.changeset/strong-games-design.md
packages/getters/src/compact-block.ts
packages/getters/src/spendable-note-record.ts
packages/query/src/block-processor.ts
packages/query/src/helpers/process-action-dutch-auction-end.test.ts
packages/query/src/helpers/process-action-dutch-auction-end.ts
packages/query/src/helpers/process-action-dutch-auction-schedule.ts
packages/query/src/helpers/process-action-dutch-auction-withdraw.ts
packages/services/src/view-service/asset-metadata-by-id.ts
packages/storage/src/indexed-db/index.ts
packages/storage/src/indexed-db/indexed-db.test-data.ts
packages/storage/src/indexed-db/indexed-db.test.ts
packages/types/src/indexed-db.ts

this is intended to encourage callers to ensure proper input when querying idb, until a more comprehensive and well-typed interface is implemented.

assert lengths of binary field inputs to idb methods

---

.changeset/tame-bananas-give.md
apps/minifront/src/components/swap/auction-list/filters.tsx
apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.test.ts
apps/minifront/src/components/swap/auction-list/get-filtered-auction-infos.ts
apps/minifront/src/components/swap/auction-list/helpers.ts
apps/minifront/src/components/swap/auction-list/index.tsx
apps/minifront/src/state/swap/dutch-auction/index.ts

1678 adjust active auction filter

---

.github/workflows/deploy-ui-preview-main.yml
.github/workflows/deploy-ui-preview-pr.yml
.github/workflows/deploy-ui-release.yml

actually fix storybook CI

---

.changeset/large-chefs-attack.md
apps/minifront/src/components/header/header.tsx
apps/minifront/src/components/tx-details/index.tsx
package.json
packages/ui/components/ui/banner/banner.test.tsx
packages/ui/components/ui/banner/index.tsx
packages/ui/components/ui/button/index.tsx
packages/ui/components/ui/fade-transition/index.tsx
packages/ui/components/ui/incompatable-browser-banner/get-compatability.ts
packages/ui/components/ui/incompatable-browser-banner/incompatable-browser-banner.test.tsx
packages/ui/components/ui/incompatable-browser-banner/index.tsx
packages/ui/components/ui/splash-page/index.tsx
packages/ui/components/ui/testnet-banner/index.tsx
packages/ui/package.json
pnpm-lock.yaml

Addresses #1666 
**Changes**
- Added generic Banner component
- Added IncompatableBrowserBanner component to splash screen and layout (header component)
- Fixed splash screen UI on mobile
- Fixed buttons not to shrink
Before:
After:

Add Banner and IncompatableBrowserBanner

---

packages/query/src/block-processor.ts

review suggestions. use work up to 8fe9234c988abf4b284b3996da98963ec430b631
commits after 8fe9234c988abf4b284b3996da98963ec430b631 should become a new issue

local genesis PR suggestions

---

.changeset/ninety-books-deliver.md
packages/query/src/block-processor.ts
packages/types/src/block-processor.ts

references https://github.com/prax-wallet/web/issues/161 and https://github.com/prax-wallet/web/pull/163
most of the changes in the diff are formatting, related to moving the core logic for processing a compact block into a dedicated [processBlock](https://github.com/penumbra-zone/web/pull/1706/files#diff-ccb0493c986b958cf859e773170457e5ff59a4a2e0d742698492247f6ae872daR186) method.

sync: add bundled genesis compact block to block processor 

---

apps/minifront/src/components/header/header.tsx
packages/ui/components/ui/incompatable-browser-banner/index.tsx
packages/ui/components/ui/incompatible-browser-banner/get-compatibility.ts
packages/ui/components/ui/incompatible-browser-banner/incompatible-browser-banner.test.tsx
packages/ui/components/ui/incompatible-browser-banner/index.tsx
packages/ui/components/ui/splash-page/index.tsx

Correct spelling 'incompatable' => 'incompatible'

---

.changeset/dull-mails-lick.md
packages/wasm/crate/src/planner.rs
packages/wasm/crate/tests/test_insufficient_notes.rs

references https://github.com/penumbra-zone/web/issues/1413 and https://github.com/prax-wallet/web/issues/148

fees: clearer error message

---

.changeset/nice-mugs-dance.md
.changeset/quick-buttons-care.md
apps/minifront/src/components/dashboard/assets-table/index.tsx
apps/minifront/src/components/swap/layout.tsx
apps/minifront/src/components/swap/lp-positions.tsx
apps/minifront/src/components/swap/swap-form/index.tsx
apps/minifront/src/components/swap/swap-form/limit-order.tsx
apps/minifront/src/state/swap/index.ts
apps/minifront/src/state/swap/lp-positions.ts
packages/perspective/src/plan/view-action-plan.ts
packages/query/src/block-processor.ts
packages/ui/components/ui/tx/action-view.tsx
packages/ui/components/ui/tx/actions-views/position-close.tsx
packages/ui/components/ui/tx/actions-views/position-open.tsx
packages/ui/components/ui/tx/actions-views/position-withdraw.tsx
packages/wasm/crate/src/metadata.rs
packages/wasm/crate/src/planner.rs

Closes https://github.com/penumbra-zone/web/pull/1739
Also some preliminary work on supporting limit order actions
(will require a mirror PR for the duplicate action view code in Prax)

LP action views

---

apps/minifront/src/components/ibc/ibc-in/chain-provider.tsx

references https://github.com/penumbra-zone/web/issues/1700

silence IBC warnings

---

apps/minifront/src/components/send/send-form/index.tsx
apps/minifront/src/components/shared/non-native-fee-warning.tsx
apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
apps/minifront/src/fetchers/gas-prices.ts
apps/minifront/src/state/shared.ts
apps/minifront/src/state/swap/index.ts

references https://github.com/penumbra-zone/web/pull/1698#discussion_r1721478977

Refactoring spend max

---

.changeset/late-tigers-rush.md
apps/minifront/src/state/status.ts

references https://github.com/penumbra-zone/web/issues/1758

sync: display sync percentage 

---

.changeset/itchy-files-flow.md

Fix changeset package name

---

apps/minifront/src/components/ibc/ibc-in/ibc-in-request.tsx
apps/minifront/src/components/ibc/ibc-out/chain-selector.tsx
packages/ui/components/ui/select/index.tsx
packages/ui/components/ui/select/select.tsx
packages/ui/package.json
pnpm-lock.yaml

Fixes: https://github.com/penumbra-zone/web/issues/1798
Updates shadcnui component to latest version which comes with scrolling. Only in use in shield page.
https://github.com/user-attachments/assets/7869c1c7-0f80-41a0-a358-5e5f74423e9d

Update Select component

---

apps/minifront/src/state/helpers.ts

Closes https://github.com/penumbra-zone/web/issues/1812

Extend timeout for build requests

---

packages/ui/package.json
packages/ui/vite.config.ts

feat: export old ui library

---

.changeset/soft-cats-care.md
packages/protobuf/package.json

Needed for: https://github.com/prax-wallet/prax/issues/206
Protos published here: https://buf.build/noble-assets/forwarding/docs/v1.x:noble.forwarding.v1

Generate noble protos

---

.changeset/funny-knives-refuse.md
packages/wasm/crate/Cargo.lock
packages/wasm/crate/Cargo.toml
packages/wasm/crate/src/keys.rs
packages/wasm/crate/tests/test_keys.rs
packages/wasm/src/keys.ts

Related to: https://github.com/prax-wallet/prax/issues/206 & https://github.com/penumbra-zone/penumbra/pull/4878
Exposes helpers needed to generate noble forwarding addresess.

Noble forwarding wasm helpers

---

apps/minifront/src/components/staking/account/delegation-value-view/staking-actions/form-dialog.tsx
apps/minifront/src/components/staking/account/delegation-value-view/staking-actions/index.test.tsx

Closes https://github.com/penumbra-zone/web/issues/1892
https://github.com/user-attachments/assets/9c5a2a0f-58e6-41ac-bfc2-c5a06417e379

Warning when voting power high

---

.changeset/friendly-dolphins-invite.md
apps/minifront/src/components/dashboard/assets-table/index.tsx
apps/minifront/src/components/shared/selectors/balance-item.tsx
apps/minifront/src/components/shared/selectors/balance-selector.tsx
apps/minifront/src/components/swap/swap-form/token-swap-input.tsx
packages/ui-deprecated/components/ui/account-switcher/account-switcher.test.tsx
packages/ui-deprecated/components/ui/account-switcher/index.tsx
packages/ui-deprecated/components/ui/address-view/index.tsx

fix(minifront): #1897: sub account terminology

---

.changeset/slow-cats-punch.md
packages/types/package.json
packages/types/src/round.test.ts
packages/types/src/round.ts
packages/types/src/shortify.ts
pnpm-lock.yaml

Removing trailing zeros + exponential number support
Updates after https://github.com/penumbra-zone/web/pull/1915

Round func updates

---

.changeset/dull-dolphins-sell.md
packages/ui/src/Tabs/index.tsx

fixes https://github.com/penumbra-zone/dex-explorer/issues/147

feat: don't show outline unless focused by keyboard

---

.changeset/thick-monkeys-march.md
packages/ui/package.json
packages/ui/src/Slider/index.tsx

- Adds the `value` prop to the Slider component to allow it to be controlled.

Controlled Slider

---

.changeset/smooth-radios-turn.md
apps/minifront/src/components/dashboard/assets-table/index.tsx

updates the IBC route from https://penumbra.zechub.org/#/ibc to https://penumbra.zechub.org/#/deposit/skip.
-----------------------
https://github.com/user-attachments/assets/3c9d971b-a21a-49e7-9e2b-735dd96bcb64

ui: fix ibc route

---

.changeset/beige-forks-tell.md
packages/types/src/pnum.test.ts
packages/types/src/pnum.ts

Add toValueView() to pnum

---

.changeset/honest-wasps-itch.md
apps/minifront/src/state/ibc-in/index.tsx
apps/minifront/src/state/ibc-out.ts

fix: #1957: unblock ibc deposits and withdrawals

---

apps/minifront/package.json
package.json
pnpm-lock.yaml

Add resolution for feather js

---

.changeset/beige-boxes-sparkle.md

A missed package bump from https://github.com/penumbra-zone/web/pull/2005

chore: release protobuf

---

.changeset/soft-horses-grab.md
apps/minifront/package.json
pnpm-lock.yaml

bump skip widget version and bump minifront version

fix: bump skip widget to fix penumbra noble transparent addresses

---

.changeset/pretty-hotels-shop.md
packages/ui/package.json
packages/ui/src/SegmentedControl/index.stories.tsx
packages/ui/src/SegmentedControl/index.tsx
packages/ui/src/utils/typography.ts
pnpm-lock.yaml

Closes #2044 
Implements `SegmentedControl` UI component with full accessibility support and v2 styles.
Result: https://penumbra-ui-preview--pr2045-feat-2044-segmented-sag1nfoe.web.app/?path=/docs/ui-library-segmentedcontrol--docs

feat(ui): #2044: `SegmentedControl` UI component

---

packages/transport-dom/src/create.test.ts

expand transport-dom test coverage, greatly improve existing tests, add more test cases

transport-dom: improve tests

---

.changeset/plenty-dryers-shop.md
packages/transport-chrome/src/session-client.ts

use a timeout instead of a recorded time

session client timeout

---

apps/dex-explorer/eslint.config.js
apps/dex-explorer/package.json
apps/dex-explorer/src/features/cosmos/chain-provider.tsx
apps/dex-explorer/src/pages/explore/ui/preview-chart/preview-adapter.test.ts
apps/minifront/src/components/ibc/deposit-manual/chain-provider.tsx
package.json
packages/configs/package.json
packages/ui-deprecated/package.json
packages/ui-deprecated/src/PenumbraUIProvider/index.tsx
pnpm-lock.yaml
turbo.json

fix: make lint and test CI depend on build step

---

apps/veil/app/tournament/[epoch]/page.ts
apps/veil/app/tournament/page.tsx
apps/veil/src/pages/tournament/ui/landing-card/index.tsx
apps/veil/src/pages/tournament/ui/landing-card/voting-footer.tsx
apps/veil/src/pages/tournament/ui/round/page.tsx
apps/veil/src/pages/tournament/ui/round/round-card/index.tsx
apps/veil/src/pages/tournament/ui/round/round-card/voting-section.tsx
apps/veil/src/pages/tournament/ui/shared/gradient-card.tsx
apps/veil/src/shared/const/pages.ts

Implements https://github.com/penumbra-zone/web/issues/2116 (with dummy data)
Same as  https://github.com/penumbra-zone/dex-explorer/pull/406

[LQT] Round card

---

.changeset/deep-suns-carry.md
packages/ui-deprecated/package.json
packages/ui/package.json
packages/ui/src/Checkbox/index.stories.tsx
packages/ui/src/Checkbox/index.tsx
packages/ui/src/theme/theme.ts
packages/ui/src/utils/color.ts
pnpm-lock.yaml

Closes #2192
Live version: https://penumbra-ui-preview--pr2217-feat-2192-checkbox-pmncxggz.web.app/?path=/docs/ui-library-checkbox--docs

feat(ui): #2192: Checkbox

---

apps/veil/next.config.mjs

fixes failed require of pino-pretty during veil build

externalize pino-pretty

---

.changeset/shaky-lights-go.md
apps/minifront/src/components/syncing-dialog/index.tsx
apps/minifront/src/components/syncing-dialog/sync-animation.tsx
apps/minifront/src/state/status.ts

address some issues with the syncing modal.
~~also, some arbitrary changes to the appearance.~~
keep in mind the orange error text is only visible in debug mode.

Improve syncing modal

---

.changeset/yummy-carrots-jam.md
apps/veil/src/pages/tournament/api/vote.ts
apps/veil/src/pages/tournament/ui/vote-dialogue.tsx
packages/wasm/crate/src/planner.rs
packages/wasm/crate/tests/test_liquidity_tournament_voting.rs

roll over delegation notes in the wasm planner for LQT actions
references https://github.com/penumbra-zone/web/issues/2065

LQT: prevent nullifier linkability 

---

apps/veil/next.config.mjs
apps/veil/src/features/cosmos/chain-provider.tsx
apps/veil/src/pages/portfolio/ui/shield-unshield.tsx

fixes #2311 
Current fixes:
- Lazy-load the skip widget, speeding up the page load significantly.

fix: lazy-load the skip widget, saving a lot of time

---

apps/veil/src/entities/leaderboard/ui/page.tsx
apps/veil/src/features/cosmos/cosmos-connect-button.tsx
apps/veil/src/features/cosmos/use-augmented-balances.ts
apps/veil/src/pages/portfolio/ui/asset-bars.tsx
apps/veil/src/pages/portfolio/ui/onboarding.tsx

fixes #2308 
addresses the destructuring error, plus cleans up some other lints and type assertions.

fix: lints and assertions

---

packages/storage/src/indexed-db/index.ts
packages/types/src/indexed-db.ts
packages/types/src/querier.ts
packages/types/src/servers.ts
packages/wasm/crate/src/database/mock.rs
packages/wasm/crate/src/storage.rs
packages/wasm/crate/src/view_server.rs
packages/wasm/src/view-server.test.ts
packages/wasm/src/view-server.ts

Quick sync: improvements

---

apps/minifront/src/components/syncing-dialog/index.tsx

We need to hammer that this is a local first experience. And the instruction should be worded in terms of a positive.
>Copy changes

minifront: sync dialog text

---

apps/veil/src/pages/portfolio/ui/asset-bars.tsx

fix: filter out unknown assets in asset bars

---

apps/veil/src/entities/leaderboard/api/post-lp-leaderboard.ts
apps/veil/src/entities/leaderboard/api/use-lp-leaderboard.ts
apps/veil/src/entities/leaderboard/api/use-my-lp-leaderboard.ts
apps/veil/src/entities/leaderboard/api/utils.ts
apps/veil/src/entities/leaderboard/ui/table.tsx
apps/veil/src/shared/api/env/getClientSideEnv.ts
apps/veil/src/shared/api/env/types.ts
apps/veil/src/shared/api/transport.ts
apps/veil/src/shared/utils/serializer.ts

Depends on https://github.com/penumbra-zone/web/pull/2320

LP Leaderboard data 2/2

---

.changeset/beige-drinks-brake.md
packages/storage/src/indexed-db/index.ts
packages/types/src/indexed-db.ts

for consistency with present behavior

fix: don't specify the autoincremeting key when setting epoch

---

.changeset/tricky-keys-stay.md

minor version bump to types package to complement latest storage changes in https://github.com/penumbra-zone/web/pull/2377

changeset: bump types package

---

apps/veil/src/pages/trade/ui/route-book/spread-row.tsx
apps/veil/src/pages/trade/ui/route-book/trade-row.tsx
apps/veil/src/pages/trade/ui/route-book/utils.ts
apps/veil/src/shared/api/server/book/helpers.ts
apps/veil/src/shared/api/server/book/index.ts

Closes https://github.com/penumbra-zone/web/issues/2273
Fixes wrong amounts caused by a comma in the string (which cant be parsed properly).

Fix Route Book

---

apps/veil/src/entities/transaction/api/plan-build-broadcast.tsx

feat: display unfilled amount in swap claim tx.

---

apps/veil/src/pages/tournament/api/use-tournament-votes.ts
apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx

fix: only allow voting in current results when able

---

apps/veil/src/pages/tournament/server/delegator-history.ts
apps/veil/src/pages/tournament/ui/delegator-rewards.tsx
apps/veil/src/pages/tournament/ui/lp-rewards.tsx
apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx

fixes some regressions from https://github.com/penumbra-zone/web/pull/2365, cc @VanishMax 
https://github.com/penumbra-zone/web/issues/2350

rewards: fix bugs in the rewards table

---

apps/minifront/package.json
apps/veil/package.json
apps/veil/src/pages/tournament/server/epoch-results.ts
packages/storage/package.json
pnpm-lock.yaml

following https://github.com/prax-wallet/registry/pull/146, pass in 'force-cache' option to the registry client to get server-side caching.

feat: implement caching for registry data in epoch results

---

apps/veil/src/pages/tournament/api/use-index-by-address.ts
apps/veil/src/pages/tournament/api/use-personal-rewards.ts
apps/veil/src/pages/tournament/server/delegator-history.ts

fix(veil): #2414: filter delegator rewards in the client side

---

apps/veil/src/pages/tournament/ui/delegator-leaderboard.tsx

fix(veil): #2438: delegator leaderboard infinite loading

---

.changeset/chilly-feet-beam.md
.github/workflows/packages-release.yml

fix https://github.com/penumbra-zone/web/issues/2452

fix: publish workflow should build the packages

---

.github/workflows/packages-release.yml
justfile

fix: fix publish workflow fix

---

apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx

Hides the "Vote now" button from the round page if user can't actually vote.

fix(veil): voting button on round page

---

apps/veil/src/entities/leaderboard/ui/table.tsx
apps/veil/src/pages/tournament/ui/delegator-leaderboard.tsx
apps/veil/src/pages/tournament/ui/landing-card/results.tsx
apps/veil/src/pages/tournament/ui/round/current-voting-results/table-row.tsx
apps/veil/src/pages/tournament/ui/shared/provide-liquidity-button.tsx

fix(veil): #2486: add liquidity link to tournament landing card

---

apps/veil/src/pages/tournament/ui/round/round-card.tsx

Closes #2547 
References #2538 
Uses `epochs: [epoch]` filter in the summary query for the round card instead of requesting current epoch summary.
Also, adds a nice little tooltip over "Ends in XX time" with the same formatting as in GitHub:

fix(veil): #2547: round card end time and blocks

---

.github/workflows/fly-cleanup-pr.yml
.github/workflows/fly-deploy-pr.yml
apps/veil/Dockerfile
apps/veil/docs/fly-deployment.md
apps/veil/fly.toml

This adds a minimal container image, and a fly.io deployment step for every PR. It is triggered by commenting /deploy and garbage collected every twelve hours. That's on purpose!

ci: fly ephemeral deploys

---

.github/workflows/fly-deploy-pr.yml

ci(fly): ultimate fix to deploy step

---

apps/veil/package.json
apps/veil/src/pages/portfolio/index.tsx
apps/veil/src/shared/api/server/shielding-deposits.ts
apps/veil/src/shared/api/use-shielding-deposits.ts
apps/veil/src/shared/database/schema.ts
apps/veil/src/widgets/shielding-ticker/index.tsx
pnpm-lock.yaml

feat: shielding stream

---

apps/veil/src/entities/tournament/api/vote.ts
apps/veil/src/pages/tournament/ui/vote-dialog/index.tsx

avoids casting denom to lowercase
N/A

proper denom handling

---

.github/workflows/fly-cleanup-pr.yml
.github/workflows/fly-deploy-pr.yml
apps/veil/justfile
ci/fly-cleanup-pr-deployments
ci/fly-deploy-branch
flake.nix
justfile

Some small tweaks to the fly logic:
* ci: port flyctl cleanup script out of yaml
* ci: port flyctl deploy script out of yaml
* ci: add flyctl to nix devshell
* ci: add BASE_URL to runtime env
* ci: fix fly cleanup script
These were prepared to ahead of config refactors like #2593, to aid in review over there.
Follow up to fly logic introduced in https://github.com/penumbra-zone/web/pull/2563

ci: tooling updates for fly deployments

---

apps/veil/src/pages/tournament/ui/previous-epochs.tsx
apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx
apps/veil/src/pages/tournament/ui/shared/bug.tsx

fix(veil): #2628: explain epochs with votes not adding up to 100%
